### ISSUE TITLE
Problema con configurazione mail

### ISSUE THREAD

**Issue by manuelbarberi** [iisgiua/giuaschool#235]
Altervista non permette la configurazione mail corretta. Altre opzioni per risolvere?

**Comment by trinko** [comment]
Credo che Altervista permetta solo l'uso di sendmail. 
Hai provato impostando la configurazione con *Usa server locale (SENDMAIL)*?
In tal caso, che errore viene riportato quando si effettua l'invio della mail di test?

**Comment by manuelbarberi** [comment]
Uncaught TypeError: stream_set_blocking(): Argument #1 ($stream) must be of type resource, null given in /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/Stream/ProcessStream.php:42 Stack trace: #0 /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/Stream/ProcessStream.php(42): stream_set_blocking(NULL, false) #1 /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(249): Symfony\Component\Mailer\Transport\Smtp\Stream\ProcessStream->initialize() #2 /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(192): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start() #3 /membri/registromanututorial/vendor/symfony/mailer/Transport/AbstractTransport.php(67): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend(Object(Symfony\Component\Mailer\SentMessage)) #4 /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(132): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mailer\SentMessage), Object(Symfony\Component\Mailer\DelayedEnvelope)) #5 /membri/registromanututorial/vendor/symfony/mailer/Transport/SendmailTransport.php(70): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send(Object(Symfony\Component\Mime\Email), NULL) #6 /membri/registromanututorial/vendor/symfony/mailer/Mailer.php(41): Symfony\Component\Mailer\Transport\SendmailTransport->send(Object(Symfony\Component\Mime\Email), NULL) #7 /membri/registromanututorial/src/Install/Installer.php(1108): Symfony\Component\Mailer\Mailer->send(Object(Symfony\Component\Mime\Email)) #8 /membri/registromanututorial/src/Install/Installer.php(1432): App\Install\Installer->testEmail('test@noreply.no', 'manuelbarberi.m...') #9 /membri/registromanututorial/src/Install/Installer.php(257): App\Install\Installer->pageEmail() #10 /membri/registromanututorial/public/install/index.php(12): App\Install\Installer->run() #11 {main} thrown in /membri/registromanututorial/vendor/symfony/mailer/Transport/Smtp/Stream/ProcessStream.php on line 42

**Comment by manuelbarberi** [comment]
@trinko

**Comment by trinko** [comment]
Puo riportare il contenuto che trovi, subito dopo che viene visualizzato l'errore, nel file **.env** per il parametro **MAILER_DSN**?

**Comment by manuelbarberi** [comment]
Si ora lo riporto

**Comment by trinko** [comment]
Ho fatto dei test: purtroppo Altervista non supporta l'invio delle mail via SENDMAIL. 
L'unica modalità utilizzabile su Altervista non è implementata nella libreria di gestione delle mail che utilizzo nel registro.

Sarà necessario scrivere il codice necessario, ma non so quando sarà possibile farlo.

**Comment by manuelbarberi** [comment]
Entro quando verrà riscritto?

**Comment by sempliciniluigi89** [comment]
Ma nemmeno *X10HOSTING* se non sbaglio, a questo punto quale hosting
sopporta la configurazione email?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/13/22,
12:25:13 AM

Il giorno lun 13 giu 2022 alle ore 00:00 Manu ***@***.***> ha
scritto:

**Comment by manuelbarberi** [comment]
Non si sà esattamente quando verrà inserito... esiste già una issue con la richiesta mail... Provvedo a chiudere questa.
