### ISSUE TITLE
Mail con altervista

### ISSUE THREAD

**Issue by manuelbarberi** [iisgiua/giuaschool#286]
La mail con altervista non funziona... quando uscirà l'aggiornamento che risolverà il problema?

**Comment by trinko** [comment]
Francamente non lo so. Forse riesco a inserirla per la versione del prossimo anno scolastico, ma non sono sicuro di farcela.

**Comment by manuelbarberi** [comment]
@trinko entro quando verrà inserita la funzione mail?

**Comment by trinko** [comment]
> @trinko entro quando verrà inserita la funzione mail?

Non lo so. Al momento non ho tempo di occuparmene.

**Comment by manuelbarberi** [comment]
@trinko con l'ultimo aggiornamento abbiamo le mail php da altervista?

**Comment by trinko** [comment]
Si, la configurazione viene fatta dal menu SISTEMA > CONFIGURAZIONE EMAIL

**Comment by manuelbarberi** [comment]
Come aggiorno dato che nella relase non c'è il nuovo?

**Comment by trinko** [comment]
Usa il vecchio sistema: carichi i file nuovi e poi lanci l'installazione da: nome_sito://public/install/inedx.php

**Comment by manuelbarberi** [comment]
Dove li trovo i file nuovi?

**Comment by trinko** [comment]
Nell'ultimo aggiornamento:
[Scarica l’ultimo aggiornamento](https://github.com/iisgiua/giuaschool/releases/download/update-v1.5.1/giuaschool-update-v1.5.1.zip)

**Comment by manuelbarberi** [comment]
@trinko quando provo a mandare le credenziali via mail esce questo avviso:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by manuelbarberi** [comment]
Quando provo a configurare la mail esce questo avviso: 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by manuelbarberi** [comment]
@trinko

**Comment by trinko** [comment]
Su Altervista funziona solo utilizzando il **server locale tramite PHP**. 
Devi anche configurare, su **SCUOLA > ISTITUTO**, l'indirizzo email del mittente delle notifiche inviate dal registro.

**Comment by manuelbarberi** [comment]
Non funziona lo stesso.

**Comment by manuelbarberi** [comment]
Il recupero password funziona ma l'invio da admin no.

**Comment by manuelbarberi** [comment]
Adesso Funziona Tutto... Grazie
