### ISSUE TITLE
Cannot run docker image on Mac M1

### ISSUE THREAD

**Issue by wbigger** [iisgiua/giuaschool#299]
Questo è il mio ambiente di sviluppo:
- MacOS Monterey 12.4
- MacBook Air (M1, 2020)
- Docker Engine: 20.10.17

Provando a lanciare da riga di comando:
```sh
docker run -d --name gs_test -p 443:443 --platform linux/amd64 ghcr.io/trinko/giuaschool:1.4.5
```
Il container esce quasi immediatamente (dopo circa 1 secondo).

Eseguendo `docker logs gs_test`, ottengo il seguente risultato:

```
Starting MariaDB database server: mariadbd ..
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 16 22:10:31.365163 2022] [core:emerg] [pid 502] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex
(95)Operation not supported: could not create accept mutex
AH00015: Unable to open logs
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

Note sull'istruzione `docker run`, rispetto alla documentazione:
- ho aggiunto `--platform linux/amd64` per evitare un log di warning, ma il risultato è lo stesso anche senza
- per facilitare la riproducibilità, ho messo la versione esatta del container usato (l'attuale latest)

**Comment by trinko** [comment]
Sembra un problema causato da apache  che viene eseguito come servizio:
`Action '-D FOREGROUND' failed.`

Dovresti provare a eseguire il container senza avviare i servizi, ma entrando nella shell di comando. Ad esempio:

`
docker run -it --name gs_test  --platform linux/amd64 ghcr.io/trinko/giuaschool:1.4.5 /bin/bash
`
Se funziona, prova ad avviare apache per capire come risolvere il problema.
