### ISSUE TITLE
PROBLEMA AGGIORNAMENTO

### ISSUE THREAD

**Issue by nicholas20220** [iisgiua/giuaschool#302]
Buonasera, non riesco a fare l'aggiornamento, chiedo aiuto. grazie

**Comment by trinko** [comment]
Se spieghi il problema forse posso aiutarti. 
Ma se non dici niente sul problema, nessuno potrà aiutarti.

**Comment by nicholas20220** [comment]
lo sa gia' @manuelberberi ci eravamo già messi in contatto sulla mail di guia school ma poi quando mi stava per fare l'aggiornamento non mi ha piu risposto

**Comment by nicholas20220** [comment]
il mio problema è che sono ancora alla versione 1.42 e non so anche con le guide ad aggiornarlo

**Comment by nicholas20220** [comment]
@manuelbarberi

**Comment by trinko** [comment]
Evita di aprire più volte un bug per lo stesso problema: si crea solo confusione.
Grazie.
