### ISSUE TITLE
Il link sulla pagina del registo del giua di rimando a github è rotto

### ISSUE THREAD

**Issue by NF02** [iisgiua/giuaschool#306]
**Quando vai sulla pagina del registro e provi ad accedere al collegamento per visionare i sorgenti della pagina, github ti rende un errore come se la pagina non esistesse.**

**basta semplicemente cliccare sul link in basso a destra**
<img width="1552" alt="Schermata 2022-08-14 alle 13 45 10" src="https://user-images.githubusercontent.com/66777517/184535290-a8bf4410-e2de-4c92-b43e-9772a675fa06.png">

<img width="1552" alt="Schermata 2022-08-14 alle 13 43 58" src="https://user-images.githubusercontent.com/66777517/184535183-6f54c380-4da3-4d98-a71e-2fd728cb918a.png">

**Comment by trinko** [comment]
Grazie per la segnalazione.
Verrà sistemato per la prossima versione 1.5.0

**Comment by NF02** [comment]
effettivamente stavo cercano i sorgenti della pagina per curiosità, visto che sono passate due versioni e volevo vedere cosa era cambiato e la schermata che ho ricevuto era quella e quindi ho deciso di usare il motore di ricerca di github e reperire da li i sorgenti della pagina

**Comment by trinko** [comment]
Corretto.
