### ISSUE TITLE
aiuto @manuelberberi

### ISSUE THREAD

**Issue by nicholas20220** [iisgiua/giuaschool#307]
Buonasera signor Barberi,
Le chiedo la cortesia di aiutarmi ad aggiornare il registro alla versione 1.45 e passare il registro all'anno successivo in quando non sono competente nel campo.
Ringrazio Anticipatamente

**Comment by trinko** [comment]
Evita di aprire più volte un bug per lo stesso problema: si crea solo confusione.
Grazie.
