### ISSUE TITLE
Problema importazione alunni da file .csv

### ISSUE THREAD

**Issue by DhTk** [iisgiua/giuaschool#310]
Ho un problema connesso all'importazione degli alunni da un file csv. Seguo tutto ciò che è riportato all'interno del file csv d'esempio ma non riesco a importare né il mio file né il file di prova presente sul sito di giua@school. Come posso risolvere?
L'errore che il sito mi dà è il seguente: ERRORE I campi del file non corrispondono a quanto previsto nel record 1.

**Comment by trinko** [comment]
Si, c'è un problema con le importazioni che sarà risolto nella prossima versione 1.5.0, penso tra qualche settimana.

**Comment by trinko** [comment]
Risolto nel codice della prossima versione 1.5.0
