### ISSUE TITLE
Errori fatali aggiornamento e installazione

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#322]
Effettuando l'operazione di aggiornamento o di nuova installazione (database completamente pulito), nella fase di scrittura dei database si verificano errori fatali.

[LOG.zip](https://github.com/iisgiua/giuaschool/files/9437811/LOG.zip)

Uno degli errori che compaiono durante l'installazione da zero è questo: In EnvVarProcessor.php line 172: Environment variable not found: "APP_SECRET".

**Comment by trinko** [comment]
Non riesco a riprodurre l'errore. Ho testato l'installazione anche su Altervista senza problemi.

L'unico problema dai log è che non trova un'immagine: puoi sostituire il file seguente nella cartella **public/install**, ma francamente non penso cambi qualcosa.

[page_header.php.zip](https://github.com/iisgiua/giuaschool/files/9439261/page_header.php.zip)
