### ISSUE TITLE
Problema cattedre csv

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#324]
Buonasera ,avrei soltanto un problema: sto provando ad importare le cattedre , ma il sistema continua a dirmi :  I campi del file non corrispondono a quanto previsto nel record 1.

Ora le allego qui sotto il file csv delle cattedre in modo che possa provare anche lei cortesemente a tentare di risolvere il problema ,evidenziando,cortesemente l'errore che non permette la normale continuazione .Grazie
 
https://github.com/iisgiua/giuaschool/files/9440738/cattedre.csv

**Comment by trinko** [comment]
L'errore è che hai inserito più classi nella stessa riga. 
Se un docente ha 4 classi, devono essere inserite 4 righe, tutte riferite allo stesso docente, ma con indicazione delle differenti classi.

Allego il file corretto:

[cattedre-corrette.csv](https://github.com/iisgiua/giuaschool/files/9442873/cattedre-corrette.csv)

**Comment by trinko** [comment]
> Inserendo il file da lei corretto mi da il seguente avviso : La classe non è corretta nel record 1.

Controlla che:

- la classe indicata nella riga 1 del file esista nel sistema ;
- la versione del registro sia la 1.5.0

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
