### ISSUE TITLE
Problema passaggio anno scolastico

### ISSUE THREAD

**Issue by scuolagioco** [iisgiua/giuaschool#326]
c'è un problema durante il passaggio dell'anno scolastico. Andando su Sistema > Nuovo a.s. > seleziono inizia > continua > continua > arrivato qui mi segnala un errore (allego l'immagine).
![E3B6294D-B40D-4BFD-9364-198F252D1A51](https://user-images.githubusercontent.com/96265220/187402699-fddc7908-9bf0-4673-906b-249dcdaa78d2.jpeg)

**Comment by scuolagioco** [comment]
qualcuno potrebbe rispondermi? è urgente.., devo fare il passaggio dell'anno scolastico @bfabio @trinko @zerai @MatteoGheza

**Comment by scuolagioco** [comment]
è urgente, davvero @trinko può aiutarmi

**Comment by trinko** [comment]
Ho bisogno del log degli errori per capire cosa è successo. 
Se non ho capito male, l'errore è durante l'esecuzione del  terzo passo (recupero delle circolari). Prova quindi a saltare il passo inserendo direttamente l'indirizzo:
 **http://nome_sito/public/sistema/nuovo/3**

**Comment by scuolagioco** [comment]
> Ho bisogno del log degli errori per capire cosa è successo.
> Se non ho capito male, l'errore è durante l'esecuzione del terzo passo (recupero delle circolari). Prova quindi a saltare il passo inserendo direttamente l'indirizzo:
> **http://nome_sito/public/sistema/nuovo/3**

No, l'errore è durante l'esecuzione del quarto passaggio (passaggio di classe degli alunni promossi). Ho provato a fare come da lei detto, sostituendo però nel link il 3 con il 4, inizialmente pensavo di esserci riuscito solo che poi dopo che lo svuotamento delle cache è stato effettuato non è cambiato niente.. mi può aiutare?

**Comment by trinko** [comment]
Ho bisogno del log degli errori per cercare di capire cosa può essere successo.

**Comment by scuolagioco** [comment]
> 

come faccio ad inviarli😅 scusi ma sono un po’ imbranato nel settore

**Comment by scuolagioco** [comment]
[2022-08-31_01-26.log](https://github.com/iisgiua/giuaschool/files/9457176/2022-08-31_01-26.log)

dovrebbe essere questo, mi faccia sapere.

**Comment by trinko** [comment]
Allora segui la procedura:

- scarica e decomprimi il seguente file:
[SistemaController.php.zip](https://github.com/iisgiua/giuaschool/files/9459221/SistemaController.php.zip)

- carica il file nel server, nella cartella **src/Controller**, andando a sostituire quello esistente

-  come amministratore, svuota la cache dalla pagina **SISTEMA > MANUTENZIONE > SVUOTA CACHE**

- a questo punto riesegui solo il passo che ha dato errore utilizzando l'indirizzo: **http://nome_sito/public/sistema/nuovo/3** (NON ripartire dall'inizio)

Dovrebbe completare la procedura senza errori.
