### ISSUE TITLE
Problema accesso con google 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#340]
Buongiorno,allora credo (non sono sicuro) di esser riuscito a configurare l'accesso con google ,ma quando appunto vado per accedere come docente/alunno con le credenziali google mi dà l'errore 500.Potrebbe aiutarmi ?

**Comment by trinko** [comment]
La configurazione non è molto semplice...

Dal registro vanno configurati i parametri (**SISTEMA > PARAMETRI**): 
- id_provider: con il valore predefinito "gsuite"
- id_provider_dominio: con il dominio utilizzato, es. nomescuola.edu.it
- id_provider_tipo: con i codici per gli utenti che dovranno usare l'autenticazione, ad. es. "ADSP" indica gli alunni, i docenti, lo staff e il preside.

Poi va fatta la configurazione sulla console di amministrazione  del tuo Google Workspace (segui le loro guide).

Poi vanno inseriti i codici generati da Google nel file **.env**
```
OAUTH_GOOGLE_CLIENT_ID=...
OAUTH_GOOGLE_CLIENT_SECRET=...
OAUTH_GOOGLE_CLIENT_HD=...
```

**Comment by sempliciniluigi89** [comment]
Lo so ,ma da solo non ci riesco ,è già tanto che io sia riuscito a creare le credenziali oauth google,se qualcuno fosse disposto ad aiutarmi ,sono disponibile all'indirizzo mail : sempliciniluigi89@gmail.com

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
