### ISSUE TITLE
Errore Generico Scrutini

### ISSUE THREAD

**Issue by ISConvertini2022** [iisgiua/giuaschool#341]
**Descrivi il problema**
Salve, riscontriamo un errore generico che riguarda gli Scrutini.
Cambiando alcune configurazioni essi sono tornati a funzionare, di conseguenza, quali sono i passi da seguire per configurare correttamente lo scrutinio lato Amministratore?
Come fare per configurare uno scrutinio (completo di ripresa per le sospensioni del giudizio) di prova, per verificare che tutto funzioni correttamente - e non trovarsi nei guai a Gennaio prossimo?
Grazie 
![Errore Scrutinio](https://user-images.githubusercontent.com/111999667/188484189-9c804a81-0cf0-47e3-aa8a-a88ce1f9cb91.png)

**Indica come riprodurre l'errore**

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
La gestione degli scrutini richiede che siano correttamente configurate:
- la classe, con almeno 1 alunno
- le materie speciali (ed.civica, condotta, religione, sostegno, supplenza), più le altre che si intendono utilizzare.
- le cattedre relative alla classe, con almeno una cattedra di Ed.civica

Per attivare uno scrutinio, si va nella pagina **SISTEMA > SCUOLA > SCRUTINIO** e si indica la data iniziale per l'inserimento delle proposte di voto e degli scrutini (possono coincidere).

Ogni periodo dello scrutinio, quando viene attivato, deve avere una data di inizio proposte/scrutinio che sia successiva a quella del periodo precedente.

**Comment by trinko** [comment]
Se si visualizza un errore del tipo indicato (errore 500 o simile), è importante recuperare il log degli errori, per capire cosa è successo nel sistema. Seguire la procedura:

1. attiva la modalità debug dalla pagina **SISTEMA > MANUTENZIONE > ATTIVA DEBUG**
2. ripeti l'esecuzione della pagina che ha dato errore
3. estrai il log dalla pagina **SISTEMA > MANUTENZIONE > LOG ERRORI**, indicando data e ora in cui hai effettuato il passo precedente (meglio inserire qualche minuto prima)
4. Il file che verrà scaricato lo puoi allegare direttamente nel messaggio di risposta.

**Comment by ISConvertini2022** [comment]
[2022-09-05_18-30.log](https://github.com/iisgiua/giuaschool/files/9491445/2022-09-05_18-30.log)
File di Debug

**Comment by trinko** [comment]
Ho risposto  [qui](https://github.com/iisgiua/giuaschool/issues/342)
