### ISSUE TITLE
Errore Scrutini > Passo 2 - 'Voto Educazione Civica

### ISSUE THREAD

**Issue by ISConvertini2022** [iisgiua/giuaschool#342]
**Descrivi il problema**
Nel momento in cui, aperto lo scrutinio, ci si accinge ad inserire nel Tabellone il voto definitivo di Educazione Civica, il Sistema si comporta così:
- Visualizza la presenza di Media - che viene dalle Proposte di Voto dei Docenti Coordinatori (che riescono ad inserirle senza problemi).
- Nel momento in cui si fa click sul bottone blu '+Aggiungi' (per aggiungere la valutazione finale, da riportare in Tabellone), il Sistema va in completo blocco - non carica quando si premono i bottoni per aggiungere il voto/per visualizzare i singoli voti caricati eventualmente dai docenti.
- Quando si clicca su passo successivo, il Sistema riferisce che non sono stati inseriti i voti per Ed. Civica
SEGNALO CHE QUESTO ERRORE IMPEDISCE DI CONTINUARE LO SCRUTINIO

La Materia Educazione Civica è così configurata:
![Config_Materia_ED](https://user-images.githubusercontent.com/111999667/188485483-2293b6f8-8ce9-4760-9bef-6506b9c87286.png)

Il Tabellone, una volta entrati nello Step 2, permette di caricare i voti di Ed. Civica, ma di fatto questo non è possibile e si rimane sempre bloccati al passo 2 (Educazione Civica)
![Tabellone](https://user-images.githubusercontent.com/111999667/188485628-bc0311bf-dc64-4c71-b0fb-0b95b4ad94e0.png)

P.S. l'errore è stato riscontrato nel test degli Scrutini del 1° Periodo, ma crediamo si verifichi in generale anche negli altri Scrutini Online. La Cattedrà di Ed. Civica è impostata solo su un docente (che è anche il Coordinatore.

Nel complesso il progetto è più che soddisfacente.

Grazie

**Comment by trinko** [comment]
Come dicevo, controlla che esista almeno una cattedra di ed.civia per la classe

**Comment by ISConvertini2022** [comment]
La cattedra, come specificato, esiste.

**Comment by ISConvertini2022** [comment]
[2022-09-05_18-30.log](https://github.com/iisgiua/giuaschool/files/9491434/2022-09-05_18-30.log)
Ecco il file dei Log, spero riesca a capire il problema, assodato che dipenda dalla configurazione.

**Comment by ISConvertini2022** [comment]
UPDATE: Ora gli Scrutini funzionano:
                                                                  PRIMO PERIODO
Il problema di Educazione Civica si presenta SOLO nel 1° Periodo e si replica la stessa situazione anche per il Comportamento. Abbiamo risolto gestendo le fasi dello Scrutinio direttamente dalla tabella del Database (unico modo per scavallare gli errori). I voti in pagella relativi al comportamento e ad educazione civica, in questo caso non vengono inseriti, nè salvati.
                                                                   SCRUTINIO FINALE
 In fase di Scrutinio Finale, invece, andando semplicemente ad aprire lo scrutinio (senza prima inserire le proposte) il Sistema permette di inserire tutto e di completare la procedura senza errori.

**Comment by manuelbarberi** [comment]
Molto spesso, se si verificano errori del genere, si può provare a chiudere e riaprire lo scrutinio... io onestamente non ho fatto prove poichè qualsiasi problema torno alla versione precedente... quella 1.4.2 che, a me, funzionava perfettamente....

**Comment by trinko** [comment]
L'errore evidenzia dei dati incongruenti nel database. Bisogna capire se è la procedura che sbaglia o se è dovuto a qualche tentativo fatto con una configurazione non corretta che ha causato tutto.

Pertanto sarebbe oppurtuno riprovare ad eseguire lo scrutinio del primo periodo su una nuova classe, per vedere se genera lo stesso errore. 

Per riattivare lo scrutinio del primo periodo, dalla pagina **SCUOLA > SCRUTINI**, modifica le date dei vari periodi: data odierna per il primo periodo, date precedenti per gli altri.

**Comment by ISConvertini2022** [comment]
Grazie.

**Comment by ISConvertini2022** [comment]
Il problema persiste, anche creando un' altra classe, per il primo periodo, lo scrutinio non va avanti a causa dell'educazione civica

**Comment by trinko** [comment]
Ho trovato il problema: non sono state riportate nello scrutinio  del primo periodo le modifiche inserite negli scrutini finali e successivi.

La procedura sarà corretta per il rilascio della prossima versione.

**Comment by trinko** [comment]
Sistemato nella 1.5.1
