### ISSUE TITLE
Error 500 inserimento avviso uscita anticipata

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#378]
Quando si prova ad inserire un avviso per un'uscita anticipata/ingresso posticipato compare l'errore 500.
[app_prod-2022-09-30.log](https://github.com/iisgiua/giuaschool/files/9686127/app_prod-2022-09-30.log)

**Comment by trinko** [comment]
Probabilmente non è definito un orario e la relativa scansione oraria per la data.
Controlla le impostazioni da **SCUOLA > ORARIO**.

**Comment by rodolfo024** [comment]
La scansione oraria c’era, solo che era rimasta scoperta la domenica. Adesso va. Grazie!
