### ISSUE TITLE
PROBLEMA CON AGGIORNAMENTO VERSIONE 1.5.0

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#379]
Buonasera, ho provato ad aggiornare il registro elettronico all'ultima versione, ma quando raggiungo la pagina /public/install/index.php, ottengo questo errore:

Fatal error: Uncaught LogicException: Please run "composer require symfony/dotenv" to load the ".env" files configuring the application. in /membri/registroliceolc/config/bootstrap.php:8 Stack trace: #0 /membri/registroliceolc/public/index.php(7): require() #1 {main} thrown in /membri/registroliceolc/config/bootstrap.php on line 8

Come posso fare?
La ringrazio in anticipo.

**Comment by trinko** [comment]
Il messaggio di errore indica che mancano dei file nella cartella **vendor**. Controlla di  aver caricato tutti i file di tutte le cartelle (anche la cartella **config** è fondamentale).

Controlla anche che l'hosting sia impostato per usare il PHP versione 7.4 o successiva.

**Comment by Lucaccc** [comment]
Buongiorno.
Sto provando a caricare i file della cartella vendor, ma vedo che alcuni trasferimenti mi dice che non possono essere completati...non so a cosa sia dovuto questo problema...i file li sto trasferendo via ftp con filezilla..

**Comment by Lucaccc** [comment]
> Il messaggio di errore indica che mancano dei file nella cartella **vendor**. Controlla di aver caricato tutti i file di tutte le cartelle (anche la cartella **config** è fondamentale).
> 
> Non cancellare nessun file di quelli caricati.
> 
> Controlla anche che l'hosting sia impostato per usare il PHP versione 7.4 o successiva.

Ho fatto la procedura e ora non mi trova più la pagina di installazione...mi dice che la pagina non esiste...

**Comment by trinko** [comment]
>   Ho fatto la procedura e ora non mi trova più la pagina di installazione...mi dice che la pagina non esiste...

Si, questo è normale. Se hai completato l'aggiornamento, al termine della procedura la pagina public/install/index.php viene rinominata in public/install/index.txt, per ragioni di sicurezza.

Se per qualche motivo devi riutilizzare la procedura, come nel tuo caso, devi prima rinominarla nuovamente in index.php.
