### ISSUE TITLE
Errore Quando Si accede con admin

### ISSUE THREAD

**Issue by manuelbarberi** [iisgiua/giuaschool#381]
Quando accedo con l'utente admin, mi porta errore 500... appena inserisco la password corretta e clicco accedi porta errore... Cosa posso fare?

**Comment by trinko** [comment]
Mi spiace ma solo con queste informazioni non posso dirti niente.
Cerca di capire cosa hai fatto prima che si verificasse questa situazione: nuova installazione? Modificato qualche parametro? Cancellato qualche file? Modificata qualche impostazione del servizio di hosting? 

Cerca anche nel log per vedere se c'è qualche informazione utile.

**Comment by manuelbarberi** [comment]
Ho trovato l'errore... In pratica non avevo inserito i file di aggiornamento nuovo ma ho solo eseguito la procedura di aggiornamento... Tutto funzionante tranne che per le richieste... C'è un'altra segnalazione al riguardo. #392
