### ISSUE TITLE
Problema configurazione COLLOQUI

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#390]
Buonasera, volevo segnalare una problematica relativa ai colloqui.
Nonostante dal lato amministratore sia stato impostato il colloquio nella sede principale dell'istituto, in fase di prenotazione da parte dei genitori e dal lato docente, come sede appare "A DISTANZA".
A cosa è dovuto?
Grazie.

**Comment by trinko** [comment]
La gestione dei colloqui era stata modificata velocemente per farli solo online negli anni scorsi.
Attualmente è in fase di modifica per consentire correttamente entrambe le possibilità (online e in presenza).

**Comment by Lucaccc** [comment]
> La gestione dei colloqui era stata modificata velocemente per farli solo online negli anni scorsi. Attualmente è in fase di modifica per consentire correttamente entrambe le possibilità (online e in presenza).

Perfetto.
Grazie mille.

**Comment by trinko** [comment]
Sistemato nella 1.5.1
