### ISSUE TITLE
Problema gestione tipologie richieste.

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#392]
Buongiorno, ho aggiornato il registro, ma c'è un problema: nella creazione dei moduli di richiesta, alla voce ""Nome del file del modello", appare un menu a tendina, ma questo è vuoto: non mi appare nessuna voce da selezionare...come posso fare?

**Comment by trinko** [comment]
I template delle richieste devono essere caricati manualmente nella cartella **templates/PERSONALI/moduli** e hanno un formato particolare.
Quando si rilascerà la nuova versione inserirò un esempio.

**Comment by gmontalbano5ct** [comment]
scusi quando farà l'esempio?

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Non ho una data precisa, ma penso di riuscire a fare il rilascio entro la fine di ottobre.

**Comment by trinko** [comment]
Versione 1.5.1 rilasciata
