### ISSUE TITLE
Conteggio assenze sbagliato

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#402]
Buongiorno ,ci siamo accorti di alcune anomalie .Praticamente se un alunno si assenta ad esempio l'11 ottobre e poi il 17 ottobre ,il portale dei genitori/alunni riporta l'assenza di 7 giorni totali ,quando invece i giorni totali sono solo 2.Non capisco perché.Un altro problema è che se un alunno si assenta oggi è il genitore giustifica dal proprio portale ,una volta che il docente convalida ,l'assenza risulta giustificata ,ma se l'alunno si assenta il giorno dopo ,quando il genitore va a giustificare le compare il giorno che ha già giustificato da giustificare e più l'assenza nuova da giustificare.Mi sembra proprio anomala come cosa .Ecco perché io propongo di non fare il conteggio in base al mese ,ossia ottobre ,tipo di assenze 3 giorni  ,ma giornalmente es.1 ottobre = alunno assenza, 2 ottobre =alunno assente,3 ottobre = alunno assente ,senza accumulare il tipo di assenze per il tipo di mese

**Comment by trinko** [comment]
Premetto che i giorni di assenza non sono molto significativi, perché contano le ore per il limite massimo previsto del 25%.

I giorni di assenza consecutiva sono però rilevanti, visto che è prevista la presentazione obbligatoria del certificato medico quando si superano i 5 giorni consecutivi (la disposizione non è valida in tutte le regioni, perché la sanità è gestita su base regionale).

Di conseguenza è necessario contare i giorni consecutivi di assenza, e allora la logica per il conteggio è la seguente: vengono considerati assenti anche i giorni festivi compresi tra le due assenze. Ad es. l'alunno si assenta il sabato e il lunedì e sono contati 3 giorni (conteggiando anche la domenica).
Sono considerati alla pari di un giorno festivi i giorni in cui non risulta nessuna firma sulle lezioni: questo perché significa che non è stato fatto l'appello (visto che nessun docente risulta aver fatto lezione). Poiché la normativa è un dispositivo sanitario che non si può prendere alla leggera, si presume che l'alunno abbia prolungato l'assenza anche in quel giorno che viene quindi considerato nel conteggio dei giorni di assenza consecutivi.

Infine, sulla problematica della giustificazione, state sbagliando la modalità di apporre le giustificazioni: il genitore non deve giustificare giorno per giorno, ma solo il giorno in cui l'alunno rientra in classe. Se l'alunno è assente il primo ottobre, poi il 2 e poi il 3, non è che il genitore deve apporre 3 firme! Il genitore saprà quando l'alunno rientra in classe e giustificherà per quel giorno, solo una volta. Accumulare le assenze, semplifica sia l'apposizione della firma del genitore che la validazione del docente.

Infine, nelle ultime modifiche ho eliminato il **totale di giorni di assenza** che il genitore vedeva. Ora al genitore viene presentato solo il totale delle ore di assenza (numero di ore firmate dal docente dove l'alunno non risulta presente). Il conteggio dei giorni consecutivi di assenza rimane  segnalto solo per le giustificazioni, per il problema del certificato medico di cui si parlava.
