### ISSUE TITLE
AGGIORNAMENTO AUTOMATICO

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#408]
Salve, sto provando con l'aggiornamento automatico, ma mi da questo errore:
Errore nell'estrazione del file "vendor/italia/spid-php/vendor/simplesamlphp/simplesamlphp/locales/no/"
Come posso procedere?
Devo fare l'aggiornamento tramite il caricamento di filezilla come avveniva prima di questa versione? o c'è una soluzione?
Grazie.

**Comment by trinko** [comment]
C'è una soluzione: elimina sul server la cartella con quel nome e poi riprendi l'installazione.

**Comment by Lucaccc** [comment]
Ho fatto, è andato avanti ma ora mi da questo errore.
"Errore 403
Non puoi accedere alla pagina o directory desiderata.
Ecco le possibili ragioni:

La directory non contiene un file indice, comunemente index.html
Non sei connesso con un numero IP valido (IP: 82.60.39.36), se stai usando un proxy puoi provare a disabilitarlo e riconnetterti.
Il traffico verso quest'area del sito è bloccato, oppure non hai l'autorizzazione per accedere alla risorsa che hai richiesto"

**Comment by trinko** [comment]
Per andare avanti devi utilizzare il link seguente:
**http://nome_sito/install/update.php?token=XXX&step=1** o 
**http://nome_sito/public/install/update.php?token=XXX&step=1**

Devi sostituire XXX con il valore del token che puoi leggere dal file **.gs-updating**, presente nella cartella principale.
