### ISSUE TITLE
Password admin nel momento dell'installazione

### ISSUE THREAD

**Issue by manuelbarberi** [iisgiua/giuaschool#411]
Impossibile eseguire i comandi per cifrare la password.

In EnvVarProcessor.php line 172: Environment variable not found: "APP_SECRET".

**Comment by trinko** [comment]
Devi dare più informazioni... Che installazione stai facendo? L'aggiornamento automatico, quello tradizionale, una nuova installzione? In che passo trovi l'errore?

**Comment by manuelbarberi** [comment]
Nuova installazione

Il giorno lun 31 ott 2022 alle 15:38 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Estrai il file allegato e sostituisci quello esistente nella cartella **src/Install**. Quindi rilancia la procedura.
Dovrebbe risolvere.

[Installer.php.zip](https://github.com/iisgiua/giuaschool/files/9904120/Installer.php.zip)
