### ISSUE TITLE
Scarica il file invece di eseguirlo

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#412]
Dopo aver scompattando il file "release" nella cartella public_html quando mi collego all'indirizzo /install/index.php mi scarica il file invece di eseguirlo. Stessa cosa se mi collego soltanto a /public.
Succede lo stesso anche se svoto la cartella public_html e la ripopolo.

**Comment by trinko** [comment]
Quale è il tuo hosting? 
Se non sei su Altervista il problema è probabilmente dovuto ad una impostazione specifica per quell'hosting. In tal caso, modifica il file **.htaccess** che trovi nella cartella principale ed elimina le righe seguenti:
```
# attiva PHP 8.0 su Altervista
AddHandler av-php8 .php
```
Poi controlla anche le impostazioni del tuo hosting per assicurarti che stia usando il PHP 7.4 o successivo.

**Comment by rodolfo024** [comment]
No non è altervista. Controllerò. Però prima funzionava…

**Comment by sempliciniluigi89** [comment]
@trinko  L'hosting è x10hosting , servirebbe che si risolvesse al più presto ,se è possibile

**Comment by trinko** [comment]
Ho già scritto quella che ritengo sia la soluzione: 
[vedi](https://github.com/iisgiua/giuaschool/issues/412#issuecomment-1301055249)

**Comment by trinko** [comment]
Più semplicemente sovrascrivi il file .htaccess con questo allegato:
[fix.zip](https://github.com/iisgiua/giuaschool/files/9930280/fix.zip)

**Comment by rodolfo024** [comment]
Il problema dello scaricare i file non succede più, d'altro canto quando provo a effettuare l'aggiornamento del db compare questo errore:
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'gs_definizione_richiesta' already exists

**Comment by trinko** [comment]
Dall'errore riportato mi sembra che tu non stia usando il metodo di aggiornamento automatico indicato 
[in questo annuncio](https://github.com/iisgiua/giuaschool/discussions/407)

Se è così, poi ti spiego come saltare i passaggi già effettuati.

**Comment by rodolfo024** [comment]
Ho scompattato il file update e messo il sito in manutenzione, però quando vado su /TEMP clicco su "continua" ma l'operazione va in time-out.
[app_prod-2022-11-04.log](https://github.com/iisgiua/giuaschool/files/9939472/app_prod-2022-11-04.log)

**Comment by trinko** [comment]
Aspetta: tu avevi già scompattato i file della nuova versione. 
Quindi devi saltare il passo iniziale. Per andare avanti devi utilizzare il link seguente:
**http://nome_sito/public/install/update.php?token=XXX&step=2**

Devi sostituire XXX con il valore del token che puoi leggere dal file **.gs-updating**, presente nella cartella principale.

**Comment by rodolfo024** [comment]
[app_prod-2022-11-04 (1).log](https://github.com/iisgiua/giuaschool/files/9940370/app_prod-2022-11-04.1.log)
Mi sa che nel frattempo ho fatto un po' di casini... XD

**Comment by trinko** [comment]
Prova lo stesso, se non hai cancellato file dovrebbe funzionare comunque.

**Comment by rodolfo024** [comment]
Non c'ho più .gs-updating

**Comment by rodolfo024** [comment]
Tra l'altro adesso mi compare l'errore 500...

**Comment by trinko** [comment]
Gli errori sono normali, perché, se ho capito bene quanto è successo, tu adesso hai il codice aggiornato alla versione 1.5.1 ma il database è ancora alla versione precedente. Questo crea problemi per qualsiasi pagina del registro. Ma l'aggiornamento dovrebbe funzionare lo stesso.

Il file **.gs-updating** lo puoi ricreare, inserendolo nella cartella principale, perchè contiene solo queste due righe:
```
version=1.5.1
token=XXX
```
Sostituisci XX con un numero qualsiasi, che userai anche nell'indirizzo che ho indicato in precedenza

**Comment by rodolfo024** [comment]
Adesso compare questo
[DELETE FROM gs_colloquio; ALTER TABLE gs_colloquio DROP FOREIGN KEY FK_A42C6DE08EEAC9E6; DROP INDEX IDX_A42C6DE08EEAC9E6 ON gs_colloquio;]

**Comment by trinko** [comment]
Prova a sostituire, nel file **src/install/update-v1.5.1**, la riga seguente:
```
 "DELETE FROM gs_colloquio; ALTER TABLE gs_colloquio DROP FOREIGN KEY FK_A42C6DE08EEAC9E6; DROP INDEX IDX_A42C6DE08EEAC9E6 ON gs_colloquio;",

``` 
con
```
 "DELETE FROM gs_colloquio;",
``` 
Poi continua col passo 3.

**Comment by rodolfo024** [comment]
Ok. Io adesso ho tre indici nella tabella colloqui.

**Comment by trinko** [comment]
Dovrebbe esserci solo la chiave primaria e l'indice sulla colonna docente_id. Se puoi, cancella a mano gli altri

**Comment by rodolfo024** [comment]
Su docente_id ho questo
IDX_A42C6DE094E27525

**Comment by trinko** [comment]
Si, quello è ok

**Comment by rodolfo024** [comment]
Quella su orario_id non me la fa cancellare per un vincolo di chiave esterna

**Comment by trinko** [comment]
Ok, prova ad inserire questi comandi SQL (nella finestra SQL di MyPhpAdmin):
```
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE gs_colloquio DROP FOREIGN KEY FK_A42C6DE08EEAC9E6; 
DROP INDEX IDX_A42C6DE08EEAC9E6 ON gs_colloquio;
SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by rodolfo024** [comment]
#1091 - Impossibile cancellare (DROP FOREIGN KEY) `FK_A42C6DE08EEAC9E6`. Controllare che il campo chiave esista.

**Comment by trinko** [comment]
Forse era già cancellata, prova a cancellare solo l'indice:
Ok, prova ad inserire questi comandi SQL (nella finestra SQL di MyPhpAdmin):
```
SET FOREIGN_KEY_CHECKS = 0;
DROP INDEX IDX_A42C6DE08EEAC9E6 ON gs_colloquio;
SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by rodolfo024** [comment]
Niente lo stesso... però mi sembra che comunque funzioni.
