### ISSUE TITLE
Problema con il file  messages+intl-icu.it.yml

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#414]
Buonasera,
raggiungendo il file messages+intl-icu.it.yml (da altervista), questo appare vuoto...non c'è nessuna scritta all'interno, nonostante sul registro tutti i messaggi appaiono correttamente.
Mi serve accedervi per modificare i messaggi relativi ai giudizi di condotta.

**Comment by trinko** [comment]
Ho notato che Altervista è "allergico" ad alcuni nomi di file non standard. Ad es. non visualizza i file che cominciano con il punto, anche se sono regolarmente presenti.
Suppongo che sia lo stesso per questo file. Prova quindi a scaricare il file sul tuo computer con FileZilla, poi vai ad aprire la copia che hai scaricato. Se è come penso troverai il contenuto completo.

**Comment by Lucaccc** [comment]
> Ho notato che Altervista è "allergico" ad alcuni nomi di file non standard. Ad es. non visualizza i file che cominciano con il punto, anche se sono regolarmente presenti. Suppongo che sia lo stesso per questo file. Prova quindi a scaricare il file sul tuo computer con FileZilla, poi vai ad aprire la copia che hai scaricato. Se è come penso troverai il contenuto completo.

Ho fatto come ha detto lei, ma andando a ritrasferire il file corretto, ora non mi fa più inserire il voto di comportamento..

**Comment by trinko** [comment]
> Ho fatto come ha detto lei, ma andando a ritrasferire il file corretto, ora non mi fa più inserire il voto di comportamento..

Forse hai cancellato qualcosa di importante. Se è l'unica cosa che hai modificato, puoi sempre recuperare l'ultima versione del file dei messaggi e ripristinarlo, in modo da controllare se l'errore è risolto.

[messages+intl-icu.it.yml.zip](https://github.com/iisgiua/giuaschool/files/9953794/messages%2Bintl-icu.it.yml.zip)
