### ISSUE TITLE
Gestione BES

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#419]
Buonasera,
ho effettuato da diverso tempo l'aggiornamento, ma nel farlo non mi è apparsa la modifica per la gestione dei documenti BES e dei relativi responsabili.
Come posso fare, senza eseguire di nuovo l'aggiornamento?
Grazie.

**Comment by trinko** [comment]
Se hai aggiornato alla 1.5.1, dovresti vedere, da amministratore, il menu **DOCENTI > RESPONSABILI BES**. 
Se non lo vedi, puoi provare a svuotare la cache.

In alternativa, si può inserire direttamente sul database con il comando SQL seguente:

```
INSERT INTO gs_menu_opzione (menu_id,sotto_menu_id, creato, modificato, ruolo, funzione, nome, descrizione, url, ordinamento, abilitato, icona) VALUES 
( (SELECT id FROM gs_menu where selettore='docenti')  , NULL,NOW(),NOW(),'M','','Responsabili&nbsp;BES','Configura i responsabili BES','docenti_responsabiliBes',7,1,'');

```

**Comment by Lucaccc** [comment]
L'ho fatto, e ora mi dice ERROR 500...
Come procedo?

**Comment by Lucaccc** [comment]
Ho risolto.
Grazie.
