### ISSUE TITLE
Gestione testo email

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#422]
Buongiorno, volevo sapere se fosse possibile modificare le intestazioni delle email e il testo visualizzato all'intero di esse.
Grazie.

**Comment by trinko** [comment]
Il contenuto delle  email lo trovi nei template, nella cartella **templates/email**.

L'oggetto riportato nelle email è fisso, cambia il nome della scuola che è preso dal nome breve dell'istituto, modificabile dalla pagina  **SCUOLA > ISTITUTO**.

**Comment by Lucaccc** [comment]
> Il contenuto delle email lo trovi nei template, nella cartella **templates/email**.
> 
> L'oggetto riportato nelle email è fisso, cambia il nome della scuola che è preso dal nome breve dell'istituto, modificabile dalla pagina **SCUOLA > ISTITUTO**.

Perfetto, grazie.
Un'ultima cosa: per quanto riguarda l'invio delle notifiche per le circolari, c'è qualcosa che bisogna fare?
Perché il registro invia correttamente le email per le password, ma le notifiche per le circolari no..

**Comment by Forrest-It** [comment]
Salve, avendo a disposizione una macchina virtuale, che comando occorre inserire nel cron per inviare le notifiche di nuove circolari via email ? 

Grazie

**Comment by trinko** [comment]
I comandi sono 2, io li imposto per l'esecuzione di 1 volta all'ora, ma sfasati di mezzora l'uno dall'altro:

1. prepara le notifiche
`php bin/console app:notifica:prepara`

2. invia le email di notifica
`php bin/console app:notifica:invia`

**Comment by Forrest-It** [comment]
Grazie mille
