### ISSUE TITLE
Errore 500 pdf riepilogo voti scrutinio 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#426]
Buonasera,quando il dirigente o il coordinatore cerca di stampare in fase di scrutinio il documento pdf riepilogo voti esce l'errore 500

**Comment by trinko** [comment]
Ho bisogno di più informazioni: attiva il debug, riesegui la procedura che riporta l'errore e poi estrai il log e caricalo qui.

**Comment by sempliciniluigi89** [comment]
[2022-11-20_16-17 (1).log](https://github.com/iisgiua/giuaschool/files/10050015/2022-11-20_16-17.1.log)

**Comment by trinko** [comment]
Il log non riporta informazioni sull'errore. 
Immagino però che si tratti del primo quadrimestre/trimeste. Appena posso, deve rivedere un po' le procedure.

**Comment by sempliciniluigi89** [comment]
se lo riesce a risolvere prima degli scrutini del primo trimestre ,sarebbe grandioso

**Comment by trinko** [comment]
Il problema ora è risolto installando l'ultimo aggiornamento:
[utimo aggiornamento](https://iisgiua.github.io/giuaschool-docs/latest-build.html)
