### ISSUE TITLE
ERRORE DURANTE SIMULAZIONE SCRUTINIO FINALE CLASSE SECONDA 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#441]
Buongiorno, durante la simulazione dello scrutinio di una classe seconda ,mi si presenta l'errore 500 che vi allego qui sotto:
[2022-12-08_14-45.log](https://github.com/iisgiua/giuaschool/files/10185914/2022-12-08_14-45.log)

**Comment by trinko** [comment]
Il log riporta solo informazioni successive alla pagina di errore.
Dovresti estrarre il logo di circa 5 minuti prima delle 14:45

**Comment by trinko** [comment]
Il problema dovrebbe essere risolto utilizzando il file allegato:
- scarica il file e decomprimilo
- carica il file ottenuto sul server, nella cartella **src/Util**, sovrascrivendo il file esistente
- resetta la cache 

[ScrutinioUtil.php.zip](https://github.com/iisgiua/giuaschool/files/10196856/ScrutinioUtil.php.zip)

**Comment by sempliciniluigi89** [comment]
Fatto , ma la problematica rimane invariata

**Comment by trinko** [comment]
Non riesco a riprodurre l'errore. 

Ti chiedo di controllare le seguenti cose:
- lo scrutinio del primo periodo è stato svolto per la classe che genera l'errore? Per il calcolo del limite di assenze la procedura va infatti  a cercare gli scrutini precedenti
- ha impostato per qualche alunno della classe l'impostazione per l'anno all'estero?
- il tuo hosting ha impostato la versione del PHP 8?

**Comment by sempliciniluigi89** [comment]
Risolto,non avevo tenuto conto dello scrutinio del primo periodo



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/11/22,
12:27:47 PM

Il giorno dom 11 dic 2022 alle ore 11:55 Antonello Dessì <
***@***.***> ha scritto:
