### ISSUE TITLE
TESTATA SCOLASTICA NON APPARE NEI DOCUMENTI 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#445]
Buongiorno ,stiamo riscontrando un problema con la testata della scuola ,praticamente il registro ufficiale della scuola è installato su Altervista ,ma questo ,nonostante abbiamo caricato rispettando sia il formato che le dimensioni 1000x216 la testata ,questa non appare in nessun documento ,nonostante abbiamo provato a svuotare la cache  .Allora ho mandato diverse mail a giuaschoolregistro@gmail.com , ma ancora non ho avuto risposta

**Comment by trinko** [comment]
Il problema è stato segnalato più volte, ma solo ora sono riuscito a riprodurlo sul mio sistema: penso di risolverlo nei prossimi giorni.

**Comment by sempliciniluigi89** [comment]
Sarebbe abbastanza urgente



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/13/22,
12:23:38 PM

Il giorno mar 13 dic 2022 alle ore 10:58 Antonello Dessì <
***@***.***> ha scritto:

**Comment by Lucaccc** [comment]
> Il problema è stato segnalato più volte, ma solo ora sono riuscito a riprodurlo sul mio sistema: penso di risolverlo nei prossimi giorni.

Mi ha aiutato un altro utilizzatore del registro, o meglio ha capito lui il problema: va inserita l'intera path dell'immagine.

**Comment by sempliciniluigi89** [comment]
in che senso?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/13/22,
09:49:07 PM

Il giorno mar 13 dic 2022 alle ore 20:51 Lucaccc ***@***.***>
ha scritto:

**Comment by trinko** [comment]
Penso di aver risolto il problema in modo definitivo (il suggerimento sul path dell'immagine purtroppo non funziona su tutti i sistemi).

Per risolvere: carica sul server i file allegati e svuota la cache. 

[giuaschool.zip](https://github.com/iisgiua/giuaschool/files/10222568/giuaschool.zip)

**Comment by sempliciniluigi89** [comment]
Me lo potrebbe fare lei per cortesia? Ho paura di fare danni, se vuole le
fornisco le credenziali di Altervista in privato

Il Mar 13 Dic 2022, 23:21 Antonello Dessì ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
Allora ho fatto come da lei indicato e adesso si presenta un problemone
,non appena clicco su scarica la password di un docente,genitore,alunno per
vedere se appare  la  testata ,mi esce errore 500  allego




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/14/22,
12:04:37 AM

Il giorno mar 13 dic 2022 alle ore 23:27 Luigi Semplicini <
***@***.***> ha scritto:

**Comment by sempliciniluigi89** [comment]
Se qualcuno mi rispondesse ,sarei grato ,dal momento che la scuola non può rimanere tanto tempo senza registro

**Comment by trinko** [comment]
Mi serve il log degli errori per capire il problema.

**Comment by sempliciniluigi89** [comment]
[2022-12-14_16-20.log](https://github.com/iisgiua/giuaschool/files/10229088/2022-12-14_16-20.log)

**Comment by sempliciniluigi89** [comment]
Potrebbe provvedere lei?io ormai mi sto quasi rassegnando

**Comment by trinko** [comment]
Ho trovato l'errore: hai sbagliato il nome dell'immagine, hai usato alla fine **jpeg** al posto di **jpg**

Se modifichi il nome dell'immagine hai risolto.

**Comment by sempliciniluigi89** [comment]
Risolto ,ora funziona ,grazie
