### ISSUE TITLE
Problema importazione alunni

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#447]
Buonasera ,sto importando l'elenco degli alunni ,  nonostante io non abbia abbinato a loro un indirizzo mail ,nel confermare l'importazione mi appare il seguente messaggio che poi impedisce l'importazione degli stessi 

: ERRORE # 1: email (alunno): Il valore inserito non è un indirizzo email valido.

**Comment by trinko** [comment]
Devi configurare il dominio email predefinito.
Vai alla pagina SISTEMA > PARAMETRI e imposta il parametro **dominio_default**: puoi inserire il dominio della tua scuola o uno fittizio (es. **noemail.local**)

In questo modo le email saranno generate come _nome_utente@dominio_

**Comment by sempliciniluigi89** [comment]
Ho fatto come da voi detto,ovvero nel parametro ho impostato come dominio
noemail.local ,ma non appeno effettuo l'importazione mi riporta lo stesso
messaggio di errore tra l'altro con il primo alunno senza il dominio
,ovvero:

ERRORE # 1: email (alunno): Il valore inserito non è un indirizzo email
valido. [maria.defilippi.s1@]


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/15/22,
03:34:09 PM

Il giorno gio 15 dic 2022 alle ore 00:07 Antonello Dessì <
***@***.***> ha scritto:

**Comment by sempliciniluigi89** [comment]
Mi potrebbe cortesemente rispondere  qualcuno ?Grazie

**Comment by trinko** [comment]
Controlla se nei parametri hai impostato qualcosa per **id_provider**: in tal caso cancella e lascialo vuoto. 

Esegui il logout e poi riconnetiti prima di effettuare nuovamente l'importazione.

**Comment by sempliciniluigi89** [comment]
No, per quanto riguarda id_provider non è presente niente ,non capisco allora dove sia il problema .In questo modo se rende inutilizzabile in quanto se non carica gli alunni ,non ha alcuna funzione

**Comment by trinko** [comment]
L'unica situazione che permette di riprodurre quell'errore è proprio il caso in cui il parametro **id_provider** non è vuoto.
Se ti sei già assicurato che sia vuoto, devo supporre che ci sia qualcosa che non va nei dati memorizzati nel database.
Prova a forzare la pulizia del campo nel modo seguente:

1. inserisci **12345678901234567890**  nel parametro **id_provider** e memorizza i dati;
2. svuota il campo **id_provider** e memorizza nuovamente i dati;
3. esegui il logout dell'utente;
4. riesegui l'accesso come amministratore;
5. fai la prova di importazione

**Comment by sempliciniluigi89** [comment]
risolto.grazie
