### ISSUE TITLE
Problema Aggiornamento dell'applicazione

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#448]
Buonasera ,non appena mi reco nella sezione aggiornamento ,per vedere se ci sono aggiornamenti o meno ,appare il
 seguente messaggio: Impossibile recuperare le informazioni sull'esistenza di aggiornamenti.

**Comment by trinko** [comment]
Ritengo sia un problema temporaneo di rete.
Riprova in seguito e vedi se mostra ancora lo stesso messaggio.

**Comment by sempliciniluigi89** [comment]
Riprovato e il messaggio è sempre lo stesso

**Comment by sempliciniluigi89** [comment]
secondo me perché è ancora la versione 1.50 ,ma avendo Altervista non so proprio come si aggiorna alla versione 1.5.1

**Comment by trinko** [comment]
Se hai ancora la 1.5.0 la procedura di aggiornamento potrebbe non funzionare.
In tal caso va effettuato l'aggiornamento con la modalità tradizionale: caricare sul server tutti i file della nuova versione, quindi si va ad eseguire la pagina **nome_sito:/install/index.php**

Naturalmente bisogna mettere il registro in modalità manutenzione prima di effettuare l'aggiornamento.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
