### ISSUE TITLE
Problema importazione docenti csv

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#449]
ho appena scoperto che quando cerco di importare i docenti ,mi restituisce il seguente messaggio di errore :ERRORE I campi del file non corrispondono a quanto previsto nel record 1.

**Comment by trinko** [comment]
Confrinta i campi del tuo file con l'esempio seguente:
[IMPORTA_DOCENTI.csv](https://iisgiua.github.io/giuaschool-docs/assets/docs/IMPORTA_DOCENTI.csv)

**Comment by sempliciniluigi89** [comment]
Provando a caricare la sua per prova ron rileva nessun errore,ma non appena
carico il mio rileva l'errore.Adesso le allego qui sotto la mia in modo da
aiutarmi  e correggere eventuali errori per favore




Il giorno sab 17 dic 2022 alle ore 18:14 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Non hai allegato il file.

**Comment by sempliciniluigi89** [comment]
[unico file docenti.csv](https://github.com/iisgiua/giuaschool/files/10252818/unico.file.docenti.csv)

**Comment by sempliciniluigi89** [comment]
le ho allegato il file csv

**Comment by trinko** [comment]
Nei dati che hai inserito, hai saltato il campo del codice fiscale, per cui c'è un dato in meno in ogni riga.

Ho modificato il file, lasciando vuoto il codice fiscale (verrà inserito un numero univoco fittizio):
[unico.file.docenti.csv](https://github.com/iisgiua/giuaschool/files/10253687/unico.file.docenti.csv)
