### ISSUE TITLE
Errore importazione genitori

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#450]
Buonasera , non potendo importare normalmente i dati relativi ai nomi e cognomi dei genitori  degli alunni ,ho effettuato da phpmyadmin l'esportazione csv degli utenti di tipo genitori e laddove era scritto cognome/nome =#NESSUN DATO#
 ho inserito i nomi e cognomi giusti ma nel registro continua a risultare andando sui dettagli di un alunno sezione genitore al dato relativo sia al nome che al cognome ,appare ancore #NESSUN DATO#

**Comment by trinko** [comment]
Se ho capito bene, hai creato il file csv con i dati esportati dal database e poi modificati. 
Ma quando hai importato il file, ha dato qualche errore?
Inoltre, vuoi importare nello stesso database, modificando i dati esistenti o li stai importando in uno nuovo?

**Comment by sempliciniluigi89** [comment]
Nello stesso modificando sezione Genitore nome e cognome al posto di
#NESSUN DATO#

Il Sab 17 Dic 2022, 21:02 Antonello Dessì ***@***.***> ha
scritto:

**Comment by trinko** [comment]
Quello che è successo è che hai aggiunto nuovi utenti con i dati dei genitori corretti.

Per modificare i dati esistenti, devi inserire necessariamente il valore per le username dell'alunno e dei genitori, ovvero i campi:
- Username
- Genitore1Username
- Genitore2Username
Per gli altri campi, dovrai inserire un valore se li vuoi modificare, o lasciarli vuoti se non vuoi modficarli.

**Comment by trinko** [comment]
Non è una differenza dipendente dall'hosting, ma dal fatto che le procedure di importazione sono state modificate per vari motivi.
Adesso è necessario eseguirle in questo modo.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
