### ISSUE TITLE
Ultimo aggiornamento

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#451]
Ho eseguito l'aggiornamento del db con le ultime modifiche per la visualizzazione dei pdf. Tutto è andato bene in fase di aggiornamento però alla pagina di login compare l'errore 500.

[app_prod-2022-12-21.log](https://github.com/iisgiua/giuaschool/files/10279462/app_prod-2022-12-21.log)

**Comment by trinko** [comment]
La procedura di installazione che hai usato non è ancora completa.

Devi eseguire inoltre:

- se non esistono già, crea le directory:
  -  **PERSONAL/** 
  -  **PERSONAL/data/**
  -  **PERSONAL/data/moduli/**
  -  **PERSONAL/templates/**
  -  **PERSONAL/img/**
- poi sposta il contenuto della directory **templates/PERSONALI/moduli/** in  **PERSONAL/data/moduli/**

**Comment by rodolfo024** [comment]
Grazie!
