### ISSUE TITLE
Errore 500 richiesta uscita anticipata 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#452]
Buongiorno ,allego l'errore 500 che si presenta nel momento in cui i genitori ,nella sezione richieste cercano di inviare la richiesta dell'uscita anticipata 

[2022-12-24_13-56.log](https://github.com/iisgiua/giuaschool/files/10298606/2022-12-24_13-56.log)

**Comment by trinko** [comment]
Nel log inviato non ci sono indicazioni utili, forse non era attivato il debug quando è stato generato. 
Prova a generarlo di nuovo, dopo esserti assicurato di aer attivato la modalità debug.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
