### ISSUE TITLE
Inserimento Rappresentanti Consiglio d'Istituto

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#459]
Buongiorno, ho notato che nell'Inserimento dei Rappresentanti del Consiglio d'Istituto e/o di Classe, nell'elenco non compaiono gli alunni o i docenti che ho inserito dopo l'aggiornamento.
Mi fa inserire tutti gli altri, ma quelli inseriti dopo l'aggiornamento non mi appaiono proprio in elenco,
Grazie.

**Comment by trinko** [comment]
Non mi è chiaro, cosa intendi con "dopo l'aggiornamento"? 

Avevi già aggiornato il registro prima del rilascio della nuova versione? In questo caso, hai installato l'aggiornamento iniziale relativa a questa funzionalità, ma poi in quelli successivi ho dovuto cambiare il funzionamento della procedura per risolvere un problema che si è presentato. Tieni presente che il codice degli aggiornamenti è soggetto a variazioni, perché non è ancora stato validato definitivamente. 

Se è questo il caso, per risolvere è necessario azzerare tutti gli inserimenti. Lo puoi fare con il comando SQL seguente (da PHPMyAdmin):

```
UPDATE gs_utente SET rappresentante='';
```

**Comment by Lucaccc** [comment]
> Non mi è chiaro, cosa intendi con "dopo l'aggiornamento"?
> 
> Avevi già aggiornato il registro prima del rilascio della nuova versione? In questo caso, hai installato l'aggiornamento iniziale relativa a questa funzionalità, ma poi in quelli successivi ho dovuto cambiare il funzionamento della procedura per risolvere un problema che si è presentato. Tieni presente che il codice degli aggiornamenti è soggetto a variazioni, perché non è ancora stato validato definitivamente.
> 
> Se è questo il caso, per risolvere è necessario azzerare tutti gli inserimenti. Lo puoi fare con il comando SQL seguente (da PHPMyAdmin):
> 
> ```
> UPDATE gs_utente SET rappresentante='';
> ```

No, mi sono espresso male.
Non ho fatto gli aggiornamenti prima del tempo, ma solo dopo che è stato rilasciato.
DOPO aver fatto l'aggiornamento (direttamente dal registro), ho inserito dei nuovi utenti di Docenti e Studenti e questi non compaiono tra la lista di quelli selezionabili per ricoprire i ruoli del consiglio d'Istituto, mentre tutti coloro che erano presenti prima che facessi l'aggiornamento sono presenti nell'elenco a discesa.

**Comment by trinko** [comment]
Ora ho capito.
E' il comportamento voluto: se clicchi sul pulsante per aggiungere un **nuovo** rappresentante, dalla lista sono esclusi quelli che sono già inseriti come rappresentanti (di qualsiasi tipo).
Se invece vuoi **modificare** un rappresentante esistente (es. aggiungere "rappresentante di classe" ad un genitore che è già "rappresentante di Istituto"), allora usi il pulsante modifica.

**Comment by trinko** [comment]
Ho capito, controllo.

**Comment by Lucaccc** [comment]
Grazie mille.
