### ISSUE TITLE
Errore 500 Scuola > Classi

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#461]
Dopo aver effettuato l'aggiornamento a 1.5.2 si presentano questi errori:
[app_prod-2023-02-02.log](https://github.com/iisgiua/giuaschool/files/10571930/app_prod-2023-02-02.log)

**Comment by rodolfo024** [comment]
Anzi, non si accede a nessuna sezione del registro da lato docente
[app_prod-2023-02-02 (1).log](https://github.com/iisgiua/giuaschool/files/10571943/app_prod-2023-02-02.1.log)

**Comment by trinko** [comment]
Prova:

1. controlla che non sia stata cambiata la versione PHP in uso (>= 7.4)
2. rimuovi la cache a mano, cancellando il contenuto della cartella **var/cache/prod** e poi fai il logout e riconnetiti

Se il problema persiste, attiva il debug e poi estrai il log.

**Comment by rodolfo024** [comment]
Svuotando manualmente la cache l'errore non compare più, grazie!!
