### ISSUE TITLE
Installazione ultimi aggiornamenti

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#463]
Buon pomeriggio.
Ho provato a installare gli aggiornamenti rilasciati dopo la versione 1.5.2, caricando i file sul server e raggiungendo il link /install/index.php
Una volta completata la procedura, il registro si è resettato, come se fosse un nuovo registro, e tutti i dati non c'erano più.
Fortunatamente avevo il backup e ho risolto, ma come devo fare per installare gli ultimi aggiornamenti se non così?
Basta che carico le cartelle e svuoto la cache senza fare altro?
Grazie.

**Comment by trinko** [comment]
Sto cambiando la procedura per l'installazione degli ultimi aggiornamenti. Non l'ho ancora documentata perché non voglio che sia svolta in modo automatico: il codice delle modifiche infatti non è da considerarsi definitivo o validato.
Quindi è da utilizzare in ambienti di test o solo quando è proprio indispensabile utilizzare una nuova funzione contenuta solo in tali modifiche.

 La procedura attuale prevede:
1. scaricare il file ZIP dell'aggiornamento (es. **giuaschool-update-v1.5.2.zip**) direttamente nella cartella **src/install**; 
2. creare nella directory principale il file **.gs-updating** che contiene le seguenti 2 righe:
```
version=versione
token=codice
```
La _versione_ indica il numero di versione con il suffisso "-build", mentre il _codice_ è la password di installazione. Ad esempio:
```
version=1.5.2-build
token=PASS1234
```

3. A questo punto si va alla pagina: **http://NOME_SITO/install/update.php?token=TOKEN&step=1**
Dove TOKEN è il _codice_ definito in precedenza. Nell'esempio fornito, sarebbe:  **http://NOME_SITO/install/update.php?token=PASS1234&step=1**


Il resto è tutto gestito dalla procedura di aggiornamento.

**Comment by Lucaccc** [comment]
Va bene, grazie mille.

**Comment by Lucaccc** [comment]
Ho visto che è stata inserita la funzione della gestione fuori aula, il che mi è indispensabile.
Posso procedere con la procedura che mi ha detto lei sopra o è molto rischiosa?
Grazie.

**Comment by trinko** [comment]
Non è ancora completata, al momento non è ancora utilizzabile. 
Ho fatto solo la gestione lato coordinatore.

**Comment by Lucaccc** [comment]
> Non è ancora completata, al momento non è ancora utilizzabile. Ho fatto solo la gestione lato coordinatore.

Ok, mi consiglia di aspettare quindi? o procedo lo stesso gestendo solo da coordinatore?

**Comment by trinko** [comment]
Mi spiego meglio: la gestione del coordinatore permette solo l'inserimento del fuori classe, che però non è ancora utilizzabile/visibile sul registro. Per cui installare questa parte è inutile.

Anticipo la domanda: non so ancora quando riucirò a completare la gestione, soprattutto perché  questo mese è cruciale per altre scadenze (PNRR).

**Comment by Lucaccc** [comment]
> Mi spiego meglio: la gestione del coordinatore permette solo l'inserimento del fuori classe, che però non è ancora utilizzabile/visibile sul registro. Per cui installare questa parte è inutile.
> 
> Anticipo la domanda: non so ancora quando riucirò a completare la gestione, soprattutto perché questo mese è cruciale per altre scadenze (PNRR).

Va bene, grazie mille.
Buona serata.
