### ISSUE TITLE
Aggiornamento non prosegue

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#464]
Ho provato a fare l'aggiornamento: ho decompresso lo zip "update" ed eseguito l'aggiornamento raggiungendo \public\instal.php solo che rimane fermo al passo 5 e cliccando su "vai avanti" ricarica la pagina e non succede niente. Dice che l'aggiornamento non è avvenuto anche se non è avvenuto. A parte che credo che non abbia avuto effetto l'aggiornamento precedente, pure se diceva che l'aggiornamento era avvenuto. La stessa cosa adesso, cioè, qui addirittura la procedura non è completata.
[app_prod-2023-02-14.log](https://github.com/iisgiua/giuaschool/files/10735909/app_prod-2023-02-14.log)

**Comment by trinko** [comment]
L'aggiornamento alle ultime modifiche non si installa nello stesso modo dell'aggiornamento di versione.

Vedi: 
[#463](https://github.com/iisgiua/giuaschool/issues/463#issuecomment-1423052454)
