### ISSUE TITLE
Aggiornamenti dopo versione 1.5.2

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#466]
Buonasera, ho provato a installare le nuove modifiche con la nuova procedura da lei descritta, ma mi da questo errore

Fatal error: Uncaught TypeError: Cannot assign bool to property App\Install\Updater::$sys of type array in /membri/miosito/src/Install/Updater.php:191 Stack trace: #0 /membri/miosito/src/Install/Updater.php(218): App\Install\Updater->readSys() #1 /membri/miosito/src/Install/Updater.php(105): App\Install\Updater->init('miapassword') #2 /membri/miosito/public/install/update.php(15): App\Install\Updater->run('miapassword', 1) #3 {main} thrown in /membri/miosito/src/Install/Updater.php on line 191

Ho cambiato in miosito e miapassword per questioni di privacy.
Credo sia dovuto al fatto che altervista non legge estensioni diverse, come .gsupdating.
Mica c'è un altro modo per procedere o per arginare il problema?
Grazie.

**Comment by trinko** [comment]
Si, l'errore è dovuto al fatto che non risulta presente il file indicato. Altervista non ha problemi a gestire quel file, semplicemente non lo visualizza quando lo cerchi tramite gli strumenti che mette a disposizione.

Quindi: 
1) crea sul tuo computer il file con il nome corretto **.gs-updating**
2) carica con ftp il file sul sito Altervista (ad es. usa FileZilla)

A questo punto inizia la procedura come indicato.

**Comment by Lucaccc** [comment]
> Si, l'errore è dovuto al fatto che non risulta presente il file indicato. Altervista non ha problemi a gestire quel file, semplicemente non lo visualizza quando lo cerchi tramite gli strumenti che mette a disposizione.
> 
> Quindi:
> 
> 1. crea sul tuo computer il file con il nome corretto **.gs-updating**
> 2. carica con ftp il file sul sito Altervista (ad es. usa FileZilla)
> 
> A questo punto inizia la procedura come indicato.

Ho fatto tutte le operazioni preliminari, ma raggiungendo il sito mi dice: 

Fatal error: Uncaught TypeError: Cannot assign bool to property App\Install\Updater::$sys of type array in /membri/miosito/src/Install/Updater.php:191 Stack trace: #0 /membri/miosito/src/Install/Updater.php(218): App\Install\Updater->readSys() #1 /membri/miosito/src/Install/Updater.php(105): App\Install\Updater->init('miapassword') #2 /membri/miosito/public/install/update.php(15): App\Install\Updater->run('miapassword', 1) #3 {main} thrown in /membri/miosito/src/Install/Updater.php on line 191

**Comment by trinko** [comment]
Ho appena riprovato la procedura sul mio sito di test su Altervista e non ci sono errori.

C'è sicuramente qualche problema con il file **.gs-updating** che non viene trovato dalla procedura. Controlla che:
- il nome del file sia esattamente **.gs-updating** 
- il file si trovi nella directory principale, cioè quella che contiene anche il file **.env**

Altra possibilità è che ci siano dei permessi di lettura errati: controlla da FileZilla che il file abbia i permessi giusti (0664).

**Comment by Lucaccc** [comment]
> Il file .gs-updating è nella directory principale ed ha i permessi corretti; Ho caricato la cartella dell'aggiornamento in /src/install. Quindi credo di aver svolto tutto correttamente, ma continua a darmi lo stesso errore...
Da quello che leggo nell'errore mi sembra di capire che forse c'è qualche problema con il file updater.php...dice di no?

**Comment by Lucaccc** [comment]
> > Il file .gs-updating è nella directory principale ed ha i permessi corretti; Ho caricato la cartella dell'aggiornamento in /src/install. Quindi credo di aver svolto tutto correttamente, ma continua a darmi lo stesso errore...
> > Da quello che leggo nell'errore mi sembra di capire che forse c'è qualche problema con il file updater.php...dice di no?



> > 
> 
> Il file .gs-updating è nella directory principale ed ha i permessi corretti; Ho caricato la cartella dell'aggiornamento in /src/install. Quindi credo di aver svolto tutto correttamente, ma continua a darmi lo stesso errore...
Da quello che leggo nell'errore mi sembra di capire che forse c'è qualche problema con il file updater.php...dice di no?

**Comment by trinko** [comment]
Il file  **updater.php** non è stato modificato dopo la 1.5.2, per cui non penso sia quello il problema. L'errore è nella riga di caricamento del file  **.gs-updating** : o non lo trova o il suo contenuto è errato.

Quindi controlla:
- che il file contenga solo le due righe che avevo indicato
- che sia un semplice file di testo: leggilo con il blocco note e verifica che sia perfettamente leggibile
- che non contenga caratteri strani, come le lettere accentate

**Comment by Lucaccc** [comment]
> Il file **updater.php** non è stato modificato dopo la 1.5.2, per cui non penso sia quello il problema. L'errore è nella riga di caricamento del file **.gs-updating** : o non lo trova o il suo contenuto è errato.
> 
> Quindi controlla:
> 
> * che il file contenga solo le due righe che avevo indicato
> * che sia un semplice file di testo: leggilo con il blocco note e verifica che sia perfettamente leggibile
> * che non contenga caratteri strani, come le lettere accentate

Questo è il contenuto, ed è leggibile se lo apro con blocco note...

version=1.5.2-build
token=miapassword

Devo aggiungere per caso le virgolette quando scrivo la password?

**Comment by trinko** [comment]
I punti escamativi non sono un problema e non sono necessarie virgolette.
Non mi vengono altre idee su cosa non stia funzionando.

Comunque, sto finendo di modificare la procedura di aggiornamento, per renderla più semplice. La finirò tra oggi e domani, quindi direi di riprovare con quella.

**Comment by Lucaccc** [comment]
> I punti escamativi non sono un problema e non sono necessarie virgolette. Non mi vengono altre idee su cosa non stia funzionando.
> 
> Comunque, sto finendo di modificare la procedura di aggiornamento, per renderla più semplice. La finirò tra oggi e domani, quindi direi di riprovare con quella.

Grazie mille.

**Comment by trinko** [comment]
Per eseguire il nuovo aggiornamento alle ultime modifiche dopo il rilascio della versione 1.5.2, devi:

- scaricare i file seguenti e caricarli sul server nelle cartelle indicate, sovrascrivendo quelli esistenti
[aggiornamento.zip](https://github.com/iisgiua/giuaschool/files/10792873/aggiornamento.zip)

- cancellare la cache da **SISTEMA > MANUTENZIONE > CANCELLA CACHE**
in alternativa, o in caso di errori, cancella tutta la cartella **var/cache/prod**

- eseguire la procedura di aggiornamento da **SISTEMA > AGGIORNAMENTO**

**Comment by Lucaccc** [comment]
> Per eseguire il nuovo aggiornamento alle ultime modifiche dopo il rilascio della versione 1.5.2, devi:
> 
> * scaricare i file seguenti e caricarli sul server nelle cartelle indicate, sovrascrivendo quelli esistenti
>   [aggiornamento.zip](https://github.com/iisgiua/giuaschool/files/10792873/aggiornamento.zip)
> * cancellare la cache da **SISTEMA > MANUTENZIONE > CANCELLA CACHE**
>   in alternativa, o in caso di errori, cancella tutta la cartella **var/cache/prod**
> * eseguire la procedura di aggiornamento da **SISTEMA > AGGIORNAMENTO**

Grazie mille.
Funziona tutto correttamente.
