### ISSUE TITLE
Genitori  fuoriclasse

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#467]
C'è solo un problema:ai genitori non risulta il fuoriclasse quando il docente lo inserisce ,il che è un problema ,in quanto nel caso in cui dovesse succedere qualsiasi cosa ,la responsabilità andrebbe a ricadere sul docente di quell'ora, anche se questo non c'entra niente .

**Comment by trinko** [comment]
No, la funzionalità inserisce formalmente il "fuori classe" nel registro, che è un atto pubblico. Il fatto che i genitori non lo leggano è del tutto ininfluente sul piano del valore legale.
Quando il registro era solo cartaceo, i genitori non leggevano niente del suo contenuto, ma non per questo aveva un minor valore legale.

Sul piano della comunicazione ai genitori, invece, si usa una circolare/avviso, che sarà inserita prima dello svolgimento dell'attività.
