### ISSUE TITLE
Configura il server per l'invio delle email

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#468]
Buonasera ,sto cercando di configurare il server per l'invio delle mail .Quando inserisco dal lato amministratore nella sezione configura Email , selezionando server smtp ed inserendo i parametri del server di posta e cliccando su conferma ,ottengo il seguente messaggio:Errore nella spedizione della mail. [Connection could not be established with host "smtp.zoho.com:587": stream_socket_client(): Unable to connect to smtp.zoho.com:587 (Connection refused)].

A me sembra strano che mi esca questo errore ,dal momento che poi ho testato su internet inserendo tutti i parametri del server in un smtp  tester e di fatto l'email arriva e non ci sono errore ,come mai con il registro si?

**Comment by sempliciniluigi89** [comment]
Nel caso dell'invio tramite server locale php come funziona?
Intendo quali passaggi dovrei effettuare? Se è possibile una spiegazione semplice semplice

**Comment by trinko** [comment]
Devi solo configurare come tipo di server email:  "Usa server locale tramite PHP". Non è richiesta altra configurazione.

Questa modalità è ad es. l'unica che funziona su Altervista. Naturalmente se funziona uno degli altri metodi è meglio usare quello: l'invio di email tramite PHP è il più lento.

**Comment by sempliciniluigi89** [comment]
In pratica  come hosting uso x10hosting ,dove ho provato ad effettuare l'invio tramite php .Quando cerco di inviare ai docenti le credenziali via mail o quando i docenti o qualsiasi utente cerca di recuperare la password esce il messaggio in verde che dice che l'email è stata inviata all'indirizzo registrato ,ma quando si entra nella casella postale ,non risulta niente ,anche dopo 2/3 giorni ,in quanto avete detto che è un sistema lento.Questo non succede se si utilizza l'email offerto dall'hosting x10hosting

**Comment by trinko** [comment]
Dovresti chiedere al supporto dell'hosting. Io ho visto velocemente alcuni messaggi sui forum di x10hosting e mi è sembrato di capire che il servizio SMTP è bloccato per i siti free.
In ogni caso suggeriscono di usare l'account email creato su x10hosting come mittente delle mail.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
