### ISSUE TITLE
Uso dei Moduli

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#470]
Buonasera, dopo l'aggiornamento alle ultime modifiche della versione 1.5.2, non funziona più, sul mio registro, l'uso dei moduli: li fa inserire da amministratore, ma quando gli studenti provano a inserire una nuova richiesta appare il seguente avviso:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

P.s. prima degli aggiornamenti i moduli funzionavano correttamente.
A cosa può essere dovuto?
Grazie.

**Comment by trinko** [comment]
Attiva la modalità debug, riprova l'inserimento del modulo e poi estrai il log e caricalo qui.

**Comment by Lucaccc** [comment]
[2023-02-25_10-25.log](https://github.com/iisgiua/giuaschool/files/10830728/2023-02-25_10-25.log)
Ecco il file di log.

**Comment by trinko** [comment]
C'è un errore di sintassi nel template usato per la richiesta, ma è difficile sapere di cosa si tratta.

Per prima cosa prova a cancellare la cache, eventualmente anche manualmente dal pannello di controllo di Altervista (cartella **var/cache/prod**).

Se non cambia niente, recupera il file del template dalla cartella **PERSONAL/data/moduli**, assicurati che non contenga dati personali (eventualmente cancellali) e postalo qui.

**Comment by Lucaccc** [comment]
[pcto_public_speaking.txt](https://github.com/iisgiua/giuaschool/files/10851733/pcto_public_speaking.txt)

**Comment by trinko** [comment]
Il file **pcto_public_speaking.txt** che hai allegato non presenta errori di sintassi e rinominato come **pcto_public_speaking.html.twig** funziona correttamente sull'ambiente di test su Altervista. Per cui non riesco a riprodurre l'errore.

Puoi provare a fare i seguenti controlli: 
- ricontrolla la corretezza della configurazione del modulo di richiesta (come amministratore);
- verifica che il modulo usato corrisponda al file  **PERSONAL/data/moduli/pcto_public_speaking.html.twig**
- verifica di non aver fatto modifiche ai template nela cartella **templates/richieste**

**Comment by sempliciniluigi89** [comment]
Anche io riscontro lo stesso problema



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/28/23,
09:53:07 PM

Il giorno mar 28 feb 2023 alle ore 19:32 Antonello Dessì <
***@***.***> ha scritto:

**Comment by Lucaccc** [comment]
> Il file **pcto_public_speaking.txt** che hai allegato non presenta errori di sintassi e rinominato come **pcto_public_speaking.html.twig** funziona correttamente sull'ambiente di test su Altervista. Per cui non riesco a riprodurre l'errore.
> 
> Puoi provare a fare i seguenti controlli:
> 
> * ricontrolla la corretezza della configurazione del modulo di richiesta (come amministratore);
> * verifica che il modulo usato corrisponda al file  **PERSONAL/data/moduli/pcto_public_speaking.html.twig**
> * verifica di non aver fatto modifiche ai template nela cartella **templates/richieste**

[2023-02-28_22-10.log](https://github.com/iisgiua/giuaschool/files/10854811/2023-02-28_22-10.log)

**Comment by Lucaccc** [comment]
> Il file **pcto_public_speaking.txt** che hai allegato non presenta errori di sintassi e rinominato come **pcto_public_speaking.html.twig** funziona correttamente sull'ambiente di test su Altervista. Per cui non riesco a riprodurre l'errore.
> 
> Puoi provare a fare i seguenti controlli:
> 
> * ricontrolla la corretezza della configurazione del modulo di richiesta (come amministratore);
> * verifica che il modulo usato corrisponda al file  **PERSONAL/data/moduli/pcto_public_speaking.html.twig**
> * verifica di non aver fatto modifiche ai template nela cartella **templates/richieste**

Ho verificato: è tutto in ordine, ma non funziona lo stesso.

**Comment by tommasiangelo01** [comment]
Adesso ho visto che il problema non si verifica solo con il modulo pcto ,bensì anche con i regolari moduli di deroga uscita,ingresso etc...

**Comment by trinko** [comment]
E' possibile che l'errore sia dovuto a qualche modifica imprevista dei due template che allego. Prova quindi:

1) scarica i file seguenti nella cartella **templates/richieste** e sovrascrivi quelli esistenti:
[richieste.zip](https://github.com/iisgiua/giuaschool/files/10864374/richieste.zip)

2. cancella la cache
3. attiva il debug
4. riprova a inserire il modulo

Se mostra ancora l'errore, carica estrai il log e caricalo, così da verificare se è sempre lo stesso.

**Comment by Lucaccc** [comment]
> E' possibile che l'errore sia dovuto a qualche modifica imprevista dei due template che allego. Prova quindi:
> 
> 1. scarica i file seguenti nella cartella **templates/richieste** e sovrascrivi quelli esistenti:
>    [richieste.zip](https://github.com/iisgiua/giuaschool/files/10864374/richieste.zip)
> 
> 2. cancella la cache
> 3. attiva il debug
> 4. riprova a inserire il modulo
> 
> Se mostra ancora l'errore, carica estrai il log e caricalo, così da verificare se è sempre lo stesso.

Perfetto, ora funziona.
Grazie.
