### ISSUE TITLE
Rettifica e pubblicazione circolari

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#472]
Buon pomeriggio,
dopo l'installazione delle ultime modifiche sto riscontrado un altro problema: quando si inserisce una nuova circolare, appare l'errore 
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Tornando indietro la circolare viene caricata correttamente, quindi penso sia dovuto al mancato invio delle notifiche.
Inoltre, se si inserisce un nuovo documento (es. rettificato), dopo la pubblicazione della stessa circolare, appare lo stesso errore e il nuovo documento inserito non si apre.
Grazie.

**Comment by trinko** [comment]
Devi darmi più informazioni: attiva il debug e scarica il log degli errori.

**Comment by Lucaccc** [comment]
> Devi darmi più informazioni: attiva il debug e scarica il log degli errori.

[2023-02-28_22-10.log](https://github.com/iisgiua/giuaschool/files/10854818/2023-02-28_22-10.log)

**Comment by trinko** [comment]
E' necessario  eseguire il seguente comando SQL tramite PHPMyAdmin:

```
ALTER TABLE gs_messenger_messages CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id);
```

**Comment by Lucaccc** [comment]
> E' necessario eseguire il seguente comando SQL tramite PHPMyAdmin:
> 
> ```
> ALTER TABLE gs_messenger_messages CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id);
> ```

Perfetto, grazie. Ora funziona correttamente.
