### ISSUE TITLE
Configurazione telegram

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#477]
Buongiorno, sto provando ad abilitare la gestione notifiche tramite telegram, ma appare questo errore:

Errore nella configurazione Telegram. [Client error: `POST https://api.telegram.org/botOMESSO/setWebhook` resulted in a `400 Bad Request` response: {"ok":false,"error_code":400,"description":"Bad Request: bad webhook: An HTTPS URL must be provided for webhook"} ]

A cosa è dovuto?

**Comment by trinko** [comment]
Sembra che non sia stata fatta la configurazione lato amministratore (impostazione del bot).
Procedi in questo modo:
- assicurati di aver scaricato gli ultimi aggiornamenti
- vedi la documentazione [Gestione notifiche](https://iisgiua.github.io/giuaschool-docs/task-notifier.html)

Se c'è quacosa di poco chiaro, chiedi pure.

**Comment by trinko** [comment]
Riguardando l'errore che hai postato mi sono accorto che il problema principale è che stai usando un sito per il registro con HTPP e non HTTPS. Questo non è permesso da Telegram.

Attiva l'HTTPS del sito del registro, se usi altervista è gratuito.

**Comment by Lucaccc** [comment]
> Riguardando l'errore che hai postato mi sono accorto che il problema principale è che stai usando un sito per il registro con HTTP e non HTTPS. Questo non è permesso da Telegram.
> 
> Attiva l'HTTPS del sito del registro, se usi altervista è gratuito.

Sto già utilizzando HTTPS...
Ho un dubbio: il bot telegram va semplicemente creato con Fatherbot oppure poi devo configurare dei comandi all'interno di questo?
Perchè altrimenti non capisco cosa non funziona..

**Comment by Lucaccc** [comment]
Un'altra domanda...visto che il registro non mi invia automaticamente le notifiche, ho provato con cronjob, ma mi da questo errore: 

URL VISITATO
http://miosito.altervista.org/command/notify/token/600
STATO
302 Found

E dice che la procedura è fallita...come mai?

**Comment by trinko** [comment]
> Un'altra domanda...visto che il registro non mi invia automaticamente le notifiche, ho provato con cronjob, ma mi da questo errore:
> 
> URL VISITATO http://miosito.altervista.org/command/notify/token/600 STATO 302 Found
> 
> E dice che la procedura è fallita...come mai?

L'indirizzo nel tuo caso dovrebbe essere probabilmente:  **https://miosito.altervista.org/public/command/notify/token/600**

E naturalmente al posto di _token_ il codice inserito nell'apposito parametro con _comando_token_.

**Comment by trinko** [comment]
> Ho un dubbio: il bot telegram va semplicemente creato con Fatherbot oppure poi devo configurare dei comandi all'interno di questo? Perchè altrimenti non capisco cosa non funziona, visto che continua a darmi lo stesso errore..

Si è sufficiente crearlo con un nome e memorizzare il token che viene creato. Puoi abbellire il bot con le immagini del logo e la descrizione, per rendere più chiaro il suo utilizzo agli utenti, ma non è indispensabile.

Per quanto riguarda l'errore, è strano perché dice proprio che non viene fornita un indirizzo HTTPS. Non è che, pur essendo attivo l'HTTPS, quando hai usato la pagina di configurazione Telegram stavi usando l'HTTP? Questo spiegherebbe l'errore: l'indirizzo è creato a partire dall'indirizzo della pagina corrente.

**Comment by Lucaccc** [comment]
> https://miosito.altervista.org/public/command/notify/token/600

In effetti credo sia così...ma come faccio a modificarlo se su altervista mi dice che è già attivo?

**Comment by Lucaccc** [comment]
> > Ho un dubbio: il bot telegram va semplicemente creato con Fatherbot oppure poi devo configurare dei comandi all'interno di questo? Perchè altrimenti non capisco cosa non funziona, visto che continua a darmi lo stesso errore..
> 
> Si è sufficiente crearlo con un nome e memorizzare il token che viene creato. Puoi abbellire il bot con le immagini del logo e la descrizione, per rendere più chiaro il suo utilizzo agli utenti, ma non è indispensabile.
> 
> Per quanto riguarda l'errore, è strano perché dice proprio che non viene fornita un indirizzo HTTPS. Non è che, pur essendo attivo l'HTTPS, quando hai usato la pagina di configurazione Telegram stavi usando l'HTTP? Questo spiegherebbe l'errore: l'indirizzo è creato a partire dall'indirizzo della pagina corrente.

In effetti credo sia così...ma come faccio a modificarlo se su altervista mi dice che è già attivo?

**Comment by trinko** [comment]
> > Per quanto riguarda l'errore, è strano perché dice proprio che non viene fornita un indirizzo HTTPS. Non è che, pur essendo attivo l'HTTPS, quando hai usato la pagina di configurazione Telegram stavi usando l'HTTP? Questo spiegherebbe l'errore: l'indirizzo è creato a partire dall'indirizzo della pagina corrente.
> 
> In effetti credo sia così...ma come faccio a modificarlo se su altervista mi dice che è già attivo?

Se modifichi l'indirizzo della pagina usando HTTPS al posto di HTTP e la ricarichi dovrebbe funzionare.

Se invece vuoi che automaticamente ogni pagina HTTP sia reindirizzata su HTTPS è necessario modificare il file **.htaccess** che trovi nella cartella **public** , aggiungendo alla fine:
```
# Redirect to HTTPS
RewriteCond %{HTTPS} off
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by Lucaccc** [comment]
> # Redirect to HTTPS
> RewriteCond %{HTTPS} off
> RewriteCond %{HTTP:X-Forwarded-Proto} !https
> RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Ho modificato l'indirizzo con HTTPS ma continua a darmi lo stesso errore..

**Comment by trinko** [comment]
Si, ho visto che viene sempre genarata una URL HTTP per la registrazione su Telegram.
Vedo di risolvere il problema.

**Comment by Lucaccc** [comment]
> Per risolvere il problema, estrai il file seguente e sovrascrivi quello esistente nella cartella **src/Util**
> 
> [TelegramManager.php.zip](https://github.com/iisgiua/giuaschool/files/11026073/TelegramManager.php.zip)

Ora funziona correttamente.
Grazie mille.
