### ISSUE TITLE
come creare il registro elettronico

### ISSUE THREAD

**Issue by Bologna221** [iisgiua/giuaschool#482]
### Discussed in https://github.com/iisgiua/giuaschool/discussions/481

<div type='discussions-op-text'>

<sup>Originally posted by **Bologna221** March 25, 2023</sup>
salve come si crea il registro elettronico, è possibile ricevere aiuto?</div>

**Comment by trinko** [comment]
Se non scrivi i dettagli del problema non è  possibile fornirti  aiuto.
Primo: leggi la documentazione e segui le procedure indicate. Se poi ci sono errori in qualche fase, specifica bene dove riscontri l'errore, cioè durante quale procedura e che tipo di errore.

**Comment by manuelbarberi** [comment]
scrivi alla mail giuaschoolregistro@gmail.com... il team l'ho fondato io e lavorano anche molto bene... ti potranno aiutare...

**Comment by Bologna221** [comment]
Salve ho già scritto una mail

Il giorno mer 29 mar 2023 alle 20:16 Lucaccc ***@***.***> ha
scritto:

**Comment by manuelbarberi** [comment]
mi hanno riferito che hanno risposto

Il giorno gio 30 mar 2023 alle 12:05 Bologna221 ***@***.***>
ha scritto:

**Comment by manuelbarberi** [comment]
Non gestisco purtroppo io il forum assistenza poichè c'è un team dedicato... Deve solo attendere loro...

**Comment by nicolatrentini** [comment]
buongiorno ho inviato una mail a giuaschoolregistro@gmail.com e pure a m.barberi.icempoliovest@gmail.com
la prego mi rispondete
