### ISSUE TITLE
Errore aggiornamento

### ISSUE THREAD

**Issue by rodolfo024** [iisgiua/giuaschool#499]
Ciao scusa, ho provato a eseguire l'aggiornamento direttamente dal portale, ma mi compare l'errore 500.
Questo è il log:
[app_prod-2023-03-03.log](https://github.com/iisgiua/giuaschool/files/11374764/app_prod-2023-03-03.log)

**Comment by trinko** [comment]
Da che versione stai aggiornando? Il log non è esauriente, credo che tu non abbia attivato il debug.
L'errore riportato nel log dice solo che hai provato ad uscire dall'alias quando eri già disconnesso. 
Forse è solo un problema della cache non cancellata completamente: cancella a mano la cartella **var/cache/prod**

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
