### ISSUE TITLE
SCRUTINI

### ISSUE THREAD

**Issue by GIANLUCA2509** [iisgiua/giuaschool#510]
**Descrivi il problema**
Eroore quando si procede con l'inserimento dei voti

**Indica come riprodurre l'errore**
quando schiaccio continua conlo scrutinio dopo aver inserito dice eroore

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Servono più informazioni.
Viene mostrato un messaggio di errore nella pagina? Quale?
Quale scrutinio? Quello finale?
Quale inserimento voti? Condotta, Ed. civica, altri voti?
Stai usando l'ultima versione del registro? Hai anche eseguito gli aggiornamenti successivi al rilascio?

**Comment by GIANLUCA2509** [comment]
Nella pagina di apertura dello scrutinio
Nel secondo quadrimestre
dopo le assenze degli alunni mi da errore
La versione 1.5.4

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
