### ISSUE TITLE
PROBLEMA SCRUTINIO FINALE CLASSE QUINTA

### ISSUE THREAD

**Issue by gmontalbano5ct** [iisgiua/giuaschool#512]
quando clicco apri lo scrutinio mi da errore 500 non capisco perché. @trinko 
[2023-06-05_16-17.log](https://github.com/iisgiua/giuaschool/files/11653628/2023-06-05_16-17.log)

qualcuno sa aiutarmi?

**Comment by rodolfo024** [comment]
Io invece ho provato a simulare lo scrutinio di una quinta ma nel passaggio allo step successivo alla conversione del credito mi compare l'errore 500.
[app_prod-2023-06-05.log](https://github.com/iisgiua/giuaschool/files/11654076/app_prod-2023-06-05.log)

**Comment by gmontalbano5ct** [comment]
io ho risolto il problema per errore avevo cancellato alcuni dati dal database grazie della collaborazione

**Comment by trinko** [comment]
> Io invece ho provato a simulare lo scrutinio di una quinta ma nel passaggio allo step successivo alla conversione del credito mi compare l'errore 500. [app_prod-2023-06-05.log](https://github.com/iisgiua/giuaschool/files/11654076/app_prod-2023-06-05.log)

Stai usando la vecchia versione. E' necessario aggiornare alla 1.5.4 perché la conversione del credito del credito non è prevista quest'anno.
