### ISSUE TITLE
Impossibile aggiornamento alla versione 1.5.4

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#513]
[2023-06-05_17-26.log](https://github.com/iisgiua/giuaschool/files/11654184/2023-06-05_17-26.log)

**Comment by trinko** [comment]
E' un problema del server che non permette l'esecuzione di una procedura per un tempo prolungato.

Devi fare l'aggiornamento manuale: anzi tutto carica il file della versione 1.5.4 sul server e decomprimilo andando a sovrascrivere i file esistenti. In alternativa, decomprimi sul tuo computer il file della versione 1.5.4 e poi carica tutti i file con Filezilla. Questo secondo metodo è più lento, ma da' maggiori garanzie che non ci siano file mancanti.

Fatto questo, crea sulla cartella principale, il file ".gs-updating" che deve contenere le seguenti 3 righe:
```
version:1.5.4
build:0
token:codice
```
Per il **token** usa un codice a piacere.

A questo punto termina l'installazione andando alla pagina:
**nome_sito/install/update.php?token=codice&step=2**

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
