### ISSUE TITLE
errore urgente scrutinio

### ISSUE THREAD

**Issue by gianlucaaiello56** [iisgiua/giuaschool#518]
Gentili,  @bfabio @trinko @zerai @MatteoGheza 
vorrei segnalare un errore dello scrutinio.
Quando il coordinatore va nella schermata scrutinio della classe coordinante il sistema da come riscontro un errore.

Per riprodurre l'errore è necessario recarsi nella schermata "coordinatore> scrutinio"

[2023-06-06_14-00 (2).log](https://github.com/iisgiua/giuaschool/files/11667558/2023-06-06_14-00.2.log)

**Comment by trinko** [comment]
In ogni caso, è possibile far ripartire la procedura dello scrutinio dall'inizio nel modo seguente:

1. dal pannello di controllo del proprio servizio di hosting, andare su PHPMyAdmin
2. una volta entrati su PHPMYAdmin, cliccare sulla scheda SQL
3. inserire il comando seguente e premere il pulsante ESEGUI:
```
UPDATE gs_scrutinio SET stato='N' WHERE periodo='F' AND stato!='N' AND stato!='C';
```
**ATTENZIONE: il comando riporta alla pagina di inizio scrutinio TUTTE le classi con scrutinio aperto.**

**Comment by gianlucaaiello56** [comment]
@trinko sì, abbiamo aperto oggi lo scrutinio con la versione 1.5.4 però non riusciamo ad andare al "passo 2"

**Comment by trinko** [comment]
Mi spiace ma il log riportato non contiene i dati della pagina di errore.

Devi procedere esattamente in questo modo:
1. assicurarti che sia attivo il debug, nella pagina di manutenzione
2. andare alla pagina dello scrutinio che genera l'errore
3. tornare alla pagina di manutenzione del log ed estrarre il log assicurandoti di includere l'ora in cui è stato generato l'errore (solitamente 5 minuti prima dell'ora corrente sono sufficienti).
4. caricare qui il log generato

**Comment by gianlucaaiello56** [comment]
[2023-06-07_07-00.log.txt](https://github.com/iisgiua/giuaschool/files/11672711/2023-06-07_07-00.log.txt)

Allego il log errori @trinko -mi scusi per il disturbo ma purtroppo non siamo riusciti a risolvere 😔

**Comment by trinko** [comment]
Ok, ho capito il problema.
Appena posso invio la correzione.

**Comment by trinko** [comment]
Questo dovrebbe risolvere il problema, almeno per ora.
Decomprimi il file e caricalo sul server nella cartella **src/Util/**, andando a sovrascrivere quello esistente.
Poi esegui la pulizia della cache (SISTEMA > MANUTENZIONE > svuota cache) e riprova.

[ScrutinioUtil.php.tar.gz](https://github.com/iisgiua/giuaschool/files/11673649/ScrutinioUtil.php.tar.gz)

**Comment by trinko** [comment]
MI viene un dubbio: non è che stai aprendo lo scrutinio finale di una classe per la quale non hi fatto lo scrutinio del primo Ttrimestre/Quardimestre?
Se è questo il caso, va fatto per forza lo scrutinio del primo periodo (eventualemte in modo fittizio), altrimenti la procedura non funziona.

**Comment by gianlucaaiello56** [comment]
@trinko ecco il problema: in quanto abbiamo cambiato registro non avevamo caricato questi voti del primo quadrimestre. Per risolvere ora ,secondo lei, vi sarebbe un modo ?
