### ISSUE TITLE
Problema proposte di voto 

### ISSUE THREAD

**Issue by nicholas20220** [iisgiua/giuaschool#519]
Buongiorno, sono da quando ho fatto l’aggiornamento (ero ad una versione molto antica) quando vado sulle proposte di voto come docente (quindi nella materia che insegno) mi da errore. 
qualcuno sa come risolvere.
Grazie.

**Comment by nicholas20220** [comment]
Vi inoltro il log.
[Uploading Safari.pdf…]()

**Comment by nicholas20220** [comment]
[Uploading Safari.pdf…]()

**Comment by trinko** [comment]
Il log non è leggibile... Ricordati di
- attivare il debug
- rieseguire la pagina che da' l'errore
- estrarre il log e caricarlo (senza trasformarlo in altri formati).

**Comment by nicholas20220** [comment]
[2023-06-07_15-05.log](https://github.com/iisgiua/giuaschool/files/11677364/2023-06-07_15-05.log)

**Comment by nicholas20220** [comment]
mi faccia sapere se ora si vede.
grazie.

**Comment by trinko** [comment]
L'errore riportato dice che non trova il template **lezioni/proposte_U.html.twig**.
Ma questo non è un template previsto nel registro (la **U** è un codice che indica il periodo, ma non è tra quelli previsti nel registro).
Devo supporre quindi che siano state fatte modifiche al codice originale, per cui non sono in grado di dare nessun aiuto.

**Comment by trinko** [comment]
Oppure sono stati inseriti nel database, a mano, dei dati incongruenti. In tal caso si dovrebbe risolvere cancellandoli.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
