### ISSUE TITLE
Errore scrutinio primo quadrimestre

### ISSUE THREAD

**Issue by gianlucaaiello56** [iisgiua/giuaschool#521]
@bfabio @trinko @zerai @MatteoGheza 
Volevo segnalare il seguente problema.. quando si vogliono inserire le proposte di voto è impossibile avviare lo scrutinio da parte del coordinatore perché il voto di educazione civica non è inseribile.

Per riprodurre l'errore bisogna recarsi su COORDINATORE > SCRUTINI > AVVIA SCRUTINIO

![image](https://github.com/iisgiua/giuaschool/assets/125404884/e070c1bd-9e92-4f56-bb5c-f44cef489401)

**Comment by gianlucaaiello56** [comment]
praticamente esce un'educazione civica in più.. e non è rimovibile

**Comment by Lucaccc** [comment]
> @bfabio @trinko @zerai @MatteoGheza Volevo segnalare il seguente problema.. quando si vogliono inserire le proposte di voto è impossibile avviare lo scrutinio da parte del coordinatore perché il voto di educazione civica non è inseribile.
> 
> Per riprodurre l'errore bisogna recarsi su COORDINATORE > SCRUTINI > AVVIA SCRUTINIO
> 
> ![image](https://user-images.githubusercontent.com/125404884/244116009-e070c1bd-9e92-4f56-bb5c-f44cef489401.png)

Credo il problema sia dovuto al fatto che avete inserito come materia l'educazione civica, dal pannello amministratore: l'educazione civica, così come il sostegno e il comportamento sono materie presenti di default.
Provate a rimuovere la materia aggiunta da voi (dovrebbe essere quella in maiuscolo "EDUCAZIONE CIVICA", perchè quella di default appare come "Ed.Civica").

**Comment by gianlucaaiello56** [comment]
Anche eliminando non va

**Comment by nicholas20220** [comment]
buongiorno, anche a me lo stesso problema. qualcuno mi può aiutare?. grazie

**Comment by trinko** [comment]
Devi entrare come amministratore e andare alla pagina **SCUOLA > MATERIE**.
Qui controlla che esista una sola materia con tipo **Ed. civica**. In tal caso elimina quella in più.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
