### ISSUE TITLE
Pagella non visibile in seguito al passaggio all'anno scolastico nuovo 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#530]
Buongiorno ,abbiamo effettuato il passaggio all'anno nuovo 2023/2024 ,ma i genitori ci segnalano che non è più visibile la pagella finale ,tanto meno quella del primo quadrimestre.Come si può rimediare ?Grazie

**Comment by trinko** [comment]
Attualmente, la procedura del passaggio d'anno andrebbe fatta in prossimità dell'inizio del nuovo anno, perché cancella molti dati dell'anno corrente, per lasciar posto a quelli del nuovo anno. E' pertanto fondamentale effettuare la procedura di archiviazione PRIMA di quella del passaggio d'anno.

Per le pagelle, è conservata solo quella finale, che dovrebbe essere visibile ai genitori nel periodo indicato come "A.S. precedente".

**Comment by sempliciniluigi89** [comment]
non c'è nemmeno quella finale ,nonostante io abbia effettuato il backup ed archiviato tutto come da guida.Appena mi dirigo su pagella esce il seguente avviso "Dati non disponibili"

**Comment by trinko** [comment]
Controlla la cartella **FILES/archivio/scrutini/storico**: qui dentro dovrebbero esserci i file PDF degli scrutini.
In ogni caso, spero tu abbia fatto un backup completo prima della procedura di passaggio d'anno.

**Comment by sempliciniluigi89** [comment]
Sì, per fortuna avevo fatto il backup prima di avviare l'archiviazione e tutto quanto.Solo che adesso il registro risulta aggiornato al nuovo anno e ho paura che importando il backup possa andare storto qualcosa .Comunque ho seguito il percorso FILES/archivio/scrutini/storico e non c'è niente ,risulta vuota la cartella

**Comment by trinko** [comment]
Ma quando il genitore va sulla pagina PAGELLE del periodo **A.S. Precedente**, viene visualizzato l'esito? Perché in tal caso si possono recuperare dal backup solo i PDF e si risolve così.

**Comment by sempliciniluigi89** [comment]
Quando il genitore si reca nel registro su "pagelle" non le appare proprio
la scritta "pagelle anno precedente", l'unica cosa che visualizza è  "i
dati non sono disponibili", tutto qua.

Il Sab 17 Giu 2023, 17:46 Antonello Dessì ***@***.***> ha
scritto:

**Comment by trinko** [comment]
Se durante la procedura di aggiornamento d'anno sono stati mostrati messaggi di errore oppure una pagina completamente bianca, allora è purtroppo normale che ci siano dei dati mancanti.
Ma se la procedura è andata avanti senza nessun problema, è molto strano che non siano stati elaborati i dati degli scrutini svolti.

In entrambi i casi ti consiglio tornare alla situazione precedente recuperando il backup completo (tutti i file e il database).

**Comment by sempliciniluigi89** [comment]
Non appena cerco di importare il backup completo ,mi restituisce il seguente errore che allego in foto 

<img width="1196" alt="Screenshot 2023-06-18 alle 02 17 52" src="https://github.com/iisgiua/giuaschool/assets/93823125/ba49d61a-a31f-42bd-bba5-b6e8d1c42e85">

**Comment by trinko** [comment]
Prima di importare il database completo devi cancellare tutte le tabelle.
Clicca in alto sulla voce database, in modo da visualizzare tutte le tabelle: selezionale tutte ed eliminale.
Poi fai l'importazione del database di backup.
Ricorda che devi anche ricaricare il backup di tutti i file.
