### ISSUE TITLE
Errore sul funzionamento dei moduli di richiesta

### ISSUE THREAD

**Issue by giadaschiavone** [iisgiua/giuaschool#538]
**Descrivi il problema**

Con il passaggio al nuovo anno scolastico, abbiamo deciso di creare i moduli di richiesta. Il problema è che la scuola ha voluto provare il funzionamento dei moduli di richiesta, solo che quando entrano in _Alias_ sul profilo di un genitore, gli appare l'errore e di conseguenza l'impossibilità di creare una richiesta. Abbiamo chiesto ad alcuni genitori rappresentanti di provare il funzionamento e se anche a loro segnalava errore, ma il risultato è stato che anche i genitori hanno avuto lo stesso problema, anche se i moduli risultano essere inseriti correttamente e risultano essere operativi.

**Indica come riprodurre l'errore**

L'errore si riproduce accedendo al profilo da genitore (oppure nel profilo da studente, in caso di alunni maggiorenni) andando sulla sezione _Richieste_. Successivamente, quando ci si trova nella pagina, nella voce della richiesta spunta un bottone con su scritto: _Inserisci una nuova richiesta_. Quando ci si schiaccia il bottone, c'è l'errore. Accade anche per le altre richieste.

**File di LOG**

Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

[2023-06-26_13-21.log](https://github.com/iisgiua/giuaschool/files/11868175/2023-06-26_13-21.log)

**Comment by trinko** [comment]
C'è un errore di sintassi nel template usato per il modulo:
_"The name "Eventuali note" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("\_"), hyphens ("-") and colons (":")."_

**Comment by giadaschiavone** [comment]
D'accordo, provvedo.

**Comment by giadaschiavone** [comment]
Ciao @trinko. Io non riesco comunque a risolvere il problema. Dovrei accedere al panello di controllo e modificare lì?

**Comment by trinko** [comment]
Come utente AMMINISTRATORE, entri nel registro e vai su **SCUOLA > MODULI DI RICHIESTA**: qui controlli che nella configurazione dei moduli, nella **lista dei campi da compilare** i nomi dei campi non abbiamo spazi o caratteri speciali.

Quindi controlli che il modello (template) caricato nella cartella **PERSONAL/data/moduli/** contenga gli stessi nomi di campo che configurato.

**Comment by giadaschiavone** [comment]
D'accordo, grazie mille!

Il giorno sab 1 lug 2023 alle ore 00:21 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
