### ISSUE TITLE
Errore 500 coordinatori

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#540]
Buongiorno,non appena vado su "coordinatori" dalla sezione amministratore ,mi esce l'errore 500 che ora allego 

[2023-06-29_18-07.log](https://github.com/iisgiua/giuaschool/files/11908029/2023-06-29_18-07.log)

**Comment by trinko** [comment]
C'è un problema di configurazione del registro.
Per funzionare correttamente, è necessario definire almeno una sede scolastica, poi ogni classe deve essere associata alla sede e il coordinatore alla classe. Per qualche motivo, nel tuo registro non risulta definita la sede probabilmente per una o più classi.
Per questo cercando di visualizzare i coordinatori risulta un errore imprevisto.

Controlla quindi con attenzione la configurazione delle SEDI e delle CLASSI.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
