### ISSUE TITLE
errore rappresentante ata

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#541]
Quando inserisco il rappresentante del personale ata e clicco su conferma ,mi esce il seguente messaggio che ne impedisce il corretto proseguimento : Il valore inserito non è un indirizzo email valido.

**Comment by trinko** [comment]
Il problema non mi pare abbia a che fare con la procedura dei rappresentanti ma con l'email associata all'utente scelto.
In altre parole, quando un utente viene indicato come rappresentante, vengono validati anche gli altri dati presenti per controllarne la correttezza. Lo stesso errore dovrebbe venir fuori se fai ATA > MODIFICA e scegli lo stesso utente e confermi i dati esistenti.

Il problema è quindi nei dati presenti dell'email: o non è una email nel formato corretto (_qualcosa@dominio.xx_), opure la stessa email è presente più volte nel sistema.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
