### ISSUE TITLE
Conversione al nuovo anno scolastico non possibile

### ISSUE THREAD

**Issue by giadaschiavone** [iisgiua/giuaschool#551]
**Descrivi il problema**

La conversione al nuovo anno scolastico con l'aggiornamento dell'applicazione alla nuova versione non è possibile, poiché, all'inizio del procedimento, risulta un errore. 

**Indica come riprodurre l'errore**

Per riprodurre l'errore, sono andata ad aggiornare l'applicazione del registro elettronico. Successivamente, l'aggiornamento non ha dimostrato errori ed è andato tutto bene. Dopo essere uscita dalla pagina per l'aggiornamento, sono andata sulla pagina per l'avvio al nuovo anno scolastico e ho eseguito tutte le procedure. Dopo averle eseguite, mi appare errore e non è possibile la conversione al nuovo anno scolastico.

**File di LOG**

Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

[2023-07-18_11-50.log](https://github.com/iisgiua/giuaschool/files/12079039/2023-07-18_11-50.log)

**Comment by trinko** [comment]
L'errore pare essere dovuto alla mancanza della configurazione del dirigente scolastico.
Controlla in **SCUOLA > DIRIGENTE SCOLASTICO** che sia configurato. Se non risulta configurato, il problema è quello.

**Comment by trinko** [comment]
**ATTENZIONE:** se il problema era quello, non puoi semplicemente rieseguire la procedura di passaggio d'anno, perché i primi passi che hai eseguito correttamente hanno già cancellato dati e otterrai una installazione con dati mancanti.

Prima di rieseguire la procedura di passaggio d'anno è indispensabile quindi ripristinare il backup completo del registro (database e file).

**Comment by giadaschiavone** [comment]
Ora il problema è stato risolto. Ho configurato il registro per l'anno scolastico corrente (istituto, dirigenti e variabili) e dopo l'ho convertito con il nuovo anno.
