### ISSUE TITLE
Problema configurazione email 

### ISSUE THREAD

**Issue by mpignatelli** [iisgiua/giuaschool#556]
**Descrivi il problema**
Salve ho un problema: quando vado sul sistema e vado configurazione email mi dice errore 500. Come devo fare 

**Indica come riprodurre l'errore**

Errore 500
**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Prima di tutto, quando riporti il log non fare copia e incolla, ma allega l'intero file al messaggio. Leggere il log riportato nel messaggio è molto complicato... Solitamente è sufficiente trascinare il file nella parte bassa del messaggio (sulla scritta "Attach files by dragging & dropping, selecting or pasting them").

Comunque il problema è che Altervista permette come email unicamente il metodo indicato come **"Usa server locale tramite PHP"**.

**Comment by mpignatelli** [comment]
#

> **Descrivi il problema** Salve ho un problema: quando vado sul sistema e vado configurazione email mi dice errore 500. Come devo fare
> 
> **Indica come riprodurre l'errore**
> 
> Errore 500 **File di LOG** Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by mpignatelli** [comment]
> Prima di tutto, quando riporti il ​​log non fare copia e incolla, ma allega l'intero file al messaggio. Leggere il log riportato nel messaggio è molto complicato... Solitamente è sufficiente trascinare il file nella parte bassa del messaggio (sulla scritta "Allega file trascinandoli, selezionandoli o incollandoli").
> 
> Comunque il problema è che Altervista permette come email unicamente il metodo indicato come **"Usa server locale tramite PHP"** .

Come faccio ad allegare il file del log

**Comment by mpignatelli** [comment]
> Prima di tutto, quando riporti il ​​log non fare copia e incolla, ma allega l'intero file al messaggio. Leggere il log riportato nel messaggio è molto complicato... Solitamente è sufficiente trascinare il file nella parte bassa del messaggio (sulla scritta "Allega file trascinandoli, selezionandoli o incollandoli").
> 
> Comunque il problema è che Altervista permette come email unicamente il metodo indicato come **"Usa server locale tramite PHP"** .

In che senso mi scusi io ho la funzione PHP ma come devo fare per fare andare la configurazione email.

**Comment by trinko** [comment]
> In che senso mi scusi io ho la funzione PHP ma come devo fare per fare andare la configurazione email.

Per configurare l'email, segui la procedura:
- come utente Amministratore, vaii alla pagina **SISTEMA > CONFIGURA EMAIL**
- nella pagina scegli come **"tipo di server per le email"** l'opzione **"Usa server locale tramite PHP"**
- a questo punto inserisci una email esistente come indirizzo a cui spedire una mail di prova
Confermando verrà spedita l'email.

ATTENZIONE: devono essere configurati correttamente i dati dell'istituto (pagina **SCUOLA > ISTITUTO**) con particolare riferimento all' **"Indirizzo email del mittente delle notifiche inviate dal registro"**

**Comment by mpignatelli** [comment]
> > In che senso mi scusi io ho la funzione PHP ma come devo fare per fare andare la configurazione email.
> 
> Per configurare l'email, segui la procedura:
> 
> * come utente Amministratore, vaii alla pagina **SISTEMA > CONFIGURA EMAIL**
> * nella pagina scegli come **"tipo di server per le email"** l'opzione **"Usa server locale tramite PHP"**
> * a questo punto inserisci una email esistente come indirizzo a cui spedire una mail di prova 
>   Confermando verrà spedita l'email.
> 
> ATTENZIONE: devono essere configurati correttamente i dati dell'istituto (pagina **SCUOLA > ISTITUTO** ) con particolare riferimento all' **"Indirizzo email del mittente delle notifiche invia dal registro"**

Quando vado su configurazione email mi dice errore

**Comment by mpignatelli** [comment]
> > In che senso mi scusi io ho la funzione PHP ma come devo fare per fare andare la configurazione email.
> 
> Per configurare l'email, segui la procedura:
> 
> * come utente Amministratore, vaii alla pagina **SISTEMA > CONFIGURA EMAIL**
> * nella pagina scegli come **"tipo di server per le email"** l'opzione **"Usa server locale tramite PHP"**
> * a questo punto inserisci una email esistente come indirizzo a cui spedire una mail di prova
>   Confermando verrà spedita l'email.
> 
> ATTENZIONE: devono essere configurati correttamente i dati dell'istituto (pagina **SCUOLA > ISTITUTO**) con particolare riferimento all' **"Indirizzo email del mittente delle notifiche inviate dal registro"**
Ti invio il link di altrevista: 

https://s578.altervista.org/lf.pl?sid=62ce423e99dcf4b77758d8a636970da3
Password:t3Akjx4fsytC fammi sapere

**Comment by trinko** [comment]
Non scrivere in pubblico le credenziali della tua installazione!
In ogni caso, mi  spiace, ma non svolgo un servizio di assistenza. 
Posso solo aiutarti a risolvere il problema.

**Comment by trinko** [comment]
Dal log che avevi caricato in precedenza sembrava che avessi tentato l'invio della mail di prova. Ma se non riesci a vedere la pagina di configurazione dell'email ritengo che, come per l'altro problema segnalato, il registro non sia stato configurato completamente o che l'installazione non sia stata svolta completamente.
Consiglio di:
- assicurarsi di aver svolto l'installazione completamente senza errori; se sono stati mostrati errori durante l'installazione iniziale o l'aggiornamento è probabile che qualche parte non sia stata installata.
- assicurarsi di aver svolto la configurazione iniziale: vedi [la documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html)

**Comment by mpignatelli** [comment]
> Dal log che avevi caricato in precedenza sembrava che avessi tentato l'invio della mail di prova. Ma se non riesci a vedere la pagina di configurazione dell'email ritengo che, come per l'altro problema segnalato, il registro non sia stato configurato completamente o che l'installazione non sia stata svolta completamente. Consiglio di:
> 
> * assicurarsi di aver svolto l'installazione completamente senza errori; se sono stati mostrati errori durante l'installazione iniziale o l'aggiornamento è probabile che qualche parte non sia stata installata.
> * assicurarsi di aver svolto la configurazione iniziale: vedere [la documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html)

Come faccio per vedere se l'istallazione non si stata fatta correttamente. Dove devo andare

**Comment by mpignatelli** [comment]
> Dal log che avevi caricato in precedenza sembrava che avessi tentato l'invio della mail di prova. Ma se non riesci a vedere la pagina di configurazione dell'email ritengo che, come per l'altro problema segnalato, il registro non sia stato configurato completamente o che l'installazione non sia stata svolta completamente. Consiglio di:
> 
> * assicurarsi di aver svolto l'installazione completamente senza errori; se sono stati mostrati errori durante l'installazione iniziale o l'aggiornamento è probabile che qualche parte non sia stata installata.
> * assicurarsi di aver svolto la configurazione iniziale: vedere [la documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html)

Mi puoi reinstallare giuaschool?? Poi se non va non fa niente.

**Comment by mpignatelli** [comment]
> Non scrivere in pubblico le credenziali della tua installazione! In ogni caso, mi spiace, ma non svolgo un servizio di assistenza. Posso solo aiutarti a risolvere il problema.

Se mi puoi inviare un video su come risolvere??

**Comment by trinko** [comment]
> Come faccio per vedere se l'istallazione non si stata fatta correttamente. Dove devo andare

Se non è stato mostrato un messaggio di errore o una pagina bianca durante i vari passi della procedura di installazione, allora dovrebbe essere a posto. Può però capitare di non avere caricato tutti i file sul server: se usi FileZilla per caricare i file, ti mostra eventuali errori di caricamento.

Ma prima di reinstallare, devi fare i controlli che ti avevo già detto:  **assicurati di aver svolto la configurazione iniziale: vedi [la documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html)**

Se dopo aver inserito tutti i parametri necessari mostra gli stessi errori, allora cred o sia necessario reinstallare.

**Comment by mpignatelli** [comment]
> > Come faccio per vedere se l'istallazione non si è stata fatta correttamente. Dove devo andare
> 
> Se non è stato mostrato un messaggio di errore o una pagina bianca durante i vari passi della procedura di installazione, allora dovrebbe essere a posto. Può però capitare di non avere caricato tutti i file sul server: se usi FileZilla per caricare i file, ti mostra eventuali errori di caricamento.
> 
> Ma prima di reinstallare, devi fare i controlli che ti avevo già detto: **assicurazioni di aver svolto la configurazione iniziale: vedi [la documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html)**
> 
> Se dopo aver inserito tutti i parametri necessari mostra gli stessi errori, allora cred o sia necessario reinstallare.

Mi puoi aiutare con l'istallazione contattami tramite email: michelina.pignatelli1983@gmail.com

**Comment by trinko** [comment]
> Mi puoi aiutare con l'istallazione contattami tramite email

Non eseguo installazioni, mi spiace. 
La procedura di installazione è abbastanza semplice: [installazione](https://iisgiua.github.io/giuaschool-docs/install-zip.html)
Se incontri un problema nella procedura descritta, scrivi cosa hai fatto e il problema incontrato e cerchiamo di risolvere.

**Comment by mpignatelli** [comment]
> > Mi puoi aiutare con l'istallazione contattami tramite email
> 
> Non eseguo installazioni, mi spiace. La procedura di installazione è abbastanza semplice: [installazione](https://iisgiua.github.io/giuaschool-docs/install-zip.html) Se incontri un problema nella procedura descritta, scrivi cosa hai fatto e il problema incontrato e cerchiamo di risolvere.

Mi puoi almeno indicare i passaggi. Io lo devo installare sul sito Altrevista. Ho capito che devo scaricare il file zip di giuaschool poi

**Comment by trinko** [comment]
- Scarica il file zip e decomprimilo sul tuo computer
- usa un programma come FileZilla ([scaricalo da qui se non ce l'hai](https://filezilla-project.org/download.php?platform=win64) )
- FileZilla ti permette di caricare i file sul tuo spazio Altervista, se non lo conosci: [tutorial FileZilla](https://www.youtube.com/watch?v=8kOMTK3XOp8)
- a questo punto devi connetterti con FileZilla al tuo spazio altervista, utilizzando le credenziali FTP che ti hanno dato loro 
- i file del tuo spazio Altervista appariranno nel riquadro SITO REMOTO;
- imposta la cartella con i file estratti dallo ZIP di giuaschool nel riquadro SITO LOCALE
- effettua il trasferimento di tutti i file dal sito LOCALE al sito REMOTO (richiederà un po' di tempo, sono tanti file)
- controlla alla fine se ci sono stati errori: in tal caso ricarica solo i file indicati come errati
- quando tutto è stato caricato puoi eseguire la procedura di installazione andando all'indirizzo:
   **http://nome_sito_altervista/public/install/app.php**
- esegui la procedura passo-passo, in caso di errori o pagina bianca, manda una segnalazione

**Comment by mpignatelli** [comment]
Ho risolto. Grazie mille
