### ISSUE TITLE
PROBLEMA INVIO EMAIL DI CONFERMA

### ISSUE THREAD

**Issue by GIANLUCA2509** [iisgiua/giuaschool#563]
**Descrivi il problema**
Buongiorno , quando configuro l'email di conferma , dice che e stata inviata nella mia casella postale , ma non arriva ne in spam ne in posta normale

**Indica come riprodurre l'errore**
Configura email - invia email di conferma

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Se non viene mostrato nessun errore, quasi sicuramente la mail è stata bloccata dal tuo servizio di hosting.

In particolare, se stati usando Altervista, l'unica modo per inviare l'email è configurando l'opzione **Usa server locale tramite PHP** che trovi nella pagina di configuraizone dell'email.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
