### ISSUE TITLE
Problema scrutinio giudizio sospeso

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#564]
Buongiorno,
Ho un problema con gli scrutini per gli alunni con giudizio sospeso: anche se per questi stessi alunni risulta la dicitura GIUDIZIO SOSPESO nella pagella, non appaiono nella pagina per effettuare lo scrutinio per giudizio sospeso.
A cosa può essere dovuto?
Grazie.

**Comment by trinko** [comment]
Forse non è stato configurato il periodo in modo corretto alla pagina **Scuola > Scrutini**
In particolare, i vari periodi (primo quadrimestre/trimestre, secondo quadrimestre, esame giudizio sospeso) devono avere date di inizio coerenti (una successiva all'altra) e precedenti la data odierna.

**Comment by Lucaccc** [comment]
> Forse non è stato configurato il periodo in modo corretto alla pagina **Scuola > Scrutini** In particolare, i vari periodi (primo quadrimestre/trimestre, secondo quadrimestre, esame giudizio sospeso) devono avere date di inizio coerenti (una successiva all'altra) e precedenti la data odierna.

Sono configurati correttamente e se provo a effettuare lo scrutinio la pagina compare, ma ha la dicitura "Non sono presenti alunni con giudizio sospeso".
E' come se non leggesse gli alunni con giudizio sospeso..
Come posso fare?

**Comment by Lucaccc** [comment]
> Puoi verificarlo eseguendo il seguente comando, utilizzando PHPmyAdmin e la finestra SQL:
> 
> ```
> SELECT *
> FROM gs_scrutinio s, gs_classe c
> WHERE s.classe_id=c.id AND s.periodo='F' AND s.stato='C'
> AND c.anno=1 AND c.sezione='A';
> ```
> 
> Modifica anno e sezione per la classe desiderata. Dovresti visualizzare una riga con i dati dello scrutinio finale.

Riesco a visualizzarla correttamente la riga; quindi lo scrutinio è stato eseguito correttamente...

**Comment by trinko** [comment]
Ok. Verifica ora la presenza degli alunni con giudizio sospeso, usando il seguente comando SQL:
```
SELECT a.id,a.nome,a.cognome
FROM gs_esito e, gs_scrutinio s, gs_utente a, gs_classe c
WHERE e.scrutinio_id=s.id AND e.alunno_id=a.id
AND e.esito='S' AND s.periodo='F' AND s.classe_id=c.id
AND c.anno=1 AND c.sezione='A';
```
Come prima, modifica anno e sezione per la classe desiderata. Dovresti visualizzare gli alunni con giudizio sospeso.

**Comment by Lucaccc** [comment]
> Ok. Verifica ora la presenza degli alunni con giudizio sospeso, usando il seguente comando SQL:
> 
> ```
> SELECT a.id,a.nome,a.cognome
> FROM gs_esito e, gs_scrutinio s, gs_utente a, gs_classe c
> WHERE e.scrutinio_id=s.id AND e.alunno_id=a.id
> AND e.esito='S' AND s.periodo='F' AND s.classe_id=c.id
> AND c.anno=1 AND c.sezione='A';
> ```
> 
> Come prima, modifica anno e sezione per la classe desiderata. Dovresti visualizzare gli alunni con giudizio sospeso.

Li visualizzo correttamente (vedo ID, nome e cognome).

**Comment by trinko** [comment]
Strano. 
Stai utilizzando l'ultima versione del registro, la 1.5.5?  O hai effettuato qualche modifica sul template **templates/coordinatore/scrutinio_G_N.html.twig**? 

Oppure, non è che nella pagina **SCUOLA > SCRUTINI** hai impostato anche i periodi **"Sessione supplettiva"** o **"Scrutini rinviati"**?

**Comment by Lucaccc** [comment]
> Strano. Stai utilizzando l'ultima versione del registro, la 1.5.5? O hai effettuato qualche modifica sul template **templates/coordinatore/scrutinio_G_N.html.twig**?
> 
> Oppure, non è che nella pagina **SCUOLA > SCRUTINI** hai impostato anche i periodi **"Sessione supplettiva"** o **"Scrutini rinviati"**?

Si, sto utilizzando l'ultima versione.
Non ho apportato modifiche al template indicato.
Per quanto riguarda i periodi da lei indicati, io non li avevo impostati, ma mi sono reso conto che sono presenti anche lì delle date impostate, diverse comunque da quelle per lo scrutinio per giudizio sospeso.
Ho provato a eliminarle ma mi dice che il campo è obbligatorio..Come posso fare per rimuoverle? Crede sia questo il problema?
Grazie.

**Comment by trinko** [comment]
E' probabile che sia quello il problema: inserisci delle date future (es. 1 gennaio 2024) in modo che non siano considerati quei periodi.

**Comment by Lucaccc** [comment]
> E' probabile che sia quello il problema: inserisci delle date future (es. 1 gennaio 2024) in modo che non siano considerati quei periodi.

Ora funziona correttamente.
Grazie mille per l'assistenza.
