### ISSUE TITLE
Problema passaggio al nuovo a.s.

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#565]
Buongiorno, 
stavo provvedendo al passaggio al nuovo anno scolastico...ho archiviato i file ed effettuato il backup dei dati; ho, quindi, posto il registro in manutenzione ed effettuato il logout degli utenti.
Al passaggio di seguito indicato il registro restituisce errore 500.. come mai?

"Verranno ora effettuate le seguenti operazioni:
* recupero degli esiti degli scrutini;
* passaggio di classe degli alunni promossi."

Di seguito il log errori:
[2023-08-23_15-42.log](https://github.com/iisgiua/giuaschool/files/12419924/2023-08-23_15-42.log)

**Comment by trinko** [comment]
Sembra che ci sia un problema sui dati presenti. L'errore è dovuto al fatto che si cerca di inserire due volte l'esito di uno stesso alunno nella tabella che conserva i voti e gli esiti del precedente anno scolastico. Puoi provare il comando SQL:
```
SELECT * FROM gs_utente WHERE id=244;
```

Devo controllare meglio per capire se c'è un errore nella procedura.

**Comment by trinko** [comment]
Mi sembra che la procedura sia corretta, per cui ci devono essere dei dati incongruenti nel database.
Con il seguente comando puoi controllare l'esito inserito inserito in tabella per l'alunno:
```
SELECT * FROM gs_storico_esito WHERE alunno_id=244;
```
Controlla che:
- l'esito sia corretto (A= ammesso, N=non ammesso, S=sospeso, L=non ammesso per limite assenze, E=anno all'estero)
- il periodo sia corretto (F=scrutinio finale, G=giudizio sospeso, R= sessione supplettiva del giudizio sospeso).

**Comment by Lucaccc** [comment]
> SELECT * FROM gs_utente WHERE id=244;

Vedo questo..dovrebbe essere corretto, o sbaglio?
![cattura php](https://github.com/iisgiua/giuaschool/assets/94230686/ffc8f17e-64ad-44c8-91ce-f86039869fd4)

**Comment by trinko** [comment]
Ok, l'alunno risulta promosso allo scrutinio finale. Quindi non ci devono essere altri esiti presenti, controlla con il comando seguente:
```
SELECT s.periodo,e.*
FROM gs_esito e, gs_scrutinio s
WHERE e.scrutinio_id=s.id AND e.alunno_id=244;
```
Dovrebbe riportare una sola riga con il periodo F (finale) e l'esito indicato in precedenza.

**Comment by Lucaccc** [comment]
> Ok, l'alunno risulta promosso allo scrutinio finale. Quindi non ci devono essere altri esiti presenti, controlla con il comando seguente:
> 
> ```
> SELECT s.periodo,e.*
> FROM gs_esito e, gs_scrutinio s
> WHERE e.scrutinio_id=s.id AND e.alunno_id=244;
> ```
> 
> Dovrebbe riportare una sola riga con il periodo F (finale) e l'esito indicato in precedenza.

Oltre ad F mi appare anche una riga con il periodo G.

**Comment by trinko** [comment]
No, controlla la colonna degli esiti: dovrebbe essere **S** (sospeso) per il periodo F e **A** (promosso) per il periodo G.
Se non è così ci sono dati incongruenti nel database.

**Comment by trinko** [comment]
In ogni caso penso che siano stati introdotti, in qualche modo, dati erronei negli scrutini. 
Comunque, se il problema riguarda solo quell'utente puoi evitare di puoi saltare il suo passaggio all'anno successivo e trasferire tutto il resto. 
Per farlo, identifca prima l'alunno come detto in precedenza ([vedi messaggio](https://github.com/iisgiua/giuaschool/issues/565#issuecomment-1690756862) ) .
Poi vai nella gestione alunni e disabilita l'utente relativo all'alunno.
A questo punto puoi riprovare la procedura di passaggio d'anno ripartendo dall'inizio.

**Comment by Lucaccc** [comment]
> In ogni caso penso che siano stati introdotti, in qualche modo, dati erronei negli scrutini. Comunque, se il problema riguarda solo quell'utente puoi saltare il suo passaggio all'anno successivo e trasferire tutto il resto. Per farlo, identifca prima l'alunno come detto in precedenza ([vedi messaggio](https://github.com/iisgiua/giuaschool/issues/565#issuecomment-1690756862) ) . Poi vai nella gestione alunni e disabilita l'utente relativo all'alunno. A questo punto puoi riprovare la procedura di passaggio d'anno ripartendo dall'inizio.

Ho provato ma continua a darmi lo stesso errore..

**Comment by trinko** [comment]
C'è un problema dovuto alla versione del database utilizzata da Altervista.
Scarica il file seguente e decomprimilo.
Quindi caricalo sul server nella cartella **src/Controller** sovrascrivendo quello esistente. 
Poi riprova a fare la procedura dall'inizio.

[SistemaController.php.zip](https://github.com/iisgiua/giuaschool/files/12445114/SistemaController.php.zip)

**Comment by Lucaccc** [comment]
> 

Continua a darmi lo stesso errore, anche con il file sostituito.

**Comment by trinko** [comment]
Devi prima svuotare la cache.

**Comment by trinko** [comment]
Riprova con caricando questo nuovo file, sempre in **src/Controller**. Poi svuota la cache e rifai la procedura di passaggio d'anno.


[SistemaController.php.zip](https://github.com/iisgiua/giuaschool/files/12445835/SistemaController.php.zip)

**Comment by Lucaccc** [comment]
> Riprova con caricando questo nuovo file, sempre in **src/Controller**. Poi svuota la cache e rifai la procedura di passaggio d'anno.
> 
> [SistemaController.php.zip](https://github.com/iisgiua/giuaschool/files/12445835/SistemaController.php.zip)

Abbiamo risolto il primo problema (quindi, ho superato lo step 2), ma ora se ne verifica un altro al terzo step.
Log errori:
[2023-08-27_19-41.log](https://github.com/iisgiua/giuaschool/files/12448511/2023-08-27_19-41.log)

**Comment by trinko** [comment]
L'errore è dovuto al fatto che non è presente il file di almeno una circolare: quando si effettua il passaggio d'anno tutti i file delle circolari (e relativi allegati) devono essere presenti nella cartella in cui sono stati caricati: **FILES/upload/circolari** 
In questo caso non è così.

Se vuoi testare la procedura devi assicurarti che tutti i documenti caricati siano presenti nelle relative cartelle.
Inoltre tieni presente che, superato il passo 2, per riprovare la procedura devi ricaricare il backup del database, perché il passo 2 svuota le tabelle degli esiti una volta che li ha trasferiti nello storico (che conserva i dati dell'anno precedente).

**Comment by Lucaccc** [comment]
> L'errore è dovuto al fatto che non è presente il file di almeno una circolare: quando si effettua il passaggio d'anno tutti i file delle circolari (e relativi allegati) devono essere presenti nella cartella in cui sono stati caricati: **FILES/upload/circolari** In questo caso non è così.
> 
> Se vuoi testare la procedura devi assicurarti che tutti i documenti caricati siano presenti nelle relative cartelle. Inoltre tieni presente che, superato il passo 2, per riprovare la procedura devi ricaricare il backup del database, perché il passo 2 svuota le tabelle degli esiti una volta che li ha trasferiti nello storico (che conserva i dati dell'anno precedente).

Come è possibile che non sono presenti le circolari...io dal registro le visualizzo correttamente, quindi non capisco come facciano a non esserci..

**Comment by trinko** [comment]
Potrebbe essere un problema di permessi sui file o sulle cartelle, ma se non hai fatto modifiche specifiche sui permessi, non dovrebbe verificarsi.

La circolare che genera l'errore è **FILES/upload/circolari/318956be3f0712c426bac4ae7ef01350-364.pdf.pdf**
Controlla anche se è stata creata la cartella **FILES/upload/circolari/2022/**: in questa cartella la procedura sposta le circolari dello scorso anno scolastico.

**Comment by trinko** [comment]
La numerazione -1 potrebbe creare problemi, ma non penso sia quello che generi l'errore.
Hai verificato se il file indicato esiste?
Se ti serve sapere la circolare collegata al file che crea problemi, puoi eseguire il comando SQL:
```
SELECT numero,data FROM 
gs_circolare 
WHERE documento='318956be3f0712c426bac4ae7ef01350-364.pdf.pdf' OR allegati LIKE '318956be3f0712c426bac4ae7ef01350-364.pdf.pdf';
```

Individuata la circolare, potresti anche provare a rimuoverla, per verificare che quel file sia l'unico problema.

**Comment by Lucaccc** [comment]
> La numerazione -1 potrebbe creare problemi, ma non penso sia quello che generi l'errore. Hai verificato se il file indicato esiste? Se ti serve sapere la circolare collegata al file che crea problemi, puoi eseguire il comando SQL:
> 
> ```
> SELECT numero,data FROM 
> gs_circolare 
> WHERE documento='318956be3f0712c426bac4ae7ef01350-364.pdf.pdf' OR allegati LIKE '%318956be3f0712c426bac4ae7ef01350-364.pdf.pdf%';
> ```
> 
> Individuata la circolare, potresti anche provare a rimuoverla, per verificare che quel file sia l'unico problema.

Ho rimosso la circolare in questione; non so per quale strana ragione, ma non si apriva più il documento relativo.
Sono riuscito a portare a termina la procedura.
Grazie mille per la consueta disponibilità.
