### ISSUE TITLE
Problema grave : il registro ha inserito delle valutazioni autonomamente.

### ISSUE THREAD

**Issue by gianlucaaiello56** [iisgiua/giuaschool#589]
**Descrivi il problema**
Il registro in una classe ha inserito 100 voti per alunno per una singola materia. Il docente ,infatti, non sapeva nulla di ciò che è accaduto.

**Indica come riprodurre l'errore**
E' capitato solo una volta, ma è grave.

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Ritengo estremamente improbabile, se non del tutto impossibile, che possa succedere una cosa del genere "autonomamente".
Il voto viene inserito esclusivamente quando si esegue la procedura di inserimento della valutazione su un singolo alunno o sull'intera classe. La valutazione viene inserita in seguito all'invio dell'apposita pagina di inserimento e questo deve essere fatto necessariamente da un utente connesso.

Quello che è probabilmente successo è:
**Ipotesi 1**- il voto può essere replicato più volte se, dopo l'invio di un voto, viene ricaricata la pagina dal browser utilizzato; questo succede talvolta a causa della lentezza della connessione, che fa sì che il docente prema più volte il pulsante di invio dei dati...   Mi pare però poco probabile che venga inviata 100 volte di seguito...
**Ipotesi 2**: poiché mi pare di capire che è sempre la stessa materia e docente, la cosa più probabile è che ci sia stato un furto della password dell'utente.

Si può comunque risalire a data/ora dell'inserimento e indirizzo IP. Dietro denuncia alla Polizia Postale per furto di identità, da questi dati si può risalire all'autore dell'inserimento dei voti.

Per estrarre questi dati, devi aprire PHPMyAdmin sul tuo servizio di hosting ed eseguire il comando SQL seguente:
```
SELECT * FROM gs_log 
WHERE categoria='VOTI' AND azione IN ('Crea voto', 'Voti della classe')
AND username='USERNAME' AND creato >= '2023-11-15 00:00';
```
**sostituendo USERNAME** con la username del docente in questione ed eventualmente modificando la data di inizio del controllo, memorizzata nel campo _creato_ (io l'ho impostata al 15 novembre).

Nei dati visualizzati, controllare il campo _creato_ per la data/ora di inserimento dei voti, in modo da individuare quelli non inseriti dal docente, quindi si può controllare l'indirizzo IP.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
