### ISSUE TITLE
doppia materia presente nel tabellone delle proposte di voto del primo trimestre

### ISSUE THREAD

**Issue by gmontalbano5ct** [iisgiua/giuaschool#591]
si allega la foto del tabellone, è presente doppiamente la materia educazione civica, pur avendo inserito le proposte non spuntano nel tabellone.
![Screenshot 2023-11-27 195701](https://github.com/iisgiua/giuaschool/assets/93207960/4a6dc148-325e-4e40-9b8b-5d50294ddd0b)

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
![1](https://github.com/iisgiua/giuaschool/assets/93207960/2f0c7b93-f0d1-4f31-88fe-2f6c6f3ce86f)

**Comment by gmontalbano5ct** [comment]
@robertopadovesi come vedi non ci sono due educazione civica

**Comment by trinko** [comment]
Stai facendo lo scrutinio del primo quadrimestre? 
Hai eseguito tutti gli aggiornamenti  disponibili?

**Comment by gmontalbano5ct** [comment]
Si

**Comment by gmontalbano5ct** [comment]
Primo trimestre

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
@trinko come risolvo la problematica?

**Comment by manuelbarberi** [comment]
Ho riscontrato lo stesso errore e, guardando nel database, ho trovato l'errore... va solamente corretto nel codice: la materia educazione civica nonostante si attribuisca come ed civica nel database esce come NORMALE....

**Comment by gmontalbano5ct** [comment]
Ora provo e ti faccio sapere grazie

**Comment by gmontalbano5ct** [comment]
![2](https://github.com/iisgiua/giuaschool/assets/93207960/bda21206-f57a-4864-94e8-6c272ef208a2)

**Comment by gmontalbano5ct** [comment]
@manuelbarberi come puoi vedere spunta come educazione civica anche nel database ma non capisco cos'altro potrebbe essere

**Comment by gmontalbano5ct** [comment]
@trinko lei mi sa aiutare?

**Comment by trinko** [comment]
Ho riprodotto l'errore, c'è un errore nela procedura di visualizzazione.
Ma devo ancora analizzare il codice.

**Comment by gmontalbano5ct** [comment]
Ok grazie

**Comment by trinko** [comment]
Mancava il template aggiornato della pagina delle proposte di voto.
Ora ho reso disponibile un aggiornamento che dovrebbe sistemare le cose.

**NB:** se dopo aver effettuato l'aggiornamento non si visualizza correttamente il registro, cancella tutto il contenuto della cartella **var/cache/prod**.

**Comment by gmontalbano5ct** [comment]
Tutto funziona al momento grazie mille per la sua disponibilità

**Comment by gmontalbano5ct** [comment]
stesso problema per il secondo trimestre @trinko

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Estrai il file allegato e caricalo nella cartella: **templates/coordinatore/scrutinio_S_N.html.twig**

Svuota la cache. 
Dovrebbe risolvere il problema.

[scrutinio_S_N.html.twig.zip](https://github.com/iisgiua/giuaschool/files/13641662/scrutinio_S_N.html.twig.zip)

**Comment by gmontalbano5ct** [comment]
salve, ho fatto come ha detto lei ma non ha risolto il problema @trinko

**Comment by gmontalbano5ct** [comment]
risolto il problema con l'aggiornamento grazie
