### ISSUE TITLE
Errore nella visione degli Alunni

### ISSUE THREAD

**Issue by ICGalvaniOpromolla** [iisgiua/giuaschool#593]
Buonasera,
sono il Referente del Dirigente Scolastico è volevo segnalarle un problema al Registro Elettronico aggiornato all'ultima versione.
il problema si svolge appena un Docente entra nella sua Classe, è per svolgere l'appello non riesce poichè si verifica l'errore è porta ad una nuova schermata con scritto: Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
non sappiamo come risolvere, è crediamo che ci potrebbe aiutare, Grazie 
"le lascio il Log dell'errore in allegato"
[2023-12-01_21-10.log](https://github.com/iisgiua/giuaschool/files/13531617/2023-12-01_21-10.log)

**Comment by trinko** [comment]
L'errore è dovuto ad una errata configurazione dei parametri per il periodo in corso.
In pratica la data della lezione non è compresa in nessun periodo (primo/secondo trimestre/quadrimestre).

Devi andare, come utente amministratore, alla pagina **SISTEMA > PARAMETRI**: in particolare imposta controlla i seguenti parametri della categoria SCUOLA:
- anno_inizio
- anno_fine
- periodo1_fine
- periodo2_fine

**Comment by Davide031** [comment]
è successo pure a me poi ho fatto come ha detto @trinko che non smetterò mai di ringraziarlo ed ho sistemato

**Comment by ICGalvaniOpromolla** [comment]
@trinko volevo informarla che ho inviato una Issues in GiuaReg, per cortesia può rispondermi?
Grazie

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
