### ISSUE TITLE
ERRORE GRAVE NELL'AGGIORNAMENTO DEL REGISTRO

### ISSUE THREAD

**Issue by gianlucaaiello56** [iisgiua/giuaschool#598]
**Descrivi il problema**
Il registro ,nella sezione aggiornamenti, richiedeva l'installazione di un aggiornamento. Dopo l'installazione la sezione ADMIN ha continuato a funzionare ma l'accesso ai docenti non funziona !
Come posso risolve ?

**Indica come riprodurre l'errore**
Accedendo in un account docente.

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

[2023-12-09_11-00.log](https://github.com/iisgiua/giuaschool/files/13623802/2023-12-09_11-00.log)

**Comment by Davide031** [comment]
Ciao Gianluca per risolvere hai fatto un backup?

**Comment by gianlucaaiello56** [comment]
Ho fatto tutte la manutenzioni possibili ma ugualmente non funziona

**Comment by gianlucaaiello56** [comment]
Quando lunedì sarà rilasciata la versione 1.5.6. risolverà il problema ?

**Comment by Lucaccc** [comment]
> **Descrivi il problema** Il registro ,nella sezione aggiornamenti, richiedeva l'installazione di un aggiornamento. Dopo l'installazione la sezione ADMIN ha continuato a funzionare ma l'accesso ai docenti non funziona ! Come posso risolve ?
> 
> **Indica come riprodurre l'errore** Accedendo in un account docente.
> 
> **File di LOG** Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
> 
> [2023-12-09_11-00.log](https://github.com/iisgiua/giuaschool/files/13623802/2023-12-09_11-00.log)

Credo sia sufficiente che ripristini il backup del sito e del database a prima che installassi l'aggiornamento (sempre che tu l'abbia fatto), così tornerà come prima. Qualora non lo avessi fatto, il tuo hosting dovrebbe farne qualcuno in automatico, ma potrebbe accadere che sia di diverso tempo fa.

**Comment by gianlucaaiello56** [comment]
> > **Descrivi il problema** Il registro ,nella sezione aggiornamenti, richiedeva l'installazione di un aggiornamento. Dopo l'installazione la sezione ADMIN ha continuato a funzionare ma l'accesso ai docenti non funziona ! Come posso risolve ?
> > **Indica come riprodurre l'errore** Accedendo in un account docente.
> > **File di LOG** Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
> > [2023-12-09_11-00.log](https://github.com/iisgiua/giuaschool/files/13623802/2023-12-09_11-00.log)
> 
> Credo sia sufficiente che ripristini il backup del sito e del database a prima che installassi l'aggiornamento (sempre che tu l'abbia fatto), così tornerà come prima. Qualora non lo avessi fatto, il tuo hosting dovrebbe farne qualcuno in automatico, ma potrebbe accadere che sia di diverso tempo fa.

purtroppo anche effettuando il backup e svuota cache non funziona. Per caso ,da quanto ho capito, con la versione 1.5.6. che sarà rilasciata domani ( sempre da quanto ho letto su github nell'annuncio di Antonello Dessì )  potrebbe risolvere il problema ?

**Comment by trinko** [comment]
Anzi tutto ti consiglio di rivedere con attenzione la procedura che usi per il backup e ripristino (del database e dei file). Se esegui correttamente queste procedure hai la certezza di ritornare alla situazione precedente, senza alcun rischio.

Per quanto riguarda l'errore, l'aggiornamento non ha eseguito le necessarie modifiche alle tabelle, per questo in alcune pagine si blocca tutto. 
L'aggiornamento alla 1.5.6 riesegue la modifica delle tabelle, per cui, se non si presentano errori, sarà ripristinata la situazione corretta.

**Comment by trinko** [comment]
Si, installando la nuova versione si dovrebbe risolvere il problema.

**Comment by gianlucaaiello56** [comment]
Buongiorno @trinko , la ringrazio. Ho risolto il problema !

**Comment by gianlucaaiello56** [comment]
ed inoltre, complimenti per la nuova versione.. eccellente !!!

**Comment by trinko** [comment]
Grazie.
Allora chiudo la segnalazione.
