### ISSUE TITLE
Aggiornamento non riuscito errore 403 

### ISSUE THREAD

**Issue by tommasiangelo01** [iisgiua/giuaschool#602]
@trinko Buongiorno non riuscendo ad installare il registro direttamente dal registro stesso ho eseguito la procedura indicatami da voi per gli aggiornamenti successivi ,ovvero la seguente che adesso riporto tra le virgolette  

"E' un problema del server che non permette l'esecuzione di una procedura per un tempo prolungato.

Devi fare l'aggiornamento manuale: anzi tutto carica il file della versione 1.5.4 sul server e decomprimilo andando a sovrascrivere i file esistenti. In alternativa, decomprimi sul tuo computer il file della versione 1.5.4 e poi carica tutti i file con Filezilla. Questo secondo metodo è più lento, ma da' maggiori garanzie che non ci siano file mancanti.

Fatto questo, crea sulla cartella principale, il file ".gs-updating" che deve contenere le seguenti 3 righe:

version:1.5.4
build:0
token:codice
Per il token usa un codice a piacere.

A questo punto termina l'installazione andando alla pagina:
nome_sito/install/update.php?token=codice&step=2"

ma una volta che carico il link per lanciare l'aggiornamento ricevo il seguente errore che allego 

<img width="1309" alt="Screenshot 2023-12-11 alle 15 40 32" src="https://github.com/iisgiua/giuaschool/assets/69850072/6dce5038-d766-4cfa-b24b-6040c80e3acb">

**Comment by tommasiangelo01** [comment]
Mi potete urgentemente aiutare ?Grazie

**Comment by trinko** [comment]
Si, la procedura è giusta, ovviamente la versione da indicare è la 1.5.6
Credo che l'errore sia questo: nell'indirizzo devi probabilmente aggiungere _public_:
```
nome_sito/public/install/update.php?token=codice&step=2
```

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
