### ISSUE TITLE
ERRORE SCRUTINIO TRIMESTRE

### ISSUE THREAD

**Issue by gianluca3090** [iisgiua/giuaschool#611]
**Descrivi il problema**
Salve , durante la procedura di avviamento dello scrutinio del trimestre , dopo aver effettuato l'aggiornamento , accompare la scritta error 500

**Indica come riprodurre l'errore**
procedi con lo scrutinio-assenza docenti avanti -error 500

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
[2023-12-14_17-32.log](https://github.com/iisgiua/giuaschool/files/13675889/2023-12-14_17-32.log)

**Comment by trinko** [comment]
Il log riportato non contiene niente. 
Probabilmente non hai eseguito correttamente la procedura per l'estrazione del log:

   - come utente amministratore, andare alla pagina **Sistema > Manutenzione** e abilitare il debug;
   - eseguire la pagina che causa l'errore;
   - tornare alla pagina **Sistema > Manutenzione** e estrarre il log, indicando l'ora in cui si è generato l'errore;
   - scaricare il file di log e allegarlo al messaggio di segnalazione

**Comment by gianluca3090** [comment]
[Uploading 2023-12-16_16-09.log…]()

**Comment by gianluca3090** [comment]
[2023-12-16_16-09.log](https://github.com/iisgiua/giuaschool/files/13692948/2023-12-16_16-09.log)

**Comment by trinko** [comment]
Purtroppo anche questo log è come il precedente: non contiene i dati di navigazione alla pagina che mostra l'errore (scrutinio).

I casi sono due: o non hai attivato il DEBUG oppure quando estrai il log stai indicato un'ora diversa da quella in cui sei andato alla pagina dello scrutinio che genera l'errore.

**Comment by trinko** [comment]
Giusto per essere sicuri: dopo aver attivato il DEBUG, vai alla pagina HOME e poi torna su 
**Sistema > Manutenzione**
Vedi nella pagina il pulsante **DISATTIVA DEBUG**?

**Comment by trinko** [comment]
Il problema è risolto nella nuova versione 1.5.7
