### ISSUE TITLE
Malfunzionamento scrutinio trimestre

### ISSUE THREAD

**Issue by gianlucaaiello56** [iisgiua/giuaschool#612]
**Descrivi il problema**
Gent.mo sig. @trinko  le allego il file di errore .Quando clicco "avvia scrutinio" risulta 500 error.

**Indica come riprodurre l'errore**
Cliccare "apri scrutinio"

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
[2023-12-17_20-00.log](https://github.com/iisgiua/giuaschool/files/13697492/2023-12-17_20-00.log)

**Comment by trinko** [comment]
L'avevo detto nell' [annuncio della 1.5.6](https://github.com/iisgiua/giuaschool/discussions/600)
La gestione degli scrutini sarà sistemata a gennaio.

**Comment by gianlucaaiello56** [comment]
Va bene ,l'importante è che a gennaio sarà possibile svolgere gli scrutini.
