### ISSUE TITLE
Problema installazione

### ISSUE THREAD

**Issue by Karimio29** [iisgiua/giuaschool#613]
Salve. ho caricato i file d'installazione tramite programma ftp sull'hosting altervista, per verificare il funzionamento di giuaschool. Ma nel momento in vado per aprire il file d'installazione, mi appare il seguente errore:

**Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /membri/registroelettronicoluci/giuaschool-release-v1.5.6/src/Install/Updater.php on line 27**

Qualcuno potrebbe aiutarmi? Grazie mille.

**Comment by trinko** [comment]
Devi impostare l'uso del PHP versione 8.0
Lo devi fare dalle impostazioni di Altervista, sulla gestione PHP.

**Comment by Karimio29** [comment]
Grazie mille. Vi farò sapere non appena apporterò le modifiche tramite computer

**Comment by trinko** [comment]
Allora chiudo la segnlazione
