### ISSUE TITLE
errore dopo ultimo aggiornamento

### ISSUE THREAD

**Issue by gmontalbano5ct** [iisgiua/giuaschool#626]
appena vado da staff in scrutinio errore 500, stessa cosa dal lato genitore appena si va sulla pagella errore 500. @trinko  può aiutarmi grazie 
[2024-01-11_00-54.log](https://github.com/iisgiua/giuaschool/files/13895644/2024-01-11_00-54.log)

**Comment by trinko** [comment]
L'aggiornamento appena rilasciato dovrebbe risolvere il problema.

**Comment by gmontalbano5ct** [comment]
ok, il problema è stato risolto ma i genitori non riescono ad inserire la presa visione della pagella @trinko

**Comment by trinko** [comment]
La presa visione non va inserita. E' automatica, come si legge la pagina viene registrata la data e ora.

**Comment by trinko** [comment]
Il coordinatore può vedere la presa visione nella pagina SITUAZIONE, scegliendo il pulsante SCRUTINI dell'alunno desiderato.

**Comment by gmontalbano5ct** [comment]
I genitori hanno visionato la pagella ma non spunta la presa visione

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
a, ok grazie mille funziona tutto adesso
