### ISSUE TITLE
Errore visione nel nome del docente (lato genitore)

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#629]
Buongiorno, ho fatto l'ultimo aggiornamento e ho svuotato la cache, ma dal profilo genitore continua a non essere visualizzabile il nome del Docente che ha inserito la valutazione; da profilo Docente, invece, si visualizza correttamente.
A cosa può essere dovuto?
Grazie.

**Comment by trinko** [comment]
Il nome del docente dovrebbe comparire nel riquadro delle informazioni sulla valutazione, quando si clicca sul voto stesso.
Se compaiono le altre informazioni ma non il nome, penso sia stato modificato il template della pagina.

Quindi forse hai modificato il file **templates/ruolo_genitore/voti.html.twig** oppure è presente un altro template personalizzato in **PERSONAL/templates/ruolo_genitore/voti.html**

**Comment by Lucaccc** [comment]
Risolto. Era dovuto alla modifica del template.
