### ISSUE TITLE
Errore nell'importazione degli alunni

### ISSUE THREAD

**Issue by robertopadovesi** [iisgiua/giuaschool#630]
**Descrivi il problema**

Buongiorno. Oggi, mentre stavo importando degli alunni per le classi II, mi si è rilevato errore. Attualmente, mi ha importato i dati in II A, II B, II C. In II D niente. Chiedo aiuto a @trinko e ai suoi collaboratori, @bfabio, @zerai, @MatteoGheza.

**Indica come riprodurre l'errore**

Accedendo all'area di importazione degli alunni, sul registro elettronico, e importandoli con il file .csv (non diffusibile a causa dei criteri di privacy).

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

[2024-01-17_15-25.log](https://github.com/iisgiua/giuaschool/files/13964493/2024-01-17_15-25.log)

**Comment by zerai** [comment]
Il file di log da te inviato fa riferimento ad un errore di duplicazione..
Ci sono nominativi uguali.

**Comment by robertopadovesi** [comment]
Va bene, allora provo a reinserire con i nominativi del solo corso D e vi faccio sapere.

**Comment by robertopadovesi** [comment]
No, continua a darmi errore. @zerai

**Comment by robertopadovesi** [comment]
Provo a svuotare la cache? @zerai, @trinko

**Comment by robertopadovesi** [comment]
Buongiorno! Ho risolto il problema, alla fine dovevo modificare solo alcuni nominativi! Grazie mille e buona serata @zerai, sei stato veramente molto gentile! 😊

**Comment by robertopadovesi** [comment]
Buongiorno! Ho risolto il problema, si hai ragione! Alla fine dovevo modificare solo alcuni nominativi e ora ci sono riuscito! Grazie mille e buona serata @zerai, sei stato veramente molto gentile! 😊
