### ISSUE TITLE
Errore grave nel registro

### ISSUE THREAD

**Issue by trinko** [iisgiua/giuaschool#632]
### Discussed in https://github.com/iisgiua/giuaschool/discussions/631

<div type='discussions-op-text'>

<sup>Originally posted by **Davide031** January 18, 2024</sup>
Buonasera io dopo aver effettuato l'aggiornamento non riesco a firmare nn compare la scritta aggiungi e non posso mettere voti</div>

**Comment by trinko** [comment]
Se nella pagina del registro non compare nessun pulsante Aggiungi/Modifica è probabile che i parametri di configurazione dei periodi e dell'anno scolastico non siano stati impostati correttamente. Controllali dalla pagina **Sistema > Parametri**

L'errore sull'assenza è strano e il log non aiuta a capire il problema. Prova a svuotare la cache a mano, cancellando la cartella **var/cache/prod**

**Comment by trinko** [comment]
Riguardando il log, sono sicuro che anche il problema delle assenze è lo stesso.
Hai chiuso lo scrutinio della classe del primo trimestre? Se si, allora non puoi più modificare niente del registro di quella classe per quel periodo (le assenze sono riportate in pagella e non possono essere alterate dopo lo scrutinio).

Se dovesse essere necessario modificare dati del primo trimestre: devi riaprire lo scrutinio della classe, tornare indietro nei passaggi sino a prima dell'apertura dello scrutinio; a quel punto è possibile modificare i dati del registro. Poi si va a rieseguire l'apertura dello scrutinio e si va passo passo sino alla fine. I dati inseriti nello scrutinio non vengono alterati, ma le assenze vengono modificate nei documenti finali.

**Comment by Davide031** [comment]
grazie mille riguardando bene ho aggiustato tutto grazie mille
