### ISSUE TITLE
Errore nell'eseguimento dello Scrutinio

### ISSUE THREAD

**Issue by nicolatrentini** [iisgiua/giuaschool#635]
Accedendo nell'Alis di un docente coordinatore di una classe con voti scrutinali inseriti, il docente apre lo Scrutinio ma gli esce l'errore seguente: Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

cliccando Apri lo scrutinio esce l'erore 500

[2024-01-21_15-38.log](https://github.com/iisgiua/giuaschool/files/14001678/2024-01-21_15-38.log)

**Comment by Davide031** [comment]
idem a me dopo l'aggiornamento

**Comment by trinko** [comment]
Il log riportato non traccia le operazioni indicate, quindi non è di alcuna utilità.
E' necessario attivare il debug, poi eseguire le operazioni che riportano l'errore, quindi estrarre il log che comprende tali operazioni.

Per intenderci il log riportato è relativo all'esecuazione delle seguenti pagine:
- sistema/manutenzione
- sistema/manutenzione/log
Probabilmente si è indicato un orario errato per l'estrazione del log.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
