### ISSUE TITLE
Malfunzionamento generale del sistema

### ISSUE THREAD

**Issue by robertopadovesi** [iisgiua/giuaschool#636]
**Descrivi il problema**

Buongiorno. Oggi in giornata, dei professori e delle famiglie mi hanno segnalato che nelle pagine del registro, ci sono vari errori. Per esempio, alcune pagine su Giua (gestione colloqui, gestione coordinatore, scaricamento del programma, valutazioni) segnalano un errore interno, e non non sapremmo come risolvere. Sono entrato in alias, tramite l'account ammininistratore, in un profilo professore, un profilo genitore e un profilo studente, e in effetti, ci sono vari problemi. Chiedo gentilmente aiuto a @trinko e ai suoi collaboratori, @bfabio, @zerai, @MatteoGheza.

**Indica come riprodurre l'errore**

Nelle pagine generiche di Giua (gestione colloqui, gestione coordinatore, scaricamento del programma, valutazioni).

**Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)**

[2024-01-22_19-58.log](https://github.com/iisgiua/giuaschool/files/14014515/2024-01-22_19-58.log)

**Comment by trinko** [comment]
Sembra che il problema sia dovuto alla versione MySQL che stai usando: mi puoi confermare che è la 5.7?
Il tuo servizio di hosting ti permette di cambiare versione del database server?

**Comment by robertopadovesi** [comment]
Sono andato su _Gestione PHP_ e in effetti, dice che la mia versione è obsoleta.
![image](https://github.com/iisgiua/giuaschool/assets/146358960/1a8e99f5-4bb7-4477-95e5-757a6b115084)
Provo a cambiarla con la 8.3.

**Comment by robertopadovesi** [comment]
Ciao @trinko.
Cambiando la versione, mi da sempre errore.
Il problema è, secondo te, forse uno più grave?
Fammi sapere, attendo tue. Grazie!

**Comment by zerai** [comment]
@robertopadovesi 

> Sembra che il problema sia dovuto alla versione MySQL che stai usando: mi puoi confermare che è la 5.7?

La risposta di trinko non riguarda il parametro da te cambiato, ossia la versione PHP in uso sul tuo server.

Quello che puoi fare è verificare se effetivamente tu stia usando una versione "problematica/obsoleta" del server di database, così da poter confermare l'ipotesi di trinko sul tuo problema.

Nel tuo panello aruba cerca la voce'database' o mysql, lì dovrebbe essere riportata la versione in uso sul tuo server.

**Comment by robertopadovesi** [comment]
Ciao @zerai! @trinko.
Allora, poco fa ho letto la tua risposta e sono andato nella pagina del database. Non so se ho sbagliato, ma mi spunta questo.
![image](https://github.com/iisgiua/giuaschool/assets/146358960/bc8e0e06-2731-4848-8fc5-436944aa2286)
Attendo vostre. Grazie mille dell'aiuto!

**Comment by zerai** [comment]
Da questo screenshot non è possibile capire la versione in uso
Clicca sul pulsante 'vai a PHPMYADMIN'  e cerca la voce 'server' o 'impostazioni' (non ricordo la dicitura esatta)
li troverai il numero di versione.

PS. non modificare/salvare niente mentre sei in phpmyadmin.

**Comment by robertopadovesi** [comment]
Ciao @zerai! @trinko.
Non la trovo, vedo solo questo:
![image](https://github.com/iisgiua/giuaschool/assets/146358960/7db0dfbd-a6dd-4659-aa7d-796fea356f7a)
Attendo vostre. Grazie mille!

**Comment by zerai** [comment]
E' nel riquadro in alto a destra c'è la voce 'versione del server'.
5.7 .... Percona server
Più di questo non posso fare, ora devi aspettare la risposta di trinko.

Effettivamente non stai usando un versione obsoleta, ma non è quanto consigliato dalla guida ufficiale giuia
che richiede MySql o in alternativa MariaDb.

> Requisiti di sistema

Per consentire l’utilizzo corretto dell’applicazione, il servizio di hosting usato dovrà rispettare i seguenti requisiti fondamentali:

    web server Apache 2.x o superiore;
    database server MySQL 5.5 o superiore, oppure MariaDB 10.0 o superiore;
    PHP 7.4 o superiore.

Durante la procedura di installazione saranno verificati ulteriori requisiti di sistema, evidenziandone le criticità.

La tua versione 'Percona Server' è sempre della stessa 'famiglia' ma non è cmq un prodotto simile ma differente in alcune cose.

**Comment by robertopadovesi** [comment]
Ah, va bene! Allora grazie comunque, sei stato veramente gentile come sempre! @zerai 
Buona serata. 🤗

**Comment by robertopadovesi** [comment]
Ciao @trinko! @zerai.
Avete per caso novità?
Grazie in anticipo!


Il giorno mar 23 gen 2024 alle ore 14:45 zero ***@***.***> ha
scritto:

**Comment by trinko** [comment]
Ho analizzato il problema, ma le modifiche necessarie per rendere il codice compatibile sono troppe.
Al momento non mi è possibile occuparmene.

**Comment by robertopadovesi** [comment]
Buongiorno, grazie mille! Come potrei risolvere allora? Non potresti darmi
istruzioni, oppure non c'è niente da fare?
Perché fra poco abbiamo gli scrutini, e ci servirebbe necessariamente che
il sistema funzionasse.
Potrei provare a esportare tutto su LampSchool, il vecchio registro che
fino a qualche anno fà usavamo, il problema è che dobbiamo reimpostare e
riconfigurare tutto, e visti gli imminenti scrutini, il processo sarebbe
troppo lungo.
Grazie comunque per la risposta e il supporto che mi avete dato, siete
stati veramente molto gentili! Buon lavoro e grazie della pazienza.

Il giorno gio 25 gen 2024 alle ore 23:01 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
L'ultimo aggiornamento dovrebbe risolvere i problemi.

**Comment by robertopadovesi** [comment]
Il problema è che sono all'ultimo aggiornamento, e di altri aggiornamenti
il sistema non me lo fa fare.

Il giorno sab 27 gen 2024 alle ore 13:12 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Mi sembra strano. Non ti compare la schermata:
![Screenshot 2024-01-27 at 16-56-48 Aggiorna Sistema](https://github.com/iisgiua/giuaschool/assets/1807143/765628fb-ef4a-4e39-be18-31405859234b)

**Comment by robertopadovesi** [comment]
No, mi appare la schermata che è impossibile effettuare aggiornamenti.
![image](https://github.com/iisgiua/giuaschool/assets/146358960/fe6245c9-e224-4545-9b22-feb9e6982b82)

**Comment by trinko** [comment]
Questo significa che il tuo servizio di hosting sta bloccando le connessioni server-to-server. Ci deve essere qualche impostazione per renderle possibili... 
Poiché stai usando un servizio a pagamento, rivolgiti alla loro assistenza e chiedi come consentire le connessioni server-to-server tramite l'uso delle funzioni PHP cURL e file_get_contents.

In alternativa, usa l'installazione manuale seguendo queste indicazioni:
- scarica il file dell'aggiornamento [https://github.com/iisgiua/giuaschool/releases/download/update-v1.5.7/giuaschool-update-v1.5.7.zip](https://github.com/iisgiua/giuaschool/releases/download/update-v1.5.7/giuaschool-update-v1.5.7.zip)
- carica il file precedente sul server dentro la cartella **src/Install**
- scarica il file seguente 
[gs-updating.zip](https://github.com/iisgiua/giuaschool/files/14073221/gs-updating.zip)

- decomprimi il file e caricalo sul server nella cartella principale; fai attenzione che il nome del file inizia con un punto e questo può creare problemi... in tal caso usa FileZilla per caricare il file sul server

- a questo punto continua l'installazione andando alla pagina del tuo sito:
  **nome_sito/install/update.php?token=update&step=1**

**Comment by trinko** [comment]
_Errata corrige..._

La pagina del sito è questa, 
**nome_sito/install/update.php?token=upgrade&step=1**

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
