### ISSUE TITLE
Problema in seguito agli scrutini

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#647]
Buongiorno ,volevo solo riportare il seguente problema :in seguito aallo svolgimento degli scrutini e alla loro chiusura, il registro dal lato docente non mostra più l'icona nè per firmare/modificare le lezione e nè per mettere i voti .Allego il file log

[2024-02-11_14-08.log](https://github.com/iisgiua/giuaschool/files/14232465/2024-02-11_14-08.log)

**Comment by trinko** [comment]
Quando si apre uno scrutinio viene bloccata ogni modifica al registro per il periodo scrutinato. Di conseguenza non appaiono i pulsanti che permettono modifiche al registro per il periodo scrutinato.

Se il problema è però presente nel periodo successivo allo scrutinio (es. scrutinio del primo quadrimestre e il problema si presenta in una data del secondo quadrimestre) significa che c'è un errore nei parametri di configurazione.

Controlla che le date siano coerenti per i parametri di inizio e fine anno scolastico e di fine dei vari periodi degli scrutini.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
