### ISSUE TITLE
Errore con i moduli

### ISSUE THREAD

**Issue by spinalucx** [iisgiua/giuaschool#652]
**Quando un genitore cerca di compilare un modulo di richiesta dà un errore: 500**

**Andare nella sezione richieste e cliccare invia richiesta**

[2024-02-18_00-00.log](https://github.com/iisgiua/giuaschool/files/14320556/2024-02-18_00-00.log)
In allegato il file di log

**Comment by manuelbarberi** [comment]
scrivimi: manuelbarberi.mb@libero.it

**Comment by trinko** [comment]
Dal log si capisce che la il template che hai usato ha una sintassi errata.
Probabilmente non hai scritto correttamente i nomi dei campi del modulo.

Ricontrolla il template, guarda anche gli esempi presenti nella documentazione: [modelli per i moduli](https://iisgiua.github.io/giuaschool-docs/task-request.html#uso-dei-modelli-per-i-moduli-di-richiesta-template)

**Comment by spinalucx** [comment]
Perfetto, riprovo in giornata e vi aggiorno.

Antonello Dessì ***@***.***> schrieb am Mo. 19. Feb. 2024 um
09:01:

**Comment by spinalucx** [comment]
Ho riprovato, l'errore persiste.

**Comment by trinko** [comment]
Prova a caricare l'immagine della pagina di configurazione del modulo e il file del template.
Solo così posso capire dove è l'errore.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
