### ISSUE TITLE
Problema nel passaggio al nuovo A.S

### ISSUE THREAD

**Issue by nicolatrentini** [iisgiua/giuaschool#655]
Andando ad Effettuare il passaggio al nuovo A.S. 2024/2025 è cliccandoci mi fa andare avanti fino alla parte del recupero circolari, dopo quello mi esce l'Errore 505

accedere all'utenza Admin, andando nella sezione Sistema cliccando poi Nuovo A.S, cliccando su inizia e arrivando fino a recupero circolari non i fa andare più avanti, esce Error 505

[2024-02-22_19-38.log](https://github.com/iisgiua/giuaschool/files/14378448/2024-02-22_19-38.log)

**Comment by zerai** [comment]
L'errore si verifica perche al tuo db manca una tabella, un breve estratto dal tuo log file:

> PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "...... gs_firma_circolare doesn't exist ....."


Dovresti avere il backup del db come consigliato nella doc, dal backup puoi estrarre la struttura della tabella mancante ed eventualmente ripristinarla nel tuo db.

**Comment by trinko** [comment]
La procedura di passaggio d'anno non è ancora stata adattata alle modifiche introdotte da settembre in poi. Sarà sistemata dopo gli scrutini di giugno.

Non credo basti aggiungere la tabella in questione, perché è molto probabile che vengano fuori altri errori. 

NB: il ciclo di sviluppo segue la normale scansione temporale delle attività scolastiche.

**Comment by nicolatrentini** [comment]
Allora cosa dovrei fare per passare?

**Comment by trinko** [comment]
Puoi provare a creare la tabella mancante nel modo seguente, poi vediamo se ci sono altri problemi.

Dalla pagina princiapale del tuo hosting, vai al servizio PHPMyAdmin.
Apri la finestra **SQL** (il pulsante è nella barra in alto) e inserisci il seguente comando:
```
CREATE TABLE gs_firma_circolare (id INT AUTO_INCREMENT NOT NULL, circolare_id INT NOT NULL, utente_id INT NOT NULL, creato DATETIME NOT NULL, modificato DATETIME NOT NULL, letto DATETIME DEFAULT NULL, firmato DATETIME DEFAULT NULL, INDEX IDX_BBB7DB2884DD82B (circolare_id), INDEX IDX_BBB7DB286FD5D2A (utente_id), UNIQUE INDEX UNIQ_BBB7DB2884DD82B6FD5D2A (circolare_id, utente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
```
Clicca su ESEGUI.
Quindi riprova ad eseguire il passaggio d'anno.

**Comment by nicolatrentini** [comment]
Buongiorno, ho provato è le operazioni sono state eseguite positivamente.
il registro mi ha fatto passare al nuovo A.S

Grazie

**Comment by trinko** [comment]
La segno come segnalazione chiusa
