### ISSUE TITLE
Files 

### ISSUE THREAD

**Issue by luigirotondi** [iisgiua/giuaschool#659]
[2024-03-04_07-27.log.txt](https://github.com/iisgiua/giuaschool/files/14478159/2024-03-04_07-27.log.txt)
Appena apro lo scrutinio risulta Error 500, non so come riparare l'errore

**Indica come riprodurre l'errore**

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Sembra che non abbia configurato la materia per la condotta, da **SCUOLA > MATERIE**

Come indicato nella [documentazione](https://iisgiua.github.io/giuaschool-docs/configure.html), per il corretto funzionamento del registro, dovranno essere obbligatoriamente inseriti:
-   un utente amministratore;
-   un utente Dirigente Scolastico;
-    i dati dell’istituto;
-    i dati di almeno una sede scolastica;
-    i dati di almeno un corso di studio e di almeno una classe;
-    i dati di un orario con relativa scansione oraria;
-    almeno le materie seguenti:
     -   1 materia di tipo SOSTEGNO;
     -   1 materia di tipo EDUCAZIONE CIVICA;
     -   1 materia di tipo RELIGIONE;
     -   1 materia di tipo CONDOTTA;
     -   1 materia di tipo SUPPLENZA.

**Comment by luigirotondi** [comment]
Ok grazie, invece, abbiamo difficoltà con la posta elettronica non ci fa mandare la mail per esempio quella delle credenziali generata dal registro elettronico, come possiamo procedere ?

**Comment by trinko** [comment]
> Ok grazie, invece, abbiamo difficoltà con la posta elettronica non ci fa mandare la mail per esempio quella delle credenziali generata dal registro elettronico, come possiamo procedere ?

Come utente amministratore, vai su **SISTEMA > CONFIGURA EMAIL**, quindi scegli **"Usa server locale tramite PHP"** e conferma.
Questa è l'unica modalità utilizzabile su Altervista.

Fai quindi il test di invio all'indirizzo email di prova.

Se vengono visualizzati errori carica qui lo screenshot della pagina.

**Comment by luigirotondi** [comment]
La mail risulta inviata, ma non arriva all'indirizzo di posta desiderata.
Un'altra domanda, come possiamo abilitare l'applicazione Giua App per l'istituto ?

**Comment by trinko** [comment]
> La mail risulta inviata, ma non arriva all'indirizzo di posta desiderata. 

Probabilmente è dovuto all'indirizzo del mittente: i server di posta possono bloccare le email che provengono da un dominio diverso da quello reale. Cioé, se il tuo sito è **nomesito.org**, il mittente deve essere **qualcosa@nomesito.org**.
Per impostare il mittente dei messaggi inviati dal registro vai alla pagina **Scuola > Istituto** e imposta il campo _"Indirizzo email del mittente delle notifiche inviate dal registro"_.
 

> Un'altra domanda, come possiamo abilitare l'applicazione Giua App per l'istituto ?

_Giua App_ non è più utilizzabile, non è aggiornata e quindi può mostrare dati errati.

Esiste la semplice web app GiuaReg che è sufficiente scaricare e configurare con l'indirizzo del registro. [Vedi qui](https://github.com/iisgiua/giuaReg?tab=readme-ov-file#giuareg)

**Comment by luigirotondi** [comment]
![2024-03-06_10-04.log.txt](https://github.com/iisgiua/giuaschool/files/14507330/2024-03-06_10-04.log.txt)

Quando vado a creare il modulo di evacuazione tramite la procedura che trovo sul sito di giua@school appena clicco su conferma risulta Error 500
Allego l'errore

**Comment by trinko** [comment]
Sembra che non trovi il file del modello.

Hai inserito il modello (template) nella cartella **PERSONAL/data/moduli/** ?
Se si, il nome del file viene visualizzato nella lista presente nel campo "Nome del file del modello" ?

**Comment by luigirotondi** [comment]
No, non ho inserito il modello, come posso procedere per inserirlo?

**Comment by trinko** [comment]
> No, non ho inserito il modello, come posso procedere per inserirlo?

Il modello di esempio è presente nella documentazione: [evacuazione.html.twig](https://iisgiua.github.io/giuaschool-docs/assets/docs/evacuazione.html.twig)

Va caricato nella cartella **PERSONAL/data/moduli/**

**Comment by luigirotondi2009** [comment]
Dopo aver aggiunto il file evacuazione, in "Nome del file del modello" non mi risulta il nome evacuazione, non appare nulla di moduli di evacuazione.

**Comment by luigirotondi2009** [comment]
Se io voglio modificare le valutazioni esempio i = impreparato g = giustifica come posso farlo? C'è un metodo?

**Comment by trinko** [comment]
> Se io voglio modificare le valutazioni esempio i = impreparato g = giustifica come posso farlo? C'è un metodo?

Questa segnalazione riguarda un errore sui moduli.
Non usarla per altri argomenti: apri una nuova segnalazione se è un errore o altrimenti usa le discussioni per altre richieste.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
