### ISSUE TITLE
Errore Symfony nell'installazione

### ISSUE THREAD

**Issue by dannycastellano** [iisgiua/giuaschool#671]
Buongiorno,
sto cercando di installare il registro elettronico tramite l'archivio ZIP.
Sto seguendo alla lettera la vostra guida ma dopo aver decompresso il file nella cartella principale del file manager attraverso FileZilla non riesco a visualizzare il mio sito online ma visualizzo una pagina di errore Symfony "ClassNotFoundError" con scritto: _Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle". Did you forget a "use" statement for another namespace?_ con un elenco di posizioni in cui è presente l'errore.

![symfony_error](https://github.com/iisgiua/giuaschool/assets/163742252/35077db7-e136-4817-b4fc-679bcf8f5e33)

Non riesco a capire dove sbaglio o cosa devo modificare per risolvere il problema. Come hosting uso Altervista.

Se qualcuno riuscisse a darmi una mano su quello che dovrei fare per risolvere il problema ne sarei grado.

Vi ringrazio anticipatamente e aspetto una risposta. 😊

@trinko @fabriziotoppi

**Comment by trinko** [comment]
Dopo aver decompresso tutti i file nella cartella principale del tuo sito:
- assicurati che la versione del PHP indicata nel pannello di controllo di Altervista del tuo sito sia **8.0**
- ti raccomando di attivare l'HTTPS, sempre dal pannello di controllo di Altervista
- esegui l'installazione andando all'indirizzo: **https://nome_sito/public/install/app.php**

**Comment by dannycastellano** [comment]
Sono riuscito ad effettuare la configurazione iniziale, ma al termine visualizzo ancora quella pagina di errore di Symfony nella pagina principale /public.

**Comment by zerai** [comment]
Dovresti controllare il tuo .env file, quel tipo di errore dovrebbe comparire solo se il software è installato in modalità/ambiente 'dev', mentre la tua installazione da zip file è per la modalità 'prod' (produzione).

All'interno del tuo .env file prova a cambiare la riga

```
APP_ENV=dev
```

con questo


```
APP_ENV=prod
```

**Comment by dannycastellano** [comment]
Ho modificato la riga del file .env con _APP_ENV=prod_ ma ora visualizzo questo errore:
_Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "App\Command\AliceLoadCommand": argument "$faker" of method "__construct()" has type "Faker\Generator" but this class was not found. in /membri/scuolafutura/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:49 Stack trace: #0 /membri/scuolafutura/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass >process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /membri/scuolafutura/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler >compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /membri/scuolafutura/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #3 /membri/scuolafutura/vendor/symfony/http kernel/Kernel.php(789): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /membri/scuolafutura/vendor/symfony/http-kernel/Kernel.php(190): Symfony\Component\HttpKernel\Kernel->preBoot() #5 /membri/scuolafutura/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #6 /membri/scuolafutura/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner >run() #7 /membri/scuolafutura/public/index.php(11): require_once('/membri/scuolaf...') #8 {main} thrown in /membri/scuolafutura/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 49_

**Comment by trinko** [comment]
Credo che tu abbia scaricato il codice errato, probabilmente hai scaricato lo ZIP dal pulsante previsto da gitHub sulla pagina del repository, non quello della versione 1.5.7.

Ti consiglio quindi di:
- cancellare dal sito altervista tutto quanto hai caricato, ripulendo tutto
- scaricare [questa versione](https://github.com/iisgiua/giuaschool/releases/download/v1.5.7/giuaschool-release-v1.5.7.zip) e decomprimerla localmente nel tuo computer
- caricare sul sito Altervista il nuovo codice
- andare all'indirizzo: https://nome_sito/public/install/app.php per eseguire l'installazione

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
