### ISSUE TITLE
Errore Assenze

### ISSUE THREAD

**Issue by trinko** [iisgiua/giuaschool#682]
### Discussed in https://github.com/iisgiua/giuaschool/discussions/681

<div type='discussions-op-text'>

<sup>Originally posted by **Bologna221** March 28, 2024</sup>
salve come posso risolvere l'errore allegato.
![image](https://github.com/iisgiua/giuaschool/assets/128899928/3c15a103-4007-48fd-a18d-5e403e604296)
</div>

**Comment by Bologna221** [comment]
ok comunque sono le presenze

**Comment by Bologna221** [comment]
e mi dà errore

**Comment by trinko** [comment]
Devi caricare un log degli errori completo, come ho detto nell'altro messaggio:
``
... devi fare attenzione a come generi il log degli errori, perché quello che hai inviato non contiene nessun problema, probabilmente perché hai indicato un' orario errato.
``
