### ISSUE TITLE
Errore nel file di evacuazione

### ISSUE THREAD

**Issue by lucacaputo09** [iisgiua/giuaschool#688]
**Descrivi il problema**
Salve, dopo aver configurato correttamente il modulo di evacuazione, quando vado ad aprirlo risulta error 500 allego l'errore

**Indica come riprodurre l'errore**

**File di LOG**
[2024-04-15_07-32.log.txt](https://github.com/iisgiua/giuaschool/files/14974409/2024-04-15_07-32.log.txt)

Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by lucacaputo09** [comment]
[2024-04-15_12-40.log.txt](https://github.com/iisgiua/giuaschool/files/14977754/2024-04-15_12-40.log.txt)

**Comment by trinko** [comment]
L'errore è nel template alla riga 11:
```
PERSONAL/data/moduli/evacuazione.html.twig line 11 [...] Argument #1 ($view) must be of type Symfony\\Component\\Form\\FormView, null given 
```
Hai modificato il file del template del modulo di evacuazione? 
Hai configurato il modulo seguendo le indicazioni della [documentazione](https://iisgiua.github.io/giuaschool-docs/task-request.html#esempio-4-modulo-per-la-prova-di-evacuazione)?

**Comment by lucacaputo09** [comment]
Ho configurato il modulo con le stesse parole degli esempi per i moduli, puoi dirmi come posso modificare questo?

**Comment by trinko** [comment]
Forse non hai cancellato la cache: prova a rimuovere l'intero contenuto della cartella **var/cache/prod**

**Comment by lucacaputo09** [comment]
Niente, mi risulta sempre errore..

**Comment by trinko** [comment]
Mi fai uno screenshot della pagina di configurazione del modulo di evacuazione?

**Comment by lucacaputo09** [comment]
![Screenshot_20240421_164228](https://github.com/iisgiua/giuaschool/assets/165372166/4399e2de-1d33-4736-b2b7-dcbc92b3373e)
![Screenshot_20240421_164233_edit_39511131212269](https://github.com/iisgiua/giuaschool/assets/165372166/8607e155-eb40-4f7d-87ab-2602b07f13a2)

**Comment by trinko** [comment]
L'errore è dovuto al fatto che non seguito le indicazioni dell'esempio riportato nella guida.
Hai cambiato i nomi dei campi, aggiungendo spazi e punteggiatura e hai aggiunto il campo dato che è già incluso.

Devi impostare i nomi indicati nell'[esempio riportato nella guida](https://iisgiua.github.io/giuaschool-docs/task-request.html#esempio-4-modulo-per-la-prova-di-evacuazione).
