### ISSUE TITLE
Problema con il caricamento del file zip

### ISSUE THREAD

**Issue by Matyf97** [iisgiua/giuaschool#690]
Salve, io sto cercando di installare il Registro giua@school su Altervista, tramite appunto il file manager. L'ho già fatto altre volte e funzionava sempre tutto tranne la configurazione della mail. Oggi sto provando a reinstallare giua@school su Altervista però come inserisco il file scaricato qua su GitHub (giuaschool-master.zip) segnala un errore, dicendo che l'archivio contiene dei file non validi. Non so di preciso cosa intenda però se scarico il file grande della release 1.5.7 da circa 90MB, non mi appaiono gli aggiornamenti recenti, come appunto la possibilità di aggiungere un voto Scritto/Grafico, cosa che in un altro registro giua@school non installato da me è possibile fare. Come posso installare il registro con i nuovi aggiornamenti?
Spero non vi disturba con questa richiesta.
Cordiali saluti

**Comment by trinko** [comment]
Da quello che ho capito stai scaricando il file zip errato. 
L'ultima versione la trovi sempre qui: [ultima verione](https://iisgiua.github.io/giuaschool-docs/latest-release.html)

Segui le indicazioni per l'installazione: [installazione su Altervista](https://iisgiua.github.io/giuaschool-docs/install-zip.html#esempio-di-installazione-su-altervista)

**Comment by Matyf97** [comment]
Ok grazie, quindi dovrei caricare direttamente la cartella estratta nel mio pc e non devo caricare direttamente il file .zip?

**Comment by Matyf97** [comment]
Inoltre non riesco a configurare l'email su Altervista, ogni volta che ci provo solo ad aprire la pagina di configurazione risulta l'errore 500.

**Comment by trinko** [comment]
> Ok grazie, quindi dovrei caricare direttamente la cartella estratta nel mio pc e non devo caricare direttamente il file .zip?

Si, come descritto nella guida indicata.

> Inoltre non riesco a configurare l'email su Altervista, ogni volta che ci provo solo ad aprire la pagina di configurazione risulta l'errore 500.

Se parli della configurazione dell'email sul giua@school, devi prima completare l'installazione.

**Comment by Matyf97** [comment]
Grazie mille, per email intendevo dopo l’installazione e la configurazione, facendo l’accesso da admin non riesco comunque a configurare l’email, risulta sempre errore 500. Stessa cosa se provo ad entrare nella pagina per il reset della password sulla pagina di accesso. Ovviamente adesso bisogna vedere se funziona dopo che Filezilla finisce di caricare i file scompattati.

**Comment by Matyf97** [comment]
Dopo tante ore di attesa, finalmente i file si sono trasferiti tramite Filezilla su Altervista. Ho eseguito la procedura di installazione e ho spostato tutti i file sulla cartella principale. Purtroppo però accedendo alla pagina principale (/public/login/form) segnala subito l’errore 500, non permettendomi nemmeno di accedere al Registro. Devo reinstallare il Registro di nuovo trasferendo i file con Filezilla o posso caricare direttamente il file .zip su Altervista?

**Comment by Matyf97** [comment]
> Grazie mille, per email intendevo dopo l’installazione e la configurazione, facendo l’accesso da admin non riesco comunque a configurare l’email, risulta sempre errore 500. Stessa cosa se provo ad entrare nella pagina per il reset della password sulla pagina di accesso. Ovviamente adesso bisogna vedere se funziona dopo che Filezilla finisce di caricare i file scompattati.



> Grazie mille, per email intendevo dopo l’installazione e la configurazione, facendo l’accesso da admin non riesco comunque a configurare l’email, risulta sempre errore 500. Stessa cosa se provo ad entrare nella pagina per il reset della password sulla pagina di accesso. Ovviamente adesso bisogna vedere se funziona dopo che Filezilla finisce di caricare i file scompattati.

**Comment by trinko** [comment]
> Dopo tante ore di attesa, finalmente i file si sono trasferiti tramite Filezilla su Altervista. Ho eseguito la procedura di installazione e ho spostato tutti i file sulla cartella principale. Purtroppo però accedendo alla pagina principale (/public/login/form) segnala subito l’errore 500, non permettendomi nemmeno di accedere al Registro. Devo reinstallare il Registro di nuovo trasferendo i file con Filezilla o posso caricare direttamente il file .zip su Altervista?

Se hai finito di caricare i file, come indicato nella guida, devi eseguire la procedura di installazione:
```
Quando sei sicuro di aver caricato tutto, esegui la procedura di installazione 
andando all’indirizzo: 
  http://nome_sito_altervista/public/install/app.php
```

**Comment by Matyf97** [comment]
> > Dopo tante ore di attesa, finalmente i file si sono trasferiti tramite Filezilla su Altervista. Ho eseguito la procedura di installazione e ho spostato tutti i file sulla cartella principale. Purtroppo però accedendo alla pagina principale (/public/login/form) segnala subito l’errore 500, non permettendomi nemmeno di accedere al Registro. Devo reinstallare il Registro di nuovo trasferendo i file con Filezilla o posso caricare direttamente il file .zip su Altervista?
> 
> Se hai finito di caricare i file, come indicato nella guida, devi eseguire la procedura di installazione:
> 
> ```
> Quando sei sicuro di aver caricato tutto, esegui la procedura di installazione 
> andando all’indirizzo: 
>   http://nome_sito_altervista/public/install/app.php
> ```

Ho eseguito la procedura di installazione ma nonostante ciò non si apre la pagina di login, ma dà l’errore 500.

**Comment by trinko** [comment]
Questo non è normale... 
Hai controllato se ci sono stati errori di caricamento di file quando hai usato FileZilla o altro programma FTP?

Oppure, più probabile: controlla su Altervista se la versione PHP usata è la 8.0...
NB: la versione può essere stata modificata a causa del caricamento dei file.

**Comment by Matyf97** [comment]
> Questo non è normale... Hai controllato se ci sono stati errori di caricamento di file quando hai usato FileZilla o altro programma FTP?
> 
> Oppure, più probabile: controlla su Altervista se la versione PHP usata è la 8.0... NB: la versione può essere stata modificata a causa del caricamento dei file.

Si, non ci sono stati errori segnalati dal sistema, ora che ci penso però durante la fase di installazione non mi ha chiesto di inserire le credenziali per l’admin e magari è quello il problema. Più tardi riprovo con Filezilla e vedo cosa succede. Inoltre volevo chiedere qual è il file php che consente di configurare l’invio delle mail dal Registro?

**Comment by trinko** [comment]
> Più tardi riprovo con Filezilla e vedo cosa succede. Inoltre volevo chiedere qual è il file php che consente di configurare l’invio delle mail dal Registro?

La password di admin deve avertela chiesta se hai eseguito tutta la procedura di installazione. Non è che c'è stato un errore in questa? 

Sconsiglio di fare modifiche di configurazione direttamente sui file, meglio farle dalle pagine di amministrazione. Comunque, si trova la configurazione è in **.env**

**Comment by Matyf97** [comment]
> > Più tardi riprovo con Filezilla e vedo cosa succede. Inoltre volevo chiedere qual è il file php che consente di configurare l’invio delle mail dal Registro?
> 
> La password di admin deve avertela chiesta se hai eseguito tutta la procedura di installazione. Non è che c'è stato un errore in questa?
> 
> Sconsiglio di fare modifiche di configurazione direttamente sui file, meglio farle dalle pagine di amministrazione. Comunque, la configurazione delle email è in **.env**

Sì, sicuramente c'è stato un errore nella procedura di installazione. Ora ho reinserito i file su Altervista tramite Filezilla, cancellando quelli di ieri. Nella procedura di installazione risultava un errore, ora risolto aggiungendo la cartella /prod su /var/sessions (ora /var/sessions/prod).

Nella procedura di installazione non riesce a connettersi al database, come posso trovare le credenziali e tutto il necessario per poter collegarlo?

**Comment by trinko** [comment]
Prova a cancellare la cache, la cartella **var/cache/prod**

Se non funziona, guarda se ha creato il file di log in **var/log/** e caricalo qui in modo che lo possa vedere.

**Comment by Matyf97** [comment]
> Prova a cancellare la cache, la cartella **var/cache/prod**
> 
> Se non funziona, guarda se ha creato il file di log in **var/log/** e caricalo qui in modo che lo possa vedere.

Ecco i file di log: 
[app_prod-2024-04-23.log](https://github.com/iisgiua/giuaschool/files/15097363/app_prod-2024-04-23.log)
[app_prod-2024-04-24.log](https://github.com/iisgiua/giuaschool/files/15097364/app_prod-2024-04-24.log)

**Comment by trinko** [comment]
Sembra che manchi il file seguente (probabilmente non è stato caricato per qualche errore su Filezilla):
```
vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php
```

**Comment by Matyf97** [comment]
> Sembra che manchi il file seguente (probabilmente non è stato caricato per qualche errore su Filezilla):
> 
> ```
> vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php
> ```

L'ho aggiunto tramite Filezilla però continua a non funzionare...

**Comment by trinko** [comment]
> L'ho aggiunto tramite Filezilla però continua a non funzionare...

Probabilmente mancano anche altri file. 
Controlla nel file di log, dovresti vedere nelle righe corrispondenti all'ora dell'ultimo errore un messaggio esplicativo.

**Comment by Matyf97** [comment]
> > L'ho aggiunto tramite Filezilla però continua a non funzionare...
> 
> Probabilmente mancano anche altri file. Controlla nel file di log, dovresti vedere nelle righe corrispondenti all'ora dell'ultimo errore un messaggio esplicativo.

Sono riuscito a installare il Registro caricando direttamente il file zip su Altervista, impiegandoci circa due minuti al posto di impiegarci 2 ore. Fortunatamente funziona tranne che le e-mail perché segnala il solito errore 500.

**Comment by trinko** [comment]
Estrai il log degli errori nel modo seguente:
 - come utente amministratore, andare alla pagina **Sistema > Manutenzione** e abilitare il debug;
 - eseguire la pagina che causa l'errore e segnarsi l'ora in cui viene eseguita;
 - tornare alla pagina **Sistema > Manutenzione** ed estrarre il log, indicando l'ora che è stata segnata in precedenza;
 - scaricare il file di log e allegarlo qui 
 - tornare alla pagina **Sistema > Manutenzione** e disabilitare il debug.

**Comment by Matyf97** [comment]
> Estrai il log degli errori nel modo seguente:
> 
> * come utente amministratore, andare alla pagina **Sistema > Manutenzione** e abilitare il debug;
> * eseguire la pagina che causa l'errore e segnarsi l'ora in cui viene eseguita;
> * tornare alla pagina **Sistema > Manutenzione** ed estrarre il log, indicando l'ora che è stata segnata in precedenza;
> * scaricare il file di log e allegarlo qui
> * tornare alla pagina **Sistema > Manutenzione** e disabilitare il debug.

Ecco il file di log estratto pochi minuti fa: 
[2024-04-27_13-32.log](https://github.com/iisgiua/giuaschool/files/15138041/2024-04-27_13-32.log)

**Comment by trinko** [comment]
```
"The mailer DSN has some garbage at the end."
```
Per qualche motivo ci sono dati errati nella configurazione. 
Fai così:
- scarica il file **.env** che trovi nella cartella principale (usa FileZilla e scaricalo, perché il gestore dei file di Altervista probabilmente non te lo mostra)
- modifica solo la riga che contiene **MAILER_DSN** nel modo seguente (senza spazi):
```
MAILER_DSN='php://default'
```
- salva e carica sul server il file **.env**

**Comment by Matyf97** [comment]
> ```
> "The mailer DSN has some garbage at the end."
> ```
> 
> Per qualche motivo ci sono dati errati nella configurazione. Fai così:
> 
> * scarica il file **.env** che trovi nella cartella principale (usa FileZilla e scaricalo, perché il gestore dei file di Altervista probabilmente non te lo mostra)
> * modifica solo la riga che contiene **MAILER_DSN** nel modo seguente (senza spazi):
> 
> ```
> MAILER_DSN='php://default'
> ```
> 
>  * salva e carica sul server il file **.env**

Ha funzionato, ora funziona tutto. Grazie mille, sei stato d’aiuto e scusa per il tempo che ti ho rubato in questa settimana. Se avrò altre difficoltà con il Registro ti contatterò tramite GitHub sperando di non rubarti troppo tempo. Grazie mille e buon serata!

**Comment by Matyf97** [comment]
> > ```
> > "The mailer DSN has some garbage at the end."
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Per qualche motivo ci sono dati errati nella configurazione. Fai così:
> > 
> > * scarica il file **.env** che trovi nella cartella principale (usa FileZilla e scaricalo, perché il gestore dei file di Altervista probabilmente non te lo mostra)
> > * modifica solo la riga che contiene **MAILER_DSN** nel modo seguente (senza spazi):
> > 
> > ```
> > MAILER_DSN='php://default'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * salva e carica sul server il file **.env**
> 
> Ha funzionato, ora funziona tutto. Grazie mille, sei stato d’aiuto e scusa per il tempo che ti ho rubato in questa settimana. Se avrò altre difficoltà con il Registro ti contatterò tramite GitHub sperando di non rubarti troppo tempo. Grazie mille e buon serata!

Nel caso volessi cambiare l’indirizzo di invio delle mail come devo procedere?

**Comment by Matyf97** [comment]
> > > ```
> > > "The mailer DSN has some garbage at the end."
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Per qualche motivo ci sono dati errati nella configurazione. Fai così:
> > > 
> > > * scarica il file **.env** che trovi nella cartella principale (usa FileZilla e scaricalo, perché il gestore dei file di Altervista probabilmente non te lo mostra)
> > > * modifica solo la riga che contiene **MAILER_DSN** nel modo seguente (senza spazi):
> > > 
> > > ```
> > > MAILER_DSN='php://default'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * salva e carica sul server il file **.env**
> > 
> > 
> > Ha funzionato, ora funziona tutto. Grazie mille, sei stato d’aiuto e scusa per il tempo che ti ho rubato in questa settimana. Se avrò altre difficoltà con il Registro ti contatterò tramite GitHub sperando di non rubarti troppo tempo. Grazie mille e buon serata!
> 
> Nel caso volessi cambiare l’indirizzo di invio delle mail come devo procedere?

In realtà ho proprio un problema sempre con l'invio delle mail perché non funziona inviando le mail (anche quella di prova) agli indirizzi @gmail.com, invece con tutti gli altri funziona perfettamente.

**Comment by trinko** [comment]
Devi controllare l'indirizzo del mittente, che viene impostato dalla pagina **Scuola > Istituto**, nel campo **Indirizzo email del mittente delle notifiche**.

Solitamente i server di posta bloccano le mail dove il mittente ha un dominio differente da quello da cui avviene l'invio (cioè il tuo sito web).

**Comment by Matyf97** [comment]
> Devi controllare l'indirizzo del mittente, che viene impostato dalla pagina **Scuola > Istituto**, nel campo **Indirizzo email del mittente delle notifiche**.
> 
> Solitamente i server di posta bloccano le mail dove il mittente ha un dominio differente da quello da cui avviene l'invio (cioè il tuo sito web).

Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.

**Comment by trinko** [comment]
> Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.

E' questo il problema: il server non ha indirizzo gmail.com ma altervista.org
Probabilmente Gmail fa uun controllo di sicurezza e vede che il mittente ha un dominio "fasullo", perché l'email non è spedita da Gmail. 
Dovresti avere un indirizzo di posta del tuo sito: usa quello come mittente.
 
> Relativamente alla modifica della mail dalla pagina **Scuola > Istituto** e nel campo **Indirizzo email**, non funziona perché continua ad inviare la mail dal vecchio indirizzo. Magari devo modificare il file .env?

No, l'unico modo per modificare il mittente è quello indicato. Ma attenzione non il campo **Indirizzo email** ma **Indirizzo email del mittente delle notifiche inviate dal registro**.

**Comment by Matyf97** [comment]
> > Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.
> 
> E' questo il problema: il server non ha indirizzo gmail.com ma altervista.org Probabilmente Gmail fa uun controllo di sicurezza e vede che il mittente ha un dominio "fasullo", perché l'email non è spedita da Gmail. Dovresti avere un indirizzo di posta del tuo sito: usa quello come mittente.
> 
> > Relativamente alla modifica della mail dalla pagina **Scuola > Istituto** e nel campo **Indirizzo email**, non funziona perché continua ad inviare la mail dal vecchio indirizzo. Magari devo modificare il file .env?
> 
> No, l'unico modo per modificare il mittente è quello indicato. Ma attenzione non il campo **Indirizzo email** ma **Indirizzo email del mittente delle notifiche inviate dal registro**.

Va bene, ti ringrazio, veramente. Buona giornata!

**Comment by mpignatelli** [comment]
> > > Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.
> > 
> > 
> > E' questo il problema: il server non ha indirizzo gmail.com ma altervista.org Probabilmente Gmail fa uun controllo di sicurezza e vede che il mittente ha un dominio "fasullo", perché l'email non è spedita da Gmail. Dovresti avere un indirizzo di posta del tuo sito: usa quello come mittente.
> > > Relativamente alla modifica della mail dalla pagina **Scuola > Istituto** e nel campo **Indirizzo email** , non funziona perché continua ad inviare la mail dal vecchio indirizzo. Magari devo modificare il file .env?
> > 
> > 
> > No, l'unico modo per modificare il mittente è quello indicato. Ma attenzione non il campo **Indirizzo email** ma **Indirizzo email del mittente delle notifiche inviate dal registro** .
> 
> Va bene, ti ringrazio, veramente. Buona giornata!

Ciao mi potresti aiutare a istallare giuaschool ho inserito il file che ho trovato sul sito giuaschool ma quando vado sul file installa non va.

**Comment by Matyf97** [comment]
> > > > Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.
> > > 
> > > 
> > > E' questo il problema: il server non ha indirizzo gmail.com ma altervista.org Probabilmente Gmail fa uun controllo di sicurezza e vede che il mittente ha un dominio "fasullo", perché l'email non è spedita da Gmail. Dovresti avere un indirizzo di posta del tuo sito: usa quello come mittente.
> > > > Relativamente alla modifica della mail dalla pagina **Scuola > Istituto** e nel campo **Indirizzo email** , non funziona perché continua ad inviare la mail dal vecchio indirizzo. Magari devo modificare il file .env?
> > > 
> > > 
> > > No, l'unico modo per modificare il mittente è quello indicato. Ma attenzione non il campo **Indirizzo email** ma **Indirizzo email del mittente delle notifiche inviate dal registro** .
> > 
> > 
> > Va bene, ti ringrazio, veramente. Buona giornata!
> 
> Ciao mi potresti aiutare a istallare giuaschool ho inserito il file che ho trovato sul sito giuaschool ma quando vado sul file installa non va.

Ciao! Prova a seguire le discussioni che ho fatto io con il sign. Dessì, magari riesci ad installarlo! Se hai difficoltà sono disponibile per aiutarti oppure puoi aprire un ticket come ho fatto io e risponderà il sign. Dessì.

**Comment by mpignatelli** [comment]
> > > > > Strano perché il dominio da cui invio la mail e quello stesso del mittente è sempre gmail.com.
> > > > 
> > > > 
> > > > E' questo il problema: il server non ha indirizzo gmail.com ma altervista.org Probabilmente Gmail fa uun controllo di sicurezza e vede che il mittente ha un dominio "fasullo", perché l'email non è spedita da Gmail. Dovresti avere un indirizzo di posta del tuo sito: usa quello come mittente.
> > > > > Relativamente alla modifica della mail dalla pagina **Scuola > Istituto** e nel campo **Indirizzo email** , non funziona perché continua ad inviare la mail dal vecchio indirizzo. Magari devo modificare il file .env?
> > > > 
> > > > 
> > > > No, l'unico modo per modificare il mittente è quello indicato. Ma attenzione non il campo **Indirizzo email** ma **Indirizzo email del mittente delle notifiche inviate dal registro** .
> > > 
> > > 
> > > Va bene, ti ringrazio, veramente. Buona giornata!
> > 
> > 
> > Ciao mi potrebbe aiutare a istallare giuaschool ho inserito il file che ho trovato sul sito giuaschool ma quando vado sul file installa non va.
> 
> Ciao! Prova a seguire le discussioni che ho fatto io con il segno. Quindi, magari riesci ad installarlo! Se hai difficoltà sono disponibile per aiutarti oppure puoi aprire un biglietto come ho fatto io e risponderà il segno. Dessì.
Visto che sono poco capace mi potresti aiutare tu ti invio il mio indirizzo email: michelina.pignatelli1983@gmail.com

**Comment by robertopadovesi** [comment]
Buongiorno! Io sono disponibile nell'aiutarti.
Scrivimi alla mail: ***@***.***

Il giorno dom 5 mag 2024 alle ore 15:12 mpignatelli <
***@***.***> ha scritto:

**Comment by robertopadovesi** [comment]
Ciao Mattia, ci vediamo anche qui! ☺️
Hai qualche problema in particolare?


Il giorno dom 5 mag 2024 alle ore 15:08 Matyf97 ***@***.***>
ha scritto:

**Comment by robertopadovesi** [comment]
@mpignatelli Buongiorno! Io sarei disposto ad aiutarla, potrebbe scrivermi in privato così ne parliamo? Mi contatti alla mail padovesi.roberto@gmail.com. Grazie!

**Comment by Matyf97** [comment]
@trinko 
Salve, scusa se ti disturbo nuovamente ma ho di nuovo dei problemi con il Registro Giua. Ieri lo ho aggiornato alla versione 1.5.8 però non riesco a firmare le lezioni. Mi spiego, nella tabella delle lezioni della giornata non mi appare il tasto "Aggiungi", di conseguenza non posso firmare. Inoltre, quando accedo come coordinatore e provo ad andare nella sezione scrutini risulta l'errore 500, ma non so il perché.

**Comment by Matyf97** [comment]
> @trinko Salve, scusa se ti disturbo nuovamente ma ho di nuovo dei problemi con il Registro Giua. Ieri lo ho aggiornato alla versione 1.5.8 però non riesco a firmare le lezioni. Mi spiego, nella tabella delle lezioni della giornata non mi appare il tasto "Aggiungi". Non mi permette nemmeno di inserire note disciplinari o valutazioni sempre perché non appare alcun pulsante, di conseguenza non posso firmare e utilizzare il registro.. Inoltre, quando accedo come coordinatore e provo ad andare nella sezione scrutini risulta l'errore 500, ma non so il perché.

Questo è il file di log che sono riuscito a ripristinare attivando la modalità debug.
[Uploading 2024-05-24_16-42.log…]()

**Comment by Matyf97** [comment]
> > @trinko Salve, scusa se ti disturbo nuovamente ma ho di nuovo dei problemi con il Registro Giua. Ieri lo ho aggiornato alla versione 1.5.8 però non riesco a firmare le lezioni. Mi spiego, nella tabella delle lezioni della giornata non mi appare il tasto "Aggiungi". Non mi permette nemmeno di inserire note disciplinari o valutazioni sempre perché non appare alcun pulsante, di conseguenza non posso firmare e utilizzare il registro.. Inoltre, quando accedo come coordinatore e provo ad andare nella sezione scrutini risulta l'errore 500, ma non so il perché.
> 
> Questo è il file di log che sono riuscito a ripristinare attivando la modalità debug. Uploading 2024-05-24_16-42.log…

Inoltre, in tutto il periodo del secondo quadrimestre oltre a non farmi firmare, inserire valutazioni e inserire gli scrutini, non mi permette di segnare le assenze perché risulta errore 404.

**Comment by trinko** [comment]
Il file di log non l'hai caricato correttamente: non è leggibile.

Di solito, problemi di questo tipo sono dovuti ad una errata configurazione dei parametri sui periodi: in particolare contralla le date di fine dei periodi impostati nei parametri e se per caso hai attivato anche l'uso di tre periodi, inserendo il nome del terzo periodo.
Controlla poi che le date impostate sugli scrutini in **SCUOLA > SCRUTINI** siano coerenti.

**Comment by Matyf97** [comment]
> Il file di log non l'hai caricato correttamente: non è leggibile.
> 
> Di solito, problemi di questo tipo sono dovuti ad una errata configurazione dei parametri sui periodi: in particolare controlla le date di fine dei periodi impostati nei parametri e se per caso hai attivato anche l'uso di tre periodi, inserendo il nome del terzo periodo. Controlla poi che le date impostate sugli scrutini in **SCUOLA > SCRUTINI** siano coerenti.
> 
> PS: la prossima volta, per un nuovo problema apri una nuova segnalazione.

Sì, ci sono 4 periodi, però io voglio che ci siano solo il Primo e il Secondo Quadrimestre, come posso rimuovere gli altri?

**Comment by Matyf97** [comment]
> > Il file di log non l'hai caricato correttamente: non è leggibile.
> > Di solito, problemi di questo tipo sono dovuti ad una errata configurazione dei parametri sui periodi: in particolare controlla le date di fine dei periodi impostati nei parametri e se per caso hai attivato anche l'uso di tre periodi, inserendo il nome del terzo periodo. Controlla poi che le date impostate sugli scrutini in **SCUOLA > SCRUTINI** siano coerenti.
> > PS: la prossima volta, per un nuovo problema apri una nuova segnalazione.
> 
> Sì, ci sono 5 periodi, però io voglio che ci siano solo il Primo e il Secondo Quadrimestre, come posso rimuovere gli altri?

**Comment by trinko** [comment]
> Sì, ci sono 5 periodi, però io voglio che ci siano solo il Primo e il Secondo Quadrimestre, come posso rimuovere gli altri?

Nella pagina **SISTEMA > PARAMETRI**, lascia vuoto il parametro **periodo3_nome**, così il sistema è configurato per gestire solo 2 periodi intermedi (i due quadrimestri).

Gli altri periodi sono gli eventuali scrutini successivi allo scrutinio finale (scrutinio per il giudizio sospeso, sessione supplettiva e scrutini rinviati): se non intendi usarli, basta non configurare la data di inizio del periodo.

**Comment by Matyf97** [comment]
> > Sì, ci sono 5 periodi, però io voglio che ci siano solo il Primo e il Secondo Quadrimestre, come posso rimuovere gli altri?
> 
> Nella pagina **SISTEMA > PARAMETRI**, lascia vuoto il parametro **periodo3_nome**, così il sistema è configurato per gestire solo 2 periodi intermedi (i due quadrimestri).
> 
> Gli altri periodi sono gli eventuali scrutini successivi allo scrutinio finale (scrutinio per il giudizio sospeso, sessione supplettiva e scrutini rinviati): se non intendi usarli, basta non configurare la data di inizio del periodo.

Sì, è già vuoto, solo che continua a mostrarmi anche gli altri periodi. E' come se lo scrutinio del secondo quadrimestre fosse già iniziato ma mai chiuso, solo che appare l'errore 500 se vado su **Coordinatore > Classe > Scrutini**

**Comment by trinko** [comment]
Se carichi il log posso capire meglio il problema.

**Comment by Matyf97** [comment]
> Se carichi il log posso capire meglio il problema.

Ho notato che nell’errore segna la scritta CRITICAL.
[2024-05-26_19-26.log](https://github.com/iisgiua/giuaschool/files/15448363/2024-05-26_19-26.log)

**Comment by trinko** [comment]
L'errore indica la presenza di scrutini finali già iniziati prima dell'aggiornamento e che quindi non contengono i dati previsti.

Si dovrebbe risolvere eseguendo il seguente comando nella finestra SQL di PHPMyadmin:
```
update gs_scrutinio set stato='N' where periodo='F'; 
```

**Comment by Matyf97** [comment]
> L'errore indica la presenza di scrutini finali già iniziati prima dell'aggiornamento e che quindi non contengono i dati previsti.
> 
> Si dovrebbe risolvere eseguendo il seguente comando nella finestra SQL di PHPMyadmin:
> 
> ```
> update gs_scrutinio set stato='N' where periodo='F'; 
> ```

Perfetto, ha funzionato, grazie mille.

Per quanto riguarda gli scrutini, c’è una materia a cui partecipano soltanto alcuni alunni poiché di indirizzo musicale. Come posso inserire k voti solo agli alunni che partecipano al corso musicale (quindi solo a questa materia) senza mettere NC agli altri?

**Comment by trinko** [comment]
> Per quanto riguarda gli scrutini, c’è una materia a cui partecipano soltanto alcuni alunni poiché di indirizzo musicale. Come posso inserire i voti solo agli alunni che partecipano al corso musicale (quindi solo a questa materia) senza mettere NC agli altri?

Questa non è una segnalazione di errore. Ho spostato e risposto nelle discussioni: #713

**Comment by trinko** [comment]
Visto che il problema è risolto, chiudo la segnalazione.
