### ISSUE TITLE
Certificato delle Competenze 

### ISSUE THREAD

**Issue by lucacaputo09** [iisgiua/giuaschool#693]
**Descrivi il problema**
Salve, come funziona in classe 2ª il certificato delle Competenze? 

**Indica come riprodurre l'errore**

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Chiudo la segnalazione perché non è un errore del programma.
Ti rispondo nell'area discussioni.
