### ISSUE TITLE
Errore aggiornamenti registro 

### ISSUE THREAD

**Issue by lucacaputo09** [iisgiua/giuaschool#695]
**Descrivi il problema**

Salve, quando vado nelle sezione aggiornati del registro appare questa schermata. Come posso procedere? 
**Indica come riprodurre l'errore**

**File di LOG**
![Screenshot_20240427_100712](https://github.com/iisgiua/giuaschool/assets/165372166/77b2117a-2d14-4f3b-b1a2-bcad2cc8876f)

Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Significa che il tuo servizio di hosting sta bloccando la richiesta verso altri siti esterni.

Se stai usando Altervista, devi consentire i collegamenti esterni:
- dal pannello di controllo Altervista, clicca su **RISORSE** e poi su ** Modifica Impostazioni PHP**
- scendi nella pagina sino al riquadro **Connessioni server to server**
- seleziona **Collegamento senza restrizioni** e clicca su **SALVA**
