### ISSUE TITLE
Certificazione competenze 

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#709]
Buongiorno,ho appena notato che la nuova certificazione prevede un'intestazione ministeriale che si colloca proprio sotto quella scolastica respingendo la tabella delle competenze nelle pagine successive, richiedendo così ben 3 pagine solo per un alunno ,come si può fare ?

**Comment by trinko** [comment]
Si, la nuova certificazione è conforme al modello ministeriale dell'allegato C riportato nel  [decreto](https://www.miur.gov.it/documents/20182/7975243/m_pi.AOOGABMI.Registro+Decreti%28R%29.0000014.30-01-2024.pdf/bb2aeae3-7803-bd2f-48a9-a8c174e19501?version=1.0&t=1707228861855)
Tale modello non ci sta in due pagine.

Ovviamente puoi modificare il template presente in **templates/coordinatore/documenti/scrutinio_certificazioni.html.twig**, ma non sarebbe più conforme al modello ministeriale.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
