### ISSUE TITLE
Attività di Orientamento a.s. 2023/2024

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#716]
Buongiorno ,come deliberato dal ministero dell'istruzione e del merito nel D.M. n. 328 del 22 dicembre 2022 , per l'anno 2023/2024 mi pare fossero previste 30 ore di attività in materia di "Orientamento" per tutte le scuole e in modo particolare per le scuole secondarie di secondo grado.Pertanto ci siamo confrontati con colleghi che lavorano per più istituto e abbiano notato che negli altri istituti il registro ,diverso da giuaschool , permette di creare la materia "Orientamento" con la possibilità di rendere attivo solo il campo della firma del docente ,assenze e argomento svolto ,mentre non è possibile registrare i voti delle interrogazioni ,verifiche varie ,in quanto non l'orientamento non è oggetto di valutazione .Stavo vedendo per quanto riguarda giuaschool e mi rendo conto che ciò è impossibile , in quanto ,pur impostando la materia "Orientamento" come supplenza , le valutazioni (verifiche scritte,interroggazione etc ) le fa mettere lo stesso , quando dovrebbe bloccare proprio la sezione "voti" .Come si può fare ?

**Comment by trinko** [comment]
A inizio anno scolastico non era molto chiaro come dovessero essere svolte queste attività, per cui, per quanto riguarda il registro elettronico, si è deciso di non riportarle.
Infatti, è obbligatorio lo svolgimento delle ore, ma non è obbligatorio che siano firmate come ore di lezione: possono essere svolte anche in orario extracurricolare. E' simile al PCTO (le cui attività, tra l'altro, possono essere anche di Orientamento), per il quale non si firma il registro.
Tieni presente, poi, che sulla piattaforma UNICA devono essere caricate le attività, per cui l'attestazione del loro svolgimento avviene lì non sul registro.

In ogni caso, mi riservo di rivedere la questione per il prossimo anno scolastico. 
Per ora, se proprio vuoi registrare le ore, potresti inserire una materia **Orientamento** con il tipo **SOSTEGNO**, che non permette valutazioni. Se poi non vuoi che compaia nei verbali degli scrutini, imposta la tipologia della cattedra a **POTEZIAMENTO**. Non è la soluzione perfetta, perché vedrai alcune diciture tipiche del Sostegno, ma credo che funzioni.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
