### ISSUE TITLE
errore 500 quando vai su assenza e sono inserite gli studenti nella classe

### ISSUE THREAD

**Issue by francyoo17** [iisgiua/giuaschool#719]
salve mi va in errore quando vado su assenze e sono inseriti gli studenti nella classe 
[2024-06-06_21-33.log](https://github.com/user-attachments/files/15685294/2024-06-06_21-33.log)

**Comment by trinko** [comment]
Il log riportato non contiene le informazioni sulla pagina che genera l'errore.
Probabilmente quando hai fatto l'estrazione non hai seguito bene i seguenti passi:

- abilitare il debug
- eseguire la pagina che causa l'errore e segnarsi l'ora in cui viene eseguita
- estrarre il log indicando l'ora segnata in precedenza.

**Comment by francyoo17** [comment]
[2024-06-10_17-54.log](https://github.com/user-attachments/files/15775923/2024-06-10_17-54.log)

**Comment by trinko** [comment]
Stai usando una vecchia versione: devi aggiornare alla versione 1.5.8.

Vai su **SISTEMA > AGGIORNAMENTO** e segui le indicazioni. Fai sempre il backup prima di procedere all'aggiornamento del sistema.

**Comment by francyoo17** [comment]
![Immagine 2024-06-10 213537](https://github.com/iisgiua/giuaschool/assets/104029568/ff0573ba-8fc4-408f-b751-35f8bdb7e6b3)

**Comment by trinko** [comment]
Questo significa che il tuo servizio di hosting sta bloccando la richiesta verso altri siti esterni.

Se stai usando Altervista, devi consentire i collegamenti esterni:

- dal pannello di controllo Altervista, clicca su **RISORSE** e poi su **Modifica Impostazioni PHP**
- scendi nella pagina sino al riquadro **Connessioni server to server**
- seleziona **Collegamento senza restrizioni** e clicca su **SALVA**

**Comment by francyoo17** [comment]
Non va lo stesso

**Comment by trinko** [comment]
> Non va lo stesso

Intendi l'aggiornamento, suppongo. 
Assicurati di aver seguito le indicazioni date, perché la procedura funziona sicuramente su Altervista.

In caso contrario, significa che il tuo servizio di hosting ha qualcosa di diverso dalla normale configurazione su Altervista: contatta il tuo gestore e segnala l'impossibilità di effettuare connessioni server-to-server.

**Comment by francyoo17** [comment]
ho installato la nuova versione  ma va in errore lo stesso 
[2024-06-14_11-45.log](https://github.com/user-attachments/files/15836297/2024-06-14_11-45.log)

**Comment by trinko** [comment]
Questo errore è dovuto alla non configurazione di alcuni parametri, in particolare controlla:
- anno_inizio
- anno_fine
- periodo1_fine
- periodo2_fine

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
