### ISSUE TITLE
Errore 500 con gli scrutini

### ISSUE THREAD

**Issue by Matyf97** [iisgiua/giuaschool#720]
Salve, ho un problema quando vado su Coordinatore > Classe > Scrutinio, nello specifico appare l'errore 500. Ho verificato nelle impostazioni degli scrutini e tutto sembra regolare. Ho anche provato ad inserire su SQL questo comando: 
`update gs_scrutinio set stato='N' where periodo='F';` ma non ha funzionato. Come posso risolvere? Mi servirebbe entro domani perché ci sono gli scrutini da effettuare.

**Comment by trinko** [comment]
Devi mandarmi il log dell'errore, altrimenti non posso capire il problema.
Per generare il log vedi: [Come fare una segnalazione di errore](https://github.com/iisgiua/giuaschool/discussions/576)

**Comment by Matyf97** [comment]
> Devi mandarmi il log dell'errore, altrimenti non posso capire il problema. Per generare il log vedi: [Come fare una segnalazione di errore](https://github.com/iisgiua/giuaschool/discussions/576)

Ecco il file di log: 
[2024-06-08_10-41.log](https://github.com/user-attachments/files/15747361/2024-06-08_10-41.log)

**Comment by trinko** [comment]
Decomprimi il file seguente e caricalo nella cartella **src/Util** andando a sovrascrivere quello esistente.
Dovrebbe risolvere il problema.






[ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15747522/ScrutinioUtil.php.zip)

**Comment by Matyf97** [comment]
> Decomprimi il file seguente e caricalo nella cartella **src/Util** andando a sovrascrivere quello esistente. Dovrebbe risolvere il problema.
> 
> [ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15747522/ScrutinioUtil.php.zip)

Funziona però non riesco a procedere con il secondo quadrimestre, va solo il quadrimestre "Giudizio Sospeso", ma io dovrei fare gli scrutini del Secondo Quadrimestre

**Comment by Matyf97** [comment]
> > Decomprimi il file seguente e caricalo nella cartella **src/Util** andando a sovrascrivere quello esistente. Dovrebbe risolvere il problema.
> > [ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15747522/ScrutinioUtil.php.zip)
> 
> Funziona però non riesco a procedere con il secondo quadrimestre, va solo il quadrimestre "Giudizio Sospeso", ma io dovrei fare gli scrutini del Secondo Quadrimestre

Risolto, grazie mille!

**Comment by Matyf97** [comment]
> > > Decomprimi il file seguente e caricalo nella cartella **src/Util** andando a sovrascrivere quello esistente. Dovrebbe risolvere il problema.
> > > [ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15747522/ScrutinioUtil.php.zip)
> > 
> > 
> > Funziona però non riesco a procedere con il secondo quadrimestre, va solo il quadrimestre "Giudizio Sospeso", ma io dovrei fare gli scrutini del Secondo Quadrimestre
> 
> Non ci posso credere, è riapparsa la schermata di errore 500, ora invio il file di log

[2024-06-08_12-25.log](https://github.com/user-attachments/files/15747576/2024-06-08_12-25.log)

**Comment by trinko** [comment]
Credo che ci siano problemi con dati di scrutinio svolti in precedenza per qualche prova.
Ti propongo quindi di ripulire tutto eseguendo i 3 comandi SQL seguenti, nell'ordine indicato.
**ATTENZIONE: i dati relativi agli scrutini finali saranno rimossi senza possibilità di recuperarli, a meno che di usare il ripristino di un backup.**

```
delete from gs_voto_scrutinio where scrutinio_id in (select id from gs_scrutinio where periodo='F');
delete from gs_esito where scrutinio_id in (select id from gs_scrutinio where periodo='F');
delete from gs_scrutinio where periodo='F';
```

**Comment by Matyf97** [comment]
> Credo che ci siano problemi con dati di scrutinio svolti in precedenza per qualche prova. Ti propongo quindi di ripulire tutto eseguendo i 3 comandi SQL seguenti, nell'ordine indicato. **ATTENZIONE: i dati relativi agli scrutini finali saranno rimossi senza possibilità di recuperarli, a meno che di usare il ripristino di un backup.**
> 
> ```
> delete from gs_voto_scrutinio where scrutinio_id in (select id from gs_scrutinio where periodo='F');
> delete from gs_esito where scrutinio_id in (select id from gs_scrutinio where periodo='F');
> delete from gs_scrutinio where periodo='F';
> ```

Inizialmente funziona ma come inserisco il Segretario dello Scrutinio appare la schermata di errore 500, mandando in tilt tutto il sistema dello Scrutinio.
[2024-06-08_13-04.log](https://github.com/user-attachments/files/15747653/2024-06-08_13-04.log)

**Comment by trinko** [comment]
Sostituisci il file allegato, come prima:

[ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15747671/ScrutinioUtil.php.zip)

**Comment by trinko** [comment]
Dimenticavo, dopo aver caricato il file sul server, ricorda di svuotare la _cache_.

**Comment by Matyf97** [comment]
> Dimenticavo, dopo aver caricato il file sul server, ricorda di svuotare la _cache_.

Funziona tutto tranne il passo 3: il voto di Educazione Civica. Mi appare la tabella per inserire il voto ma non appaiono gli alunni e, di conseguenza non posso inserire i voti. Non mi da errore, però resta la barra di caricamento che non va via.

**Comment by trinko** [comment]
Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.

**Comment by mimmomarino** [comment]
> Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.

Buonasera, ho seguito la conversazione in quanto anche io ho avuto diversi problemi con gli scrutini. Subito dopo aver caricato il file e svuotato la cache, non spuntano neanche a me i nominativi degli alunni nel momento in cui si dovrebbero inserire le valutazioni di educazione civica. La nostra scuola non ha classi articolate e/o con gruppi.

**Comment by Matyf97** [comment]
> > Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.
> 
> Buonasera, ho seguito la conversazione in quanto anche io ho avuto diversi problemi con gli scrutini. Subito dopo aver caricato il file e svuotato la cache, non spuntano neanche a me i nominativi degli alunni nel momento in cui si dovrebbero inserire le valutazioni di educazione civica. La nostra scuola non ha classi articolate e/o con gruppi.

Esatto, nemmeno io ho classi articolate. Penso sia un errore a questo punto della versione di Giuaschool

**Comment by Matyf97** [comment]
> > > Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.
> > 
> > 
> > Buonasera, ho seguito la conversazione in quanto anche io ho avuto diversi problemi con gli scrutini. Subito dopo aver caricato il file e svuotato la cache, non spuntano neanche a me i nominativi degli alunni nel momento in cui si dovrebbero inserire le valutazioni di educazione civica. La nostra scuola non ha classi articolate e/o con gruppi.
> 
> Esatto, nemmeno io ho classi articolate. Penso sia un errore a questo punto della versione di Giuaschool

Come si può vedere, questo è ciò che appare.
![image](https://github.com/iisgiua/giuaschool/assets/159051228/7b3e735c-2a60-40b0-bff0-d231349ec03e)

**Comment by mimmomarino** [comment]
> > > > Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.
> > > 
> > > 
> > > Buonasera, ho seguito la conversazione in quanto anche io ho avuto diversi problemi con gli scrutini. Subito dopo aver caricato il file e svuotato la cache, non spuntano neanche a me i nominativi degli alunni nel momento in cui si dovrebbero inserire le valutazioni di educazione civica. La nostra scuola non ha classi articolate e/o con gruppi.
> > 
> > 
> > Esatto, nemmeno io ho classi articolate. Penso sia un errore a questo punto della versione di Giuaschool
> 
> Come si può vedere, questo è ciò che appare. ![image](https://private-user-images.githubusercontent.com/159051228/337928067-7b3e735c-2a60-40b0-bff0-d231349ec03e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NzY1ODAsIm5iZiI6MTcxNzg3NjI4MCwicGF0aCI6Ii8xNTkwNTEyMjgvMzM3OTI4MDY3LTdiM2U3MzVjLTJhNjAtNDBiMC1iZmYwLWQyMzEzNDllYzAzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxOTUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTM2ZjBlMGYzYzU4MzczODUxNTE2ZTNiOGE3ZDRkNTRhYTcyYmFhYTE0ODVjOWVhMDY5M2QwMTZiNjFhODZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_20tZPHh8R4Wa6x2o0iRplKEQKX8HvKIFBJ0h6qclg)

Stessa situazione anche a me

**Comment by Matyf97** [comment]
> > > > > Mi viene un dubbio: non è che stai usando una classe articolata? Cioè con i gruppi? Perché in tal caso probabilmente c'è una configurazione errata della classe.
> > > > 
> > > > 
> > > > Buonasera, ho seguito la conversazione in quanto anche io ho avuto diversi problemi con gli scrutini. Subito dopo aver caricato il file e svuotato la cache, non spuntano neanche a me i nominativi degli alunni nel momento in cui si dovrebbero inserire le valutazioni di educazione civica. La nostra scuola non ha classi articolate e/o con gruppi.
> > > 
> > > 
> > > Esatto, nemmeno io ho classi articolate. Penso sia un errore a questo punto della versione di Giuaschool
> > 
> > 
> > Come si può vedere, questo è ciò che appare. ![image](https://private-user-images.githubusercontent.com/159051228/337928067-7b3e735c-2a60-40b0-bff0-d231349ec03e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NzY1ODAsIm5iZiI6MTcxNzg3NjI4MCwicGF0aCI6Ii8xNTkwNTEyMjgvMzM3OTI4MDY3LTdiM2U3MzVjLTJhNjAtNDBiMC1iZmYwLWQyMzEzNDllYzAzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxOTUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTM2ZjBlMGYzYzU4MzczODUxNTE2ZTNiOGE3ZDRkNTRhYTcyYmFhYTE0ODVjOWVhMDY5M2QwMTZiNjFhODZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_20tZPHh8R4Wa6x2o0iRplKEQKX8HvKIFBJ0h6qclg)
> 
> Stessa situazione anche a me

Probabilmente si tratta di un bug nella versione dell'applicazione.

**Comment by trinko** [comment]
Credo di aver capito: la classe di cui stai facendo lo scrutinio finale ha svolto sul registro anche i precedenti scrutini intermedi? Se non è così, la procedura non può funzionare, perché cerca i dati dei precedenti scrutini e non li trova.

Se hai il dubbio della presenza degli scrutini precedenti, esegui il seguente comando nella finestra SQL di PHPMyAdmin, sostituendo a **ANNO** e **SEZIONE** quelli della classe scrutinata:

```
SELECT periodo FROM gs_scrutinio s, gs_classe c WHERE s.classe_id=c.id AND
c.anno=ANNO AND c.sezione='SEZIONE'
ORDER BY data;  
```
Quando sono presenti tutti gli scrutini, devi vedere 2 righe **P **e** F** se usi due quadrimestri, o 3 righe **P S** e **F** se usi i trimestri.

**Comment by mimmomarino** [comment]
> Credo di aver capito: la classe di cui stai facendo lo scrutinio finale ha svolto sul registro anche i precedenti scrutini intermedi? Se non è così, la procedura non può funzionare, perché cerca i dati dei precedenti scrutini e non li trova.
> 
> Se hai il dubbio della presenza degli scrutini precedenti, esegui il seguente comando nella finestra SQL di PHPMyAdmin, sostituendo a **ANNO** e **SEZIONE** quelli della classe scrutinata:
> 
> ```
> SELECT periodo FROM gs_scrutinio s, gs_classe c WHERE s.classe_id=c.id AND
> c.anno=ANNO AND c.sezione='SEZIONE'
> ORDER BY data;  
> ```
> 
> Quando sono presenti tutti gli scrutini, devi vedere 2 righe **P e F** se usi due quadrimestri, o 3 righe **P S** e **F** se usi i trimestri.

Sì, ho già svolto lo scrutinio del primo quadrimestre sul registro. Nel database sono inseriti i risultati del primo quadrimestre delle classi.

**Comment by trinko** [comment]
Rispondi a queste due domande:
1) hai effettuato tutti gli aggiornamenti dopo l'uscita della versione 1.5.8?
2) quali lettere vengono mostrate eseguendo il comando SQL come indicato nel mio precedente messaggio?

**Comment by Matyf97** [comment]
> Credo di aver capito: la classe di cui stai facendo lo scrutinio finale ha svolto sul registro anche i precedenti scrutini intermedi? Se non è così, la procedura non può funzionare, perché cerca i dati dei precedenti scrutini e non li trova.
> 
> Se hai il dubbio della presenza degli scrutini precedenti, esegui il seguente comando nella finestra SQL di PHPMyAdmin, sostituendo a **ANNO** e **SEZIONE** quelli della classe scrutinata:
> 
> ```
> SELECT periodo FROM gs_scrutinio s, gs_classe c WHERE s.classe_id=c.id AND
> c.anno=ANNO AND c.sezione='SEZIONE'
> ORDER BY data;  
> ```
> 
> Quando sono presenti tutti gli scrutini, devi vedere 2 righe **P e F** se usi due quadrimestri, o 3 righe **P S** e **F** se usi i trimestri.

Ah ecco! Io non ho svolto gli scrutini del primo quadrimestre, sicuramente è questo che causa il problema. Devo per forza fare gli scrutini oppure esiste un comando SQL che mi permette di inserire in automatico 6 a tutti di tutte le classi giusto per procedere con il secondo quadrimestre?

**Comment by trinko** [comment]
> Ah ecco! Io non ho svolto gli scrutini del primo quadrimestre, sicuramente è questo che causa il problema. Devo per forza fare gli scrutini oppure esiste un comando SQL che mi permette di inserire in automatico 6 a tutti di tutte le classi giusto per procedere con il secondo quadrimestre?

Ho modificato la procedura: tieni presente che se mancano gli scrutini precedenti il controllo sul limite massimo di assenze (25% di monte ore) non potrà essere svolto. 

Scarica il file allegato e sovrascrivilo sempre nella cartella **src/Util**. 
Svuota anche la cache, poi **torna indietro al primo passo dello scrutinio** e quindi procedi normalmente.

[ScrutinioUtil.php.zip](https://github.com/user-attachments/files/15751048/ScrutinioUtil.php.zip)

**Comment by mimmomarino** [comment]
Tutto risolto, non avevo fatto l'aggiornamento. Grazie mille.

**Comment by Matyf97** [comment]
> Tutto risolto, non avevo fatto l'aggiornamento. Grazie mille.

Anche io ho risolto utilizzando il file php. Grazie mille

**Comment by trinko** [comment]
La segno come segnalazione chiusa
