### ISSUE TITLE
ERRORE 500 PAGINA SCRUTINI

### ISSUE THREAD

**Issue by dannycastellano** [iisgiua/giuaschool#721]
Buonasera,
sia quando accedo da Docente, sia quando accedo tramite l'alias del Docente andando nella pagina Scrutini (sotto il menù coordinatore) compare sempre la pagina con l'errore: "Oops! An Error Occurred - The server returned a 500 Internal Server Error".

Ringrazio in anticipo e attendo riposta.

_Allego file log (sperando sia quello giusto):_
[2024-06-11_22-46.log](https://github.com/user-attachments/files/15794644/2024-06-11_22-46.log)

**Comment by trinko** [comment]
Assicurati di:
- aver installato gli ultimi aggiornamenti;
- che per le classe siano state configurate le cattedre;
- che nella classe siano stati inseriti gli alunni.

**Comment by dannycastellano** [comment]
Ok, per testare avevo creato una classe, con una cattedra, un docente e un alunno ma mi ritrovo quell'errore, non so se sia necessario creare più dati

**Comment by trinko** [comment]
Allora, controlla che:
- l'alunno deve essere abilitato e senza frequenza all'estero;
- la cattedra deve essere attiva, di tipo NORMALE e non di Sostegno;
- il docente deve essere abilitato.

**Comment by dannycastellano** [comment]
Risolto grazie

**Comment by trinko** [comment]
La segno come segnalazione chiusa
