### ISSUE TITLE
problema quando vai nella sezione staff

### ISSUE THREAD

**Issue by francyoo17** [iisgiua/giuaschool#722]
salve mi esce errore quando vado in staff 
[2024-06-13_21-20.log](https://github.com/user-attachments/files/15827668/2024-06-13_21-20.log)

**Comment by trinko** [comment]
Sembra che ci siano dati incongruenti nel database. In particolare, dovrebbe esserci almeno un avviso per il quale non esiste l'indicazione del docente che l'ha inserito.

Hai forse effettuato modifiche direttamente sui dati esistenti nel database?

**Comment by francyoo17** [comment]
si ho messo per sbaglio 2 dirigenti scolastici

**Comment by trinko** [comment]
Ma l'hai riprovato con la versione aggiornata?

**Comment by francyoo17** [comment]
si ho provato  con la versione aggiornata

**Comment by trinko** [comment]
> si ho provato con la versione aggiornata

Dovresti caricare il log dell'errore del sistema aggiornato: non è detto che sia lo stesso problema.

**Comment by francyoo17** [comment]
e uguale il log

**Comment by trinko** [comment]
Ok, per vedere i dati incongruenti presenti nel database, prova ad eseguire il seguente comando nella finestra SQL di PHPMyAdmin. 
```
select id,data,oggetto
from gs_avviso
where docente_id is not null;
```
Dovrebbe visualizzare i dati degli avvisi con dati incongruenti.

Se viene confermata la presenza di avvisi con dati incongruenti, puoi rimuoverli con i comandi seguenti:
```
delete from gs_avviso_utente where avviso_id IN (select id from gs_avviso where docente_id is null);
delete from gs_avviso_classe where avviso_id IN (select id from gs_avviso where docente_id is null);
delete from gs_avviso_sede where avviso_id IN (select id from gs_avviso where docente_id is null);
delete from gs_avviso where id IN (select id from gs_avviso where docente_id is null);
```

**Comment by trinko** [comment]
Scusa, ho sbagliato a scrivere il primo comando che visualizza i dati errati.
Il comando corretto è il seguente:

```
select id,data,oggetto
from gs_avviso
where docente_id is null;
```

**Comment by francyoo17** [comment]
![Immagine 2024-06-18 190521](https://github.com/iisgiua/giuaschool/assets/104029568/a0e0b37e-1afa-4b75-9375-af6cd653c34a)

**Comment by trinko** [comment]
Purtroppo non riesco a riprodurre l'errore in nessun modo.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
