### ISSUE TITLE
problema nel passaggio del anno 2024/2025

### ISSUE THREAD

**Issue by francyoo17** [iisgiua/giuaschool#723]
salve non riesco ad passare al anno 2024/2025

[2024-06-14_11-52.log](https://github.com/user-attachments/files/15836391/2024-06-14_11-52.log)

**Comment by trinko** [comment]
L'errore è dovuto alla mancanza dell'utente PRESIDE.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
