### ISSUE TITLE
Problema scrutinio recupero debiti

### ISSUE THREAD

**Issue by trinko** [iisgiua/giuaschool#732]
### Discussed in https://github.com/iisgiua/giuaschool/discussions/731

<div type='discussions-op-text'>

<sup>Originally posted by **Davide031** June 23, 2024</sup>
Buonasera quando io schiaccio per impostare l esito per lo scrutinio per il recupero debiti fa un caricamento infinito come posso risolvere?</div>

**Comment by trinko** [comment]
Hai controllato la coerenza delle date dei periodi configurati?

**Comment by Davide031** [comment]
Assolutamente si

**Comment by Davide031** [comment]
Sono messi correttamente ma continua a darmi caricamenti infiniti come risolvo?

**Comment by Davide031** [comment]
[2024-06-23_21-09.log.txt](https://github.com/user-attachments/files/15945726/2024-06-23_21-09.log.txt)
Ecco il log ma non so cosa si riesca a fare

**Comment by trinko** [comment]
Non avevo capito che stessi già svolgendo lo scrutinio sospeso.
Questo scrutinio è ancora sotto revisione. Credo che sarà rilasciata la nuova versione testata per le prime settimane di luglio.

**Comment by Davide031** [comment]
Ah ok speriamo che riusciamo ad averlo Prima possibile

Il dom 23 giu 2024, 23:26 Antonello Dessì ***@***.***> ha
scritto:

**Comment by Davide031** [comment]
Ok, ora però devo eliminare i dati degli scrutini sospesi in modo da poter
tornare alla schermata dove posso scaricare i risultati degli scrutini
finali, come devo fare?

Il dom 23 giu 2024, 23:28 DAVIDE COCO ***@***.***> ha scritto:

**Comment by Davide031** [comment]
Buonasera mi risulta un aggiornamento sarebbero questi scrutini? Posso svolgerlo?

**Comment by trinko** [comment]
No, verrà rilasciata la nuova versione 1.5.9

**Comment by Davide031** [comment]
Circa quando?

**Comment by Davide031** [comment]
E cosa comprenderà

**Comment by trinko** [comment]
Vedi #735

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
