### ISSUE TITLE
Configurazione API con SSO Google

### ISSUE THREAD

**Issue by Matyf97** [iisgiua/giuaschool#734]
Salve, io sto cercando di collegare Google Workspace con l'accesso tramite SSO su Giuaschool, ma non ho la minima idea di come procedere. Potrei essere aiutato? Grazie

**Comment by Matyf97** [comment]
> Salve, io sto cercando di collegare Google Workspace con l'accesso tramite SSO su Giuaschool, ma non ho la minima idea di come procedere. Potrei essere aiutato? Grazie

Sul Registro, ho configurato tutto come deve essere con anche il dominio della scuola, eppure non riesco a configurare le API di Google. Le loro guide sono al quanto complesse e non si riesce a capire quasi nulla delle loro spiegazioni su come creare Credenziali OAuth o cose del genere, lei potrebbe aiutarmi?

**Comment by trinko** [comment]
Non posso aiutarti molto, perché quasi  tutto va fatto sulla piattaforma Google: io l'ho fatto diversi anni fa e ora hanno cambiato un tutto.

Segui qualche tutorial, ad esempio ho trovato [questo](https://www.agenziawebeureka.it/come-usare-chiavi-api-di-google/).

Devi generate le chiavi (API KEY) per **Admin SDK API**, in modo da avere la gestione degli utenti. 

Una volta generate le chiavi le devi impostare sul file **.env**:
```
OAUTH_GOOGLE_CLIENT_ID='XXX'
OAUTH_GOOGLE_CLIENT_SECRET='XXX'
OAUTH_GOOGLE_CLIENT_HD='nomescuola.edu.it'
```

L'ultimo parametro (OAUTH_GOOGLE_CLIENT_HD) contiene il tuo dominio di Google Workspace.

**Comment by Matyf97** [comment]
> Non posso aiutarti molto, perché quasi tutto va fatto sulla piattaforma Google: io l'ho fatto diversi anni fa e ora hanno cambiato un tutto.
> 
> Segui qualche tutorial, ad esempio ho trovato [questo](https://www.agenziawebeureka.it/come-usare-chiavi-api-di-google/).
> 
> Devi generate le chiavi (API KEY) per **Admin SDK API**, in modo da avere la gestione degli utenti.
> 
> Una volta generate le chiavi le devi impostare sul file **.env**:
> 
> ```
> OAUTH_GOOGLE_CLIENT_ID='XXX'
> OAUTH_GOOGLE_CLIENT_SECRET='XXX'
> OAUTH_GOOGLE_CLIENT_HD='nomescuola.edu.it'
> ```
> 
> L'ultimo parametro (OAUTH_GOOGLE_CLIENT_HD) contiene il tuo dominio di Google Workspace.

Ok, grazie. Solo un'informazione: il Registro viene identificato come Applicazione Web oppure come altra applicazione? Mi serve per creare le API

**Comment by trinko** [comment]
Applicazione web va bene.

**Comment by Matyf97** [comment]
> Applicazione web va bene.

Alcune persone mi dicono che su Altervista non è molto semplice configurare le API di Google, puoi confermarmi? Perché ci tengo ad utilizzare le API.

**Comment by trinko** [comment]
Non so, non ho mai provato su Altervista.

**Comment by trinko** [comment]
> Ok, ho fatto il Registro su Netsons (registrodavinci.netsons.org/public/login/form) però sulle API di Google non riesco a configurare il Redirect URI corretto. Quale redirect uri dovrei inserire?

Dovrebbe essere: 
  https://registrodavinci.netsons.org/public/login/gsuite/check
che mi pare sia quello che hai impostato. 

Forse non l'hai autorizzato, [vedi dettagli](https://developers.google.com/identity/protocols/oauth2/web-server?hl=it#authorization-errors-redirect-uri-mismatch)

**Comment by trinko** [comment]
Inoltre hai impostato nel file .env i dati seguenti?
```
OAUTH_GOOGLE_CLIENT_ID='XXX'
OAUTH_GOOGLE_CLIENT_SECRET='XXX'
OAUTH_GOOGLE_CLIENT_HD='nomescuola.edu.it'
```
Dopo aver modificato il file **.env**, ricorda di svuotare la cache.

**Comment by Matyf97** [comment]
> Inoltre hai impostato nel file .env i dati seguenti?
> 
> ```
> OAUTH_GOOGLE_CLIENT_ID='XXX'
> OAUTH_GOOGLE_CLIENT_SECRET='XXX'
> OAUTH_GOOGLE_CLIENT_HD='nomescuola.edu.it'
> ```
> 
> Dopo aver modificato il file **.env**, ricorda di svuotare la cache.

Su 
```OAUTH_GOOGLE_CLIENT_HD=```
 bisogna inserire il dominio della Scuola o il dominio del Registro Elettronico? Deve essere per forza un dominio .edu.it?

**Comment by trinko** [comment]
> Su `OAUTH_GOOGLE_CLIENT_HD=` bisogna inserire il dominio della Scuola o il dominio del Registro Elettronico? Deve essere per forza un dominio .edu.it?

E' il dominio della scuola, o, per essere più chiari, il dominio usato nelle mail degli utenti.
Cioè, se i tuoi utenti sono del tipo utente@scuola.it, il dominio da indicare è **scuola.it**

Serve per semplificare l'accesso degli utenti, che dovranno inserire solo la username perché il dominio è bloccato.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
