### ISSUE TITLE
Errore nel download delle password degli utenti

### ISSUE THREAD

**Issue by istitutoenricomattei** [iisgiua/giuaschool#748]
Buonasera, riporto come ho già scritto nell'altra sezione l'errore che mi da quando, avendo aggiornato dalla 1.5.3 alla 1.5.9, provo a scaricare il pdf delle password di un qualsiasi utente. Se il problema è quello di avere saltato versione per versione, com'è possibile risolverlo? grazie mille in anticipo

**Indica come riprodurre l'errore**

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)

**Comment by trinko** [comment]
Spiegami nel dettaglio come hai fatto l'aggiornamento di versione: hai modificato anche il database o hai copiato solo i file del codice?
Inoltre, se hai sovrascritto i file del codice, i file nuovi li hai presi dall file compresso che hai trovato  [qui](https://iisgiua.github.io/giuaschool-docs/latest-release.html) ?

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
