### ISSUE TITLE
URGENTE Errore passaggio numero 7 della procedura di passaggio al nuovo AS

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#752]
Buongiorno, sto riscontrando problemi con il passaggio numero 7 della procedura di passaggio al nuovo anno scolastico...mi dice "ooops an error occurred".
Allego log errori.
Grazie.
[2024-09-10_08-27.log](https://github.com/user-attachments/files/16940431/2024-09-10_08-27.log)

**Comment by trinko** [comment]
Il passo 7 rimuove gli utenti disabilitati e gli alunni promossi al termine della quinta.
Nel tuo caso non può rimuovere uno o più utenti perché è rimasto un riferimento in una imprecisata tabella del database a questi utenti.
Non dovrebbe succedere, perché tutti i riferimenti presenti sono rimossi prima della cancellazione dell'utente. 

Comunque puoi ignorare il problema, perché ti ritroverai solo degli utenti in più che puoi disabilitare.

Non rieseguire la procedura, perché potresti perdere dati.
Vai invece all'ultimo passo della procedura vai direttamente inserendo l'indirizzo: 
  **nome_sito://public/sistema/nuovo/8**

**Comment by Lucaccc** [comment]
> Il passo 7 rimuove gli utenti disabilitati e gli alunni promossi al termine della quinta. Nel tuo caso non può rimuovere uno o più utenti perché è rimasto un riferimento in una imprecisata tabella del database a questi utenti. Non dovrebbe succedere, perché tutti i riferimenti presenti sono rimossi prima della cancellazione dell'utente.
> 
> Comunque puoi ignorare il problema, perché ti ritroverai solo degli utenti in più che puoi disabilitare.
> 
> Non rieseguire la procedura, perché potresti perdere dati. Vai invece all'ultimo passo della procedura vai direttamente inserendo l'indirizzo: **nome_sito://public/sistema/nuovo/8**
