### ISSUE TITLE
Errore modifica alunni

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#754]
Buonasera.
Ho effettuato l'importazione degli alunni tramite csv; dopo averlo fatto, quando provo a cliccare sulla voce ALUNNI>MODIFICA, mi da errore.
A cosa può essere dovuto?
Allego log errori.

Grazie.

[2024-09-15_19-33.log](https://github.com/user-attachments/files/17006727/2024-09-15_19-33.log)

**Comment by trinko** [comment]
E' un errore strano: dice che trova un valore per i numeri di telefono dell'utente che non è del tipo atteso (dovrebbe essere un vettore).
Mai capitato, nonostante le tante importazioni che ho fatto. 

Controlla il file CSV che hai usato per il caricamento, per vedere cosa c'è nel campo dei numeri di telefono.

**Comment by Lucaccc** [comment]
> E' un errore strano: dice che trova un valore per i numeri di telefono dell'utente che non è del tipo atteso (dovrebbe essere un vettore). Mai capitato, nonostante le tante importazioni che ho fatto.
> 
> Controlla il file CSV che hai usato per il caricamento, per vedere cosa c'è nel campo dei numeri di telefono.

Il campo era stato lasciato vuoto...si prevedeva di inserire in seguito i numeri di telefono...quindi non capisco.

**Comment by trinko** [comment]
> Il campo era stato lasciato vuoto...si prevedeva di inserire in seguito i numeri di telefono...quindi non capisco.

Forse c'è qualche errore nel formato del file CSV.
Comunque fai questa prova: riusa lo stesso file CSV e metti 0 come numero di telefono, in modo che non sia vuoto. Quindi importa nuovamente per modificare i dati esistenti e vedi se cambia qualcosa.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
