### ISSUE TITLE
Errore configurazione moduli

### ISSUE THREAD

**Issue by mimmomarino** [iisgiua/giuaschool#756]
Buongiorno,
Nella sezione della configurazione dei moduli (utente amministratore), non fa selezionare il nome del file del modello.
Se, dopo aver compilato tutti i dati richiesti dalla pagina, clicco su "Continua", il registro mi indirizza alla pagina di errore

Allego file di LOG
[2024-09-19_12-52.log](https://github.com/user-attachments/files/17057843/2024-09-19_12-52.log)

**Comment by trinko** [comment]
Ma hai caricato il template nella cartella **PERSONAL/data/moduli**?
I template in questa cartella devono avere come nome:

-   **nome_senza_spazi.html.twig**

**Comment by trinko** [comment]
La segno come segnalazione chiusa
