### ISSUE TITLE
Errore inserimento piani di lavoro

### ISSUE THREAD

**Issue by Lucaccc** [iisgiua/giuaschool#757]
Buongiorno,
sto riscontrando un problema con il caricamento dei piani di lavoro.
In particolare, questo si verifica solo per una classe..mi da errore 500.
Non vorrei ci fosse stato qualche problema in fase di passaggio al nuovo anno..
Allego il log degli errori...può darmi una mano a capire?
Grazie.

[2024-09-25_12-43.log](https://github.com/user-attachments/files/17129563/2024-09-25_12-43.log)

**Comment by robertopadovesi** [comment]
È vero! Anche da noi, riscontriamo problemi riguardanti il caricamento dei
piani di lavoro e prove di evacuazione, ci da sempre errore, però in tutte
le classi, non solo in una!

Il giorno mer 25 set 2024 alle ore 12:46 Lucaccc ***@***.***>
ha scritto:

**Comment by trinko** [comment]
L'errore è un problema di permessi sulle cartelle:

> Cannot rename /membri/XXX/FILES/tmp/XXX.pdf" to "/membri/XXX/FILES/archivio/classi/XXX/XXX.pdf":  Permission denied

Devi controllare se c'è qualcosa di diverso nei permessi delle cartelle che stai usando. Se prima funzionava, è probabile che ricreando la cartella al passaggio al nuovo anno, queste non hanno più i permessi previsti per la modifica dei file... 

Vedi se ci sono differenze sui permessi tra:
- /membri/XXX/FILES/
- /membri/XXX/FILES/archivio/
- /membri/XXX/FILES/archivio/classi/
- /membri/XXX/FILES/archivio/classi/CLASSE/

**Comment by robertopadovesi** [comment]
Ciao, @Lucaccc! Avrei una domanda da farti, per caso, conosci una certa Federica Bianchi, che ti abbia chiesto di qualche scuola a cui potersi rivolgersi? Non è una domanda spam o una domanda phising, ma è solo un informazione. Grazie!

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
