### ISSUE TITLE
Errore nel caricamento dei piani di lavoro, programmi finali e relazioni finali. Problemi nella compilazione delle prove di evacuazione. Problemi nella consegna delle credenziali del registro elettronico ad ATA, docenti e famgilie.

### ISSUE THREAD

**Issue by robertopadovesi** [iisgiua/giuaschool#759]
**Descrivi il problema**

- I docenti, al caricamento dei piani di lavoro, programmi finali e relazioni finali riscontrano problemi nel caricamento, facendo apparire la scheda di errore, scheda di servizio temporaneamente sospeso o facendoli direttamente uscire dal registro elettronico. Stessa problematica nel caricamento e nella compilazione delle prove di evacuazione.
- Da fine agosto, problemi nella consegna delle credenziali del registro elettronico a famiglie, docenti e ATA. Le credenziali dal sistema, risultando inviate ma gli utenti non le ricevono.

**Indica come riprodurre l'errore**

- Caricando i piani di lavoro, programmi finali e relazioni finali. Compilando le prove di evacuazione.
- Inviando le credenziali a docenti, famiglie e ATA.

**File di LOG**

Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
[2024-09-28_09-40.log](https://github.com/user-attachments/files/17173632/2024-09-28_09-40.log)

**Menzioni**

@trinko @zerai @bfabio @MatteoGheza

**Comment by trinko** [comment]
Se non ricordo male, tu stai usando un servizio di hosting che usa versione particolare di MySQL che non è pienamente supportata.
Ricordo una segnalazione simile tempo fa. Me lo confermi? Mi serve anche la versione di MySQL in uso sul server.

**Comment by trinko** [comment]
Mi riferisco a questa segnalazione:  #636

**Comment by robertopadovesi** [comment]
Ciao! sì, sono io.

**Comment by robertopadovesi** [comment]
Ora controllo la mia versione, aspetta un attimo.

**Comment by robertopadovesi** [comment]
![image](https://github.com/user-attachments/assets/917676a9-06a6-4522-99fd-a5cd4bd2076d)
Queste sono le informazioni del mio database! dovrei cercare in server del database?
@trinko

**Comment by robertopadovesi** [comment]
Buongiorno! vorrei segnalare, che il responsabile BES della scuola, che entro la fine della settimana doveva caricare la documentazione degli alunni sul registro, non riesce a caricarla sul sistema e riscontra gli stessi problemi riscontrati nel caricamento dei piani di lavoro, programmi finali e relazioni finali.
Come si può procedere? il problema è risolvibile oppure è definitivo? attendo tue!
@trinko

**Comment by robertopadovesi** [comment]
Buona domenica! ha novità?
@trinko

Il giorno sab 28 set 2024 alle ore 11:08 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Come detto, il problema sembra legato alla versione del server database (Percona server) che è cambiata rispetto a quella della precedente segnalazione. E come avevo detto non è lo standard previsto per l'uso del registro giuaschool.

L'analisi per capire se è possibile effettuare modifiche sull'applicazione per renderla compatibile con questa versione richiede parecchio tempo per effettuare delle verifiche. 
Purtroppo al momento ho altre priorità pressanti.

**Comment by trinko** [comment]
Visto che stai usando un servizio di hosting a pagamento, contatta l'assistenza e chiedi se è possibile effettuare un downgrade della versione del database server, dalla attuale **8.0** alla precedente **5.7**.

Questo dovrebbe risolvere i problemi, visto che in precedenza funzionava tutto.

**Comment by trinko** [comment]
Rettifico quanto ho scritto in precedenza, nei messaggi che ho cancellato.

Può essere che il problema sia dovuto ad altro.
Poiché nel file di log precedente non c'erano informazioni utili, ho bisogno del log degli errori per ciascuno degli errori indicati:
- caricamento piani di lavoro 
- caricamento documento bes

**Comment by robertopadovesi** [comment]
Va bene!
comunque ho letto del downgrade, se possibile proverei a farlo, grazie

**Comment by robertopadovesi** [comment]
Buonasera! ho provato a chiedere per il downgrade
Il problema è un altro: dicono che il downgrade non è possibile effettuarlo
perché la 5.7, almeno in tutto il mondo, non è più supportata dal 2023.
Come possiamo fare?

Il giorno dom 29 set 2024 alle ore 21:09 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
Per capire meglio quale possa essere l'errore ho bisogno dei log di errore specifici per ogni tipo di errore.

**Comment by robertopadovesi** [comment]
Buongiorno! finalmente, stamattina, sono riuscito a provvedere! per le credenziali ho fatto solo ata, però il problema persiste anche per gli utenti docenti e genitori

[inviocredenziali.log](https://github.com/user-attachments/files/17349545/inviocredenziali.log)
[doc15maggio.log](https://github.com/user-attachments/files/17349546/doc15maggio.log)
[relazionifinali.log](https://github.com/user-attachments/files/17349547/relazionifinali.log)
[programmisvolti.log](https://github.com/user-attachments/files/17349548/programmisvolti.log)
[piani di lavoro.log](https://github.com/user-attachments/files/17349549/piani.di.lavoro.log)
[provedievacuazione.log](https://github.com/user-attachments/files/17349550/provedievacuazione.log)

**Comment by robertopadovesi** [comment]
Buongiorno! finalmente, stamattina, sono riuscito a provvedere! per le credenziali ho fatto solo ata, però il problema persiste anche per gli utenti docenti e genitori

[inviocredenziali.log](https://github.com/user-attachments/files/17349552/inviocredenziali.log)
[doc15maggio.log](https://github.com/user-attachments/files/17349553/doc15maggio.log)
[relazionifinali.log](https://github.com/user-attachments/files/17349554/relazionifinali.log)
[programmisvolti.log](https://github.com/user-attachments/files/17349555/programmisvolti.log)
[piani di lavoro.log](https://github.com/user-attachments/files/17349556/piani.di.lavoro.log)
[provedievacuazione.log](https://github.com/user-attachments/files/17349558/provedievacuazione.log)

@trinko @zerai @bfabio @MatteoGheza

**Comment by trinko** [comment]
Controlla se la versione del **PHP** è diversa dalla 8.0 e nel caso impostala a questa versione.

**Comment by robertopadovesi** [comment]
ci provo! ora vedo e ti faccio sapere

**Comment by robertopadovesi** [comment]
> Controlla se la versione del **PHP** è diversa dalla 8.0 e nel caso impostala a questa versione.

la versione è la 8.3, provo ad abbassarla e impostarla alla 8.0

**Comment by robertopadovesi** [comment]
> Controlla se la versione del **PHP** è diversa dalla 8.0 e nel caso impostala a questa versione.

ora provo a vedere se sul Registro funziona tutto!

**Comment by robertopadovesi** [comment]
> Controlla se la versione del **PHP** è diversa dalla 8.0 e nel caso impostala a questa versione.

novità! il flag sul registro si apre e permette di caricare i documenti!
tutta via per prove di evacuazione e credenziali, ancora nulla, non funziona

**Comment by robertopadovesi** [comment]
> > > Controlla se la versione del **PHP** è diversa dalla 8.0 e nel caso impostala a questa versione.
> > 
> > 
> > novità! il flag sul registro si apre e permette di caricare i documenti! tutta via per prove di evacuazione e credenziali, ancora nulla, non funziona! @trinko
> 
> Ok, dovresti rifare il log degli errori per le pagine che non funzionano.

certo! ora, nel pomeriggio lo faccio

> Collaborator

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
