### ISSUE TITLE
non riesco ad caricare i piani di lavoro 

### ISSUE THREAD

**Issue by francy202111111** [iisgiua/giuaschool#767]
mi va in errore equando cerco di caricare i piani di lavoro 
[2024-10-16_09-28.log](https://github.com/user-attachments/files/17391149/2024-10-16_09-28.log)

**Comment by trinko** [comment]
Il log che hai inserito non da' nessuna informazione, non risulta neanche la pagine dove avviene il caricamento del piano di lavoro.
Forse hai sbagliato ad inserire l'orario per estrarlo o non hai seguito bene le indicazioni per la generazione del log degli errori.

Senza queste informazioni non posso aiutarti.

**Comment by francy202111111** [comment]
[2024-10-16_11-23.log](https://github.com/user-attachments/files/17392971/2024-10-16_11-23.log)

**Comment by trinko** [comment]
Ho visto che questa volta hai attivato il DEBUG, ma non hai eseguito la pagina che genera l'errore, per cui nel log non c'è nessuna informazione utile.

Per generare il log degli errori, seguire la procedura:

  -  come utente amministratore, andare alla pagina Sistema > Manutenzione e abilitare il debug;
  -  eseguire la pagina che causa l'errore e segnarsi l'ora in cui viene eseguita;
  -  tornare alla pagina Sistema > Manutenzione e estrarre il log, indicando l'ora che è stata segnata in precedenza;
  -  scaricare il file di log e allegarlo al messaggio di segnalazione

**Comment by francy202111111** [comment]
[2024-10-17_10-15.log](https://github.com/user-attachments/files/17408762/2024-10-17_10-15.log)

**Comment by trinko** [comment]
Mi spiace, nel log che riporti non c'è nessuna informazione utile a capire il problema.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
