### ISSUE TITLE
non vedo  Piu i voti 

### ISSUE THREAD

**Issue by francyoo17** [iisgiua/giuaschool#771]
non ce nessun errore ma non mi fa mettere i voti i voti sono inesistenti

**Comment by trinko** [comment]
La cosa più probabile è che sia dovuto alla configurazione delle date di inizio/fine anno scolastico e dei periodi intermedi.
Controlla i parametri in **SISTEMA > PARAMETRI** e le date degli scrutini in **SCUOLA > SCRUTINI**

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
