### ISSUE TITLE
Codice PHP visualizzato invece che pagina di login

### ISSUE THREAD

**Issue by 217eastbroadway** [iisgiua/giuaschool#779]
Quando la pagina web viene caricata (mi riferisco a registro.giua.edu.it) viene mostrato un segmento di codice PHP invece che la pagina di login iniziale.

Non e' chiaro come riprodurre questo bug in quanto succede a volte randomicamente.

**Allego una foto con il bug esposto**
![bug](https://github.com/user-attachments/assets/50810fc4-2851-4a0a-8255-640096ae6cd0)

**Comment by trinko** [comment]
E' dovuto alla cache del tuo browser... In altre parole ti sta mostrando una pagina vecchia di qualche giorno fa.
Devi aggiornare la pagina con l'apposito pulsante del browser (o da tastiera CONTROL R).
Megio ancora se pulisci la cache del browser.

**Comment by 217eastbroadway** [comment]
Effettivamente non avevo aperto il sito dall'ultima volta che questa scritta usci'.
Aggiornando la cache funziona perfettamente :)
