### ISSUE TITLE
importazione orario docente

### ISSUE THREAD

**Issue by sempliciniluigi89** [iisgiua/giuaschool#786]
buongiorno, non appena importo l'orario del docente ricevo il seguente messaggio:Errore L'ora non è valida nel record 1. allego il csv d'esempio 
[orario.csv](https://github.com/user-attachments/files/17782978/orario.csv)

**Comment by trinko** [comment]
L'orario attualmente non è usato e di conseguenza la funzione di importazione è da revisionare.
Sarà sistemato quando riuscirò a trovare il tempo per attivare questa funzionalità.

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
